### ISSUE TITLE
Shortcuts addon broken

### ISSUE THREAD

**Issue by anjiax** [Windower/Issues#1000]
Hello, 

I'm having an issue with shortcuts addon. I put the error i get below. I've tried uninstalling windower, shortcuts a few times and no fix. My husband's PC has the same addons and his addon works (we looked at the LUA and they are the same). I also had him send me his LUA file, wont work for me.

Shortcuts: LUA runtime error: shortcuts/statics.lua:200: bad argument #1 to "pairs" (table expected, nil)

The word pairs on line 200 of my LUA is highlighted bright blue, but I'm not sure what to try to fix it.

**Comment by Byrth** [comment]
I am 99% sure there is just something wrong with your resources. Here is a zipped version:
https://www.dropbox.com/s/ii47tj6qtv3ccq7/res.zip?dl=0

I am going to close this so it is lost in the sands of time and no one else uses the link to download outdated resources in two months, subsequently opening another issue asking us why X gear doesn't exist.
