### ISSUE TITLE
Windower DEV Huge CPU Usage

### ISSUE THREAD

**Issue by DanielHazzard** [Windower/Issues#1001]
Fixes are amazing, only issue I seem to have limited to the DEV version is HUGE CPU usage when dual boxing.

On the normal version I get max ~10% on 1920x1080, Supersampled on multiple accounts.

However, when I upgrade to the DEV this jumps to 25% in the mog-house and on all accounts no matter what the settings. 1920x1080 Supersampled and even 800x600 non supersampled. Guaranteed 20+ CPU.

What's odd is the HUGE CPU only begins when I log into a mule, then the previous one is 25%+ with the newly logged in one less than 10% and the same when I log another then the previous two are ~25%+ with the newly logged in one under 10%.

Intel i7-770k (4.90 GHZ)
Geforce 1080 TI
16GB RAM

Reinstalling the previous version and they drop right back down to 10% on 1920x1080 around 4% on mules.

**Comment by cairthenn** [comment]
The good news is that CPU profiling agrees with you!

**Comment by cairthenn** [comment]
The second good news is I believe the issue is solved (LuaCore 2.2.1.1). Let us know if any functionality breaks. Thanks for the report!
