### ISSUE TITLE
Treasury appears to be crashing gameplay

### ISSUE THREAD

**Issue by GenTeal** [Windower/Issues#1003]
Each time I load Treasury, the game crashes.  At 1st I thought it was an error in the settings.  But I removed treasury from the addon folder.  Reloaded Windower and reinstalled a fresh Treasury. Reloaded game, with Treasury loaded, game ran fine.  entered drop add illuminink, game continues to run fine.  Entered drop add flint stone, game now crashes.

I have gone as far as unloading all addon's  and plugins except for Treasury and game still crashes.  

I tried several times to create a dump file to attach, but have been unsuccessful to create one.

**Comment by GenTeal** [comment]
I am still unable to create a dump file.  Please assist

**Comment by z16** [comment]
Not really possible to assist without a crash dump or without more information and testing on your part. Please paste the contents of the settings file here so we can look at it, and see if we can reproduce it.

Did you run the DumpSetup program to set up crash dumps?

**Comment by GenTeal** [comment]
I installed a dump program i found through a link here on windower.net.  when i pasted the files to this box, it said files not supported.  I tried installing a windows dump program but it is not installing or I just can not locate it.
Your assistance in creating a dump file is very much needed.

**Comment by joshk6656** [comment]
Is this what you used?

https://github.com/Windower/Issues/wiki/Creating-crash-dumps-with-Windbg

**Comment by GenTeal** [comment]
Yes, and I can not locate it to get dump file

**Comment by GenTeal** [comment]
WinDbg can not be found on my computer.

**Comment by GenTeal** [comment]
<?xml version="1.1" ?>
<settings>
    <global>
        <AutoDrop>false</AutoDrop>
        <AutoStack>true</AutoStack>
        <Delay>0</Delay>
        <Drop />
        <Lot />
        <Pass />
        <Verbose>false</Verbose>
    </global>
    <sovnek>
        <Drop>Flint Stone</Drop>
    </sovnek>
</settings>

**Comment by GenTeal** [comment]
[settings.txt](https://github.com/Windower/Issues/files/2091951/settings.txt)

**Comment by GenTeal** [comment]
I am using Windows 7 64bit

**Comment by joshk6656** [comment]
Did you do this section? You need to install it...

Downloading and Installing WinDbg

WinDbg is the debugger offered by Microsoft with the Windows SDK
<http://www.microsoft.com/en-us/download/details.aspx?id=8279>. You only
need to install the Debugging Tools for Windows

**Comment by GenTeal** [comment]
ok, I followed the link to a web based application.  I removed all checkmarks except Debugging Tools for Windows.  It did the installation and I clicked Finish.  But I can not locate program.

**Comment by Nifim** [comment]
No crash dump provided, if issue has persisted come to our discord for support.
