### ISSUE TITLE
craft syntax error

### ISSUE THREAD

**Issue by vpmarche** [Windower/Issues#1005]
I got a craft syntax error after my game crashed. lua syntax error: craft/craft .lua 103: 1=1 expected near 1:1 or something like that cant read my writing.

**Comment by joshk6656** [comment]
What were you inputting

**Comment by vpmarche** [comment]
//craft support got that message when I hit input and It didn't do anyhing

**Comment by joshk6656** [comment]
Are you near a craft support npc? If so which one?

**Comment by vpmarche** [comment]
Yeah goldsmithing one but no craft commands work atm

**Comment by vpmarche** [comment]
Verify the text is this: craft: syntax error: craft/craft.lua:103: '='
expected near ':'

**Comment by vpmarche** [comment]
lua syntax error: craft/craft.lua103: '=' expected near ':'  and it keeps telling me that craft doesn't exist when I try to reload it, and I deleted the folder and reloaded craft and same thing. this is 102 +
local exceptions = {
['Geo Crystal'] = 6509,
['Fire Card'] : 9764,
['Ice Card'] : 9765,
['Wind Card'] : 9766,
['Earth Card'] : 9767,
['Water Card'] : 9769,
['Light Card']: 9770,
['Dark Card']: 9771,
}

local clusters = {
['Fire Crystal'] = 'Fire Cluster',
['Ice Crystal'] = 'Ice Cluster',
['Wind Crystal'] = 'Wind Cluster',
['Earth Crystal'] = 'Earth Cluster',
['Lightng. Crystal'] = 'Lightning Cluster',
['Water Crystal'] = 'Water Cluster',
['Light Crystal'] = 'Light Cluster',
['Dark Crystal'] = 'Dark Cluster',
}

**Comment by z16** [comment]
Thanks for pointing that out, this should be fixed. Can you try again? Should be able to just rerun `Windower.exe`, don't need to log out. Then just `//load craft` in-game.

**Comment by vpmarche** [comment]
I'm slow how do u reload windower?

**Comment by vpmarche** [comment]
Same error reloading craft

**Comment by vpmarche** [comment]
it was working fine all morning then I slept during the day woke up and game crashed and that wasn't working, also there seemed to be an update of sorts for windower.

**Comment by vpmarche** [comment]
Oh yeah I did add 2 new add-ons maybe that's why trust and another I can't
remember

**Comment by vpmarche** [comment]
Might have added those after prob

**Comment by z16** [comment]
Sorry, I forgot to actually merge the code <_< Try again now...

**Comment by vpmarche** [comment]
Thanks man fixed

**Comment by Snapster-amb** [comment]
whoops!  my bad.  glad it got resolved

**Comment by vpmarche** [comment]
Ty
