### ISSUE TITLE
SetKey weirdness on Dev

### ISSUE THREAD

**Issue by ghost** [Windower/Issues#1007]
If I manually follow an npc/player and type 

> //setkey numpad 7 down

It works -- follow is cancelled.

however if I execute it any way other than a console or the ffxi chatlog, such as via a script it does not work.

contents of my "stopfollow.txt":

> echo test
> setkey numpad7 down
> setkey numpad7 up

following something then //exec stopfollow.txt does print "test", but it doesn't stop following like the manual typing.

This used to work on Live.

**Comment by cairthenn** [comment]
Try adding a small wait between setkey for the time being.

**Comment by ghost** [comment]
> echo test
> setkey numpad7 down
> sleep 5.0
> setkey numpad7 up

also does not work. It seems that for whatever reason if it's not issued via the console or ffxi chat log "setkey" doesn't function -- of course this is just from what little information I can see. I do remember in the past that using setkey from somewhere other the console or chatlog doesn't print the "Setting key code ${keycode} to state: (up|down)" message. Perhaps this is related?

**Comment by cairthenn** [comment]
"sleep" won't do anything. Use "wait"

**Comment by ghost** [comment]
Welp, that works. even a small "wait 0.1". Oops.
