### ISSUE TITLE
Firaga and other AoE magics crash me in large groups

### ISSUE THREAD

**Issue by androwe** [Windower/Issues#1010]
Description of issue: When I use borderless window, i usually crash when mobs use large aoe moves or magical aoes, particularly firaga and thundaga, on larger alliances.  This normally happens in dyna d, omen, vagary, and reisenjima.  i can avoid the issue by completely turning off effects from mobs or launching in fullscreen mode.  I'd like to be able to dualbox and still see the visual effects from moves.

Operating system: Windows 10

Windower version: Windower 4.  4.3.6632.29121

Windower plugins/addons/other:  below

Windower settings: 
?xml version="1.0" encoding="utf-8"?
<settings
  <autoload
    <addon>aecho</addon>
    <addon>chars</addon>
    <addon>scoreboard</addon>
    <addon>TParty</addon>
    <addon>Clock</addon>
    <addon>autocontrol</addon>
    <addon>DistancePlus</addon>
    <addon>Pouches</addon>
    <addon>SpeedChecker</addon>
    <addon>TreasurePool</addon>
    <addon>capetrader</addon>
    <addon>PetTP</addon>
    <addon>thtracker</addon>
    <addon>targetinfo</addon>
    <addon>timestamp</addon>
    <addon>autoinvite</addon>
    <plugin>Timers</plugin>
    <plugin>FFXIDB</plugin>
    <plugin>InfoBar</plugin>
  </autoload>
  <profile name="">
    <consolekey>Insert</consolekey>
    <uiscale>1</uiscale>
  </profile
  <profile name="Andrew"
    <region>US</region
    <consolekey>Insert</consolekey
    <mipmaplevel>3</mipmaplevel
    <uiscale>2.7</uiscale
    <supersampling>2</supersampling
    <bumpmapping>true</bumpmapping
    <logs>9</logs
  </profile>
  
</settings>

Details of how the issue happened: I crash any time a BLM mob uses firaga in dyna D.  That is what will make it happen the most frequently.  I've been going fullscreen to important events for the last couple months but anytime i forget to relog into fullscreen, it will generally be firaga that crashes me.

I doubt it matters, but im playing on a PC and i use a 4k for my monitor.

Crash Dump: 
[pol.exe.11520.zip](https://github.com/Windower/Issues/files/2196344/pol.exe.11520.zip)

Microsoft (R) Windows Debugger Version 10.0.17134.12 X86
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [C:\Program Files (x86)\Windower4\dumps\pol.exe.11520.dmp]
User Mini Dump File: Only registers, stack and portions of memory are available

Symbol search path is: srv*
Executable search path is: 
Windows 10 Version 17134 MP (8 procs) Free x86 compatible
Product: WinNt, suite: SingleUserTS Personal
17134.1.x86fre.rs4_release.180410-1804
Machine Name:
Debug session time: Sun Jul 15 16:54:46.000 2018 (UTC - 4:00)
System Uptime: not available
Process Uptime: 0 days 3:00:24.000
................................................................
...................................................
Loading unloaded module list
...............
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(2d00.2d8c): Access violation - code c0000005 (first/second chance not available)
eax=00000000 ebx=00000000 ecx=271bcf8d edx=00000000 esi=00000003 edi=00000003
eip=779aa7bc esp=0019e180 ebp=0019e310 iopl=0         nv up ei pl nz ac po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000212
ntdll!NtWaitForMultipleObjects+0xc:
779aa7bc c21400          ret     14h

**Comment by cairthenn** [comment]
This doesn't seem to be Windower related (though I'm not ruling out the possibility entirely). It's likely one of the many things that simply breaks on Win10 with FFXI.

**Comment by androwe** [comment]
Are you going to look into this anymore and if so do you need anymore crash logs or info.  Thank you

**Comment by cairthenn** [comment]
I can't look too much more into it, it's crashing in FFXI code, not Windower code. Your better bet is to post on XI official forums that their game doesn't run properly on Windows 10 windowed mode. :(

**Comment by androwe** [comment]
Thank you very much for your time.  I appreciate it.
