### ISSUE TITLE
Windower error 123 nothing loads

### ISSUE THREAD

**Issue by sozoid** [Windower/Issues#1012]
turned on windower this morning after using last night with no problems, it seemed to auto update itself, now I turn it on and enter ffxi and error message "could not execute (directorypath)Windower4scriptsautoloadautoload.txt - unknown error 123"

clearly douchebags who have the ability to edit/force updates fucked with something that screwed it up, and there is no information on this shitty website about how to fix anything, just a bunch of elitist epeen cunts talking about scripting. wtf did you guys do to the program? it's worked fine for years, I just deleted and redownloaded and reset all my fucking scripts and it still does not work, getting same issue, what in the actual fuck.

**Comment by z16** [comment]
Fixed, update will be pushed shortly. Thank you very much for calm and level headed analysis of the issue. It was a tremendous help.

**Comment by sozoid** [comment]
thanks dick, stop fucking with shit

**Comment by z16** [comment]
No chance, this is way too much fun 👍

**Comment by sozoid** [comment]
leave it to beaker
