### ISSUE TITLE
Apparently this guy crashes with the GilTracker addon and some other addon whose name they don't seem to know

### ISSUE THREAD

**Issue by vpmarche** [Windower/Issues#1013]
havent crashed since i turned off the addon that shows your gil, and the addon that lets you chat after a zone. so one of them is the culprit.

**Comment by z16** [comment]
A better title would be "Crashing with the GilTracker addon". Either way, we would need a [crash dump](https://github.com/Windower/Issues/wiki/Enabling-automatic-crash-dumps) to diagnose this.

**Comment by vpmarche** [comment]
How do u do a crash dump?

**Comment by vpmarche** [comment]
Oh I see link on pc sorry

**Comment by vpmarche** [comment]
So I should prob enable one or both of those programs and let the crashdump do its thing ?

**Comment by z16** [comment]
Yes, exactly. When you crash the next time you'll have a crash dump in the `dumps` folder.

**Comment by vpmarche** [comment]
im sorry, I haven't had a crash in 2-3 weeks now. something musta fixed itself.
