### ISSUE TITLE
Windower only shows "Preparing to Install..." Screen

### ISSUE THREAD

**Issue by jdaugh85** [Windower/Issues#1014]
I recently tried to open the ERA server in Windower, following the directions posted on the server's page. When I get to the section of configuring Windower, I can configure the settings folder, but when I re-launch Windower and try to connect to the server, all I am getting is a pop-up that says "Preparing to Install..." I have left it on this screen, just to make sure that it would not progress further, but it does not progress.

In a separate window, it shows me as logged in to the Dark Star servers, just not progressing beyond this screen.

**Comment by alphaONE2** [comment]
This isn't a Windower issue. What you're seeing is the Windows Feature on Demand window.

Starting with Windows 8, DirectPlay is no longer installed by default. Instead the operating system detects when a process attempts to load this component and installs it on demand. The window you're seeing is Windows attempting to do that. You can avoid this by installing it manually. Search for "Turn Windows features on or off" in the <kbd>Start</kbd> menu and then enable "DirectPlay" under the "Legacy Components" section.

**Comment by jdaugh85** [comment]
Sorry I forgot to mention in the original post.. Direct Play is currently enabled and I have attempted to run in Administrator Mode as well on Windows 10 with the same result each time.

**Comment by alphaONE2** [comment]
I'm not sure what to tell you. Windower doesn't have a "Preparing to install..." pop up. Verify that it doesn't happen with Vanilla FFXI on retail servers, do a file check, and make sure that your anti-virus software isn't deleting or quarrentining FFXI files (this has happened multiple times in the past, with or without Windower)
