### ISSUE TITLE
Timers - New COR Gear not supported

### ISSUE THREAD

**Issue by Chiaia** [Windower/Issues#1015]
The following phantom roll duration gear(id) doesn't seem to be supported.
Regal Necklace - 26038
Lanun Tricorne +2 - 23079
Lanun Tricorne +3 - 23414 (Didn't actually test this one but assuming since +2 came out at the same time.)

**Comment by zetaepyon** [comment]
I think I already fixed these in a dev branch, maybe it never got rolled out....

**Comment by Chiaia** [comment]
Just fixed this.
