### ISSUE TITLE
auction house crash

### ISSUE THREAD

**Issue by vpmarche** [Windower/Issues#1018]
I have a random crash a lot of the time , actually almost all the time at the auction house.
[crash.log](https://github.com/Windower/Issues/files/2279003/crash.log)

**Comment by z16** [comment]
This crash log is from a different crash. Follow the instructions [https://github.com/Windower/Issues/wiki/Enabling-automatic-crash-dumps](here) to get a proper crash dump.

**Comment by Nifim** [comment]
Come to our discord for support if the issue has persisted.
