### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by AlgarDude** [Windower/Issues#1019]
I am unsure of what is causing them. I've tried disabling nearly every addon, but there is nothing I can reproduce. Here are the latest two crash-dumps. Thank you!

[dumps.zip](https://github.com/Windower/Issues/files/2368790/dumps.zip)

**Comment by AlgarDude** [comment]
As a followup, the crashes appear to occur whenever I hit the enter button too quickly, such as when breezing through menus for entering BC's. I can sometimes reproduce them. Attached is another dump from this.
[pol.exe.15028.dmp.zip](https://github.com/Windower/Issues/files/2381203/pol.exe.15028.dmp.zip)
.

**Comment by Nifim** [comment]
If issue still persists come to our discord for assistance.
