### ISSUE TITLE
I am getting a 'nil value' error from this function, what is missing?

### ISSUE THREAD

**Issue by GenTeal** [Windower/Issues#1020]
function Can_Cast_Spell(spell)
	local result = false
	local myspell = res.spells:with('name',spell)
	Recasts = windower.ffxi.get_spell_recasts()
	if (Recasts[myspell.id] == 0) and (not isCasting) and (windower.ffxi.get_player().vitals.mp >= myspell.mp_cost) and (isBusy == 0) then
		result = true
	end
	return result
end

**Comment by cairthenn** [comment]
This is not an 'issue'. If you have an error, you will also have a line number and error type information with which to debug your code. If this code is your own, you can look for help either online or in our discord http://discord.gg/b275nMv. If the code is not your own, you should still have the aforementioned line information as well as what addon this happens in and what makes the error occur which you submit as an issue for that addon.
