### ISSUE TITLE
having a hard time getting the back piece to change 

### ISSUE THREAD

**Issue by vpmarche** [Windower/Issues#1022]
I put -- next to the back piece I don't want to use and it still keeps changing to that one. I don't know how to disable or test that out, so I left it alone.

**Comment by cairthenn** [comment]
-- means you want to comment out a line in Lua. If you don't want a back equipped in your GearSwap, don't specify a back to equip. Additionally, this is not an "issue". You can seek basic help on our discord.

**Comment by vpmarche** [comment]
Oh ty. Didnt think about erasing it but what if i wanna switch tto cp
mantle for cp. Just put it in manually?

**Comment by GenTeal** [comment]
you could disable the back slot and put the mantle on for cp.
