### ISSUE TITLE
Scoreboard Aeonic Skillchains not calculated

### ISSUE THREAD

**Issue by Dridian** [Windower/Issues#1030]
I've been looking over the code and the scoreboard.lua in lines 446-450 have the reference numbers to the different types of Skillchains. While this is great, I've been looking over the file and making my own adjustments to see the WS and MB damages. I've been successful at incorporating MB damage to the chatlog while you've already have it running on total damage.

My main issue is the Reference Numbers 767,768,769,770 for Skillchain messages in the res.action_messages isn't being captured. All the other Ref # are doing great but when trying to read Umbra and Radiance nothing seems to be happening. I've reset the program to see if it was just me and I'll unload and reloaded Scoreboard to see if its capturing the damage and it fails to add in the damage done.

I could be wrong, but so far everything I've tried works under the conditions given.

**Comment by Chiaia** [comment]
I fixed this a few minutes ago by updating the actions library to include the newer SCes that scoreboard relies on.
