### ISSUE TITLE
windower.ffxi.get_ability_recasts() return nil 

### ISSUE THREAD

**Issue by shadow9555** [Windower/Issues#1039]
i have a lua that uses windower.ffxi.get_ability_recasts() and until today it always return a table but now it is returning Nil, but it does work in gearswap just not in other luas i use

**Comment by shadow9555** [comment]
this problem just got stranger, on one of my lua windower.ffxi.get_ability_recasts() is returning a table, but on my other one its returning nil. and this lua was been working until yesterday and show its last edit before December. I can image what has changed where it can work in a one lua but not the other.

**Comment by joshk6656** [comment]
Paste examples of how you are using it please.

Or use gist.github.com

**Comment by shadow9555** [comment]
The problem was between the keyboard and the chair.
I was unaware if the ability id use is not available to the job that the id would not be in the table.
The error message led me to believe that the table was nil but it was the index i was looking up because the job did not have that particular ability.
