### ISSUE TITLE
InfoBar and Aldouin Enemies

### ISSUE THREAD

**Issue by coldReactive** [Windower/Issues#1040]
Continuation of this: https://github.com/Windower/Issues/issues/1035

Enemies such as the "Pinetorum" do not have proper levels (or even ???) nor aggro types/etc.

This is mainly for tracking purposes. I'm not really up to doing it again. But the linked issue above will provide information for others to add the enemies to the database. Once someone has, please use this issue to upload the database and show that you have tested it properly.

**Comment by andrewbabbittdev** [comment]
Why go through so much effort to do all of this?

Darkstar has a decent sized team working on this kind of stuff, they have SQL scripts for MySQL with all the info pulled from the retail game. It wouldn't be hard to create a small tool to pull from a Darkstar DB/regex the scripts to pull the relevant info into the SQLite DB.

Could look into doing this if there is interest.

**Comment by coldReactive** [comment]
I'm currently working on this right now, since I haven't seen anyone update the database with them. I noticed when adding entries that there were false entries added in the first two non-waterways Aldouin Zones, and removed them as I go along. The update also adds a couple Orcish Grunt entries that have been bothering me. Example of what I'm on right now:

![image](https://user-images.githubusercontent.com/1313673/223604113-a7ad7642-a2fc-41af-95aa-30fed9bc9710.png)

I've completed the aggro/levels of Yahse, Ceizak and Rala Waterways (Non-U versions.) Another 10 areas left to fill out once I'm done with Morimar Basalt Fields.

**Comment by coldReactive** [comment]
@joshk6656 @z16 I've updated this database with almost all of the Aldouin Enemies. There are some Rieve enemies I forgot to put in. But, to be fair, they will almost always be aggressive.

[database.zip](https://github.com/Windower/Issues/files/10922871/database.zip)

Example of a below Aldouin enemy being targeted, with the InfoBar in the upper left:

![InfoBarTest1](https://user-images.githubusercontent.com/1313673/223776014-02ff06b0-44bb-4880-bb41-4e4e7ae43e44.jpg)

I've also taken the liberty of filling out any and all weaknesses/strengths to elements/etc. that I could find on the enemies. But don't be alarmed if there are a bunch I didn't put in. There is a lot of lacking information on wikis, ffxiah, ffxidb, etc. Plus I mainly only did aggressive/detects on Ceizak, Yahse and Rala Waterways.

**Comment by coldReactive** [comment]
Pull Request made: https://github.com/Windower/Lua/pull/2281

**Comment by coldReactive** [comment]
I won't be ever subscribing to FFXI or installing it again. So this pull will never be confirmed/tested by me again.

Closing, since the windower team doesn't plan to do anything with it, even a year after I made the actual effort into doing what they asked in my previous issue with all the escha enemies, but this time with adoulin enemies.
