### ISSUE TITLE
having a error flood on screen

### ISSUE THREAD

**Issue by vpmarche** [Windower/Issues#1041]
went into escha zitah and got this error flooding on my screen: gearswap lua runtime error: gearswap/equip_processing.lua: 246. attempt  to index field '?' (a nil value).  

what does this mean and how do I turn it off? I have recently removed a smn lua and I am on smn maybe that might be it but idk.

**Comment by vpmarche** [comment]
ok it quit doing it, I don't know why that happened.

**Comment by vpmarche** [comment]
i didn't even have a lua on.

**Comment by z16** [comment]
All's well that ends well!
