### ISSUE TITLE
ERROR luacore - failed to load plug in - (126) module not found

### ISSUE THREAD

**Issue by chrisellis111** [Windower/Issues#1047]
worked fine last night 
re downloaded 2x "dev"
tried stable version, disabled firewall

**Comment by z16** [comment]
Is the `LuaCore.dll` inside the `Windower/plugins/` folder?

**Comment by chrisellis111** [comment]
![image](https://user-images.githubusercontent.com/17678182/67150453-68ca7800-f26c-11e9-8d94-8e645ed15a3d.png)

**Comment by chrisellis111** [comment]
changed the APP resolution settings now seems to be working fine
