### ISSUE TITLE
Windower 4 Not installing properly

### ISSUE THREAD

**Issue by Dalmahr** [Windower/Issues#1049]
I tried on 2 different computers. It will install and launch and let me change settings however if I close it and try to find it, it's no where to be found. If I go to install it again it just launches. I found that the files were being extracted into the temp folder (I chose run instead of save while downloading) so I copied those files to the program files folder and made a shortcut from the exe from there and that seems to do the job. I woud have thought it was maybe something with my computer at first but since it happened on 2 different computers, both running Windows 10 1903, I thought I should pass this a long.

**Comment by RubenatorX** [comment]
Windower4 no longer has an installer, it just creates the files it needs to run in the folder where you run it.

**Comment by Dalmahr** [comment]
Thanks for the quick response. Makes sense. I didn't see any sort of instruction about that from the install website. Good to keep in mind though.
