### ISSUE TITLE
Black Screen on CS in Ro'maeve for Shantoto Ascencion

### ISSUE THREAD

**Issue by kaincenteno** [Windower/Issues#1051]
CS 71 in Ro'Maeve leads to black screen after opening door.

This issue only happens on windower, if running using xiloader from command prompt this issue doesn't happen.

**Comment by RubenatorX** [comment]
For clarity, this is mission 8, and it is documented on bgwiki
 https://www.bg-wiki.com/bg/A_Shantotto_Ascension_Mission_8

**Comment by Nifim** [comment]
Also closing as this is a duplicate of https://github.com/Windower/Issues/issues/399
