### ISSUE TITLE
Memory leak seems to be causing crashes

### ISSUE THREAD

**Issue by Flareburst** [Windower/Issues#1052]
Hello,

I'm using gearswap with the attached WAR.lua file. The POL service seems to be steadily increasing its memory consumption until windower just crashes.

I'm not sure where the problem is. All threads seem to be closing in the lua file.

Please help!

Dump file:
https://www.dropbox.com/s/d3b80j2u94bibdl/pol.exe.14316.dmp?dl=0

Lua:
[WAR.txt](https://github.com/Windower/Issues/files/3950222/WAR.txt)

**Comment by RubenatorX** [comment]
Have you done:
//console_log 1
//lua memory
to determine how much memory gearswap is actually using and if its increasing over time?
How much memory are you noticing POL using?

**Comment by Flareburst** [comment]
Hi RubenatorX,

I did look at the memory consumption from all luas and they were stable at 30MB/20MB for Gearswap/Treasury.

The POL process started at about 300MB and went all the way up to 500MB.

I installed dgvoodoo and reshade and there hasn't been any crash for a good 12 hours now. 

Could it be due to graphics?

Thanks,

**Comment by RubenatorX** [comment]
If its only hitting 500MB, unless your system has pitiful amounts of total ram that is not likely the issue.
It definitely could be graphics related. If you are not using a graphics visualizer (like DGVoodoo) or if you haven't turned down the UAC (user account control) setting to "(do not dim the desktop)" then if you run a program that causes the administrative "Are you sure you want to run this?" yes/no popup to appear, then the act of dimming the screen causes the game to crash. (Locking the computer can also cause this).
If you'd like to talk about it more feel free to come chat about it on the official Windower discord: https://discord.gg/v6pk6uy (you can also find this link at the top of http://windower.net)

**Comment by Nifim** [comment]
User was directed to discord for further assistance.
