### ISSUE TITLE
POL is not launching at all!

### ISSUE THREAD

**Issue by andreapapazzoni** [Windower/Issues#1054]
Hello there!
I’ve been using windower since years, and this is the first time that this happens.
I was using windower with no problem until yesterday, then I installed the mega pack overhaul from Amelia to make FFXI looks better, followed all the instructions, installed reshade for D9 ( after I tried D10/11/12) and finished the installations.
If I boot FFXI from original POL I have no problem playing, but if I launch windower, I get stuck in “launching PlayOnline viewer” and then it closes and nothing happens.
I searched the web, in on win 10, I have all authorizations, no antivirus, everything is fine, no updates from Microsoft, nothing on nothing.
What could it be?
P.s. I tried installing ashita and I got the same problem, the programs stops before launching POL.
Please, HELP!
:)

**Comment by RubenatorX** [comment]
Do you or have you ever played on Nasomi on your current windows install? (I ask because people who have modified their client with Nasomi in the past sometimes have an issue like this).

**Comment by andreapapazzoni** [comment]
Nope, never, always retail.

**Comment by andreapapazzoni** [comment]
It seems ( from what I heard ) a registry problem.
I don’t know anything about registry tho, so I’m stuck and I don’t know what to do at all.

**Comment by RubenatorX** [comment]
A registry problem can do that but, if you didn't mess with the registry then that may not be the problem.
You can always do a POL file check to have it fix all the dats you modded and then you can move on and play without the mod.
If you want to chat about it more or want me to walk you through the steps to check your registry you can come have a conversation in discord (link at the top of windower.net) or wait for someone else to maybe have a bright idea but... if the dat mods breaks Windower's ability to launch the game then, you may need to find some support from Amelila or not use the mod.

**Comment by andreapapazzoni** [comment]
I’ll come in discord after work :)
Already did a file check with pol, BTW

**Comment by RubenatorX** [comment]
If you did a file check then either the dats unrelated to the problem or you may have to do a fresh reinstall of FFXI/POL (the new installer is pretty fast I hear)

**Comment by andreapapazzoni** [comment]
I did find the solution!
When I installed the mega pack HD, I had ( from the instructions) to put this file D3D8.DLL in my Playonline folder.
Simply remove this file from there and everything will work!
:)
