### ISSUE TITLE
Windower resolution issue

### ISSUE THREAD

**Issue by Keishito** [Windower/Issues#1055]
I installed windower4 To play ffxi, but the resolution seeems not to match.  When I play without windower it looks perfect at 1920x1080  and 8/11 UI.  But since now I should adjust it inside windower instead, I do the same and it’s somehow unbalanced and also the mouse is bugged/unaligned (buttons should be clicked like one inch left from where they are).
Is there a way to use the PlayOnline configuration resolution instead, like I was playing before but activate the plugins? I only downloaded 4 plugins (timers, keybind, IME, no delay for macros) but haven’t activated them yet since I wanted to fix the issue with the resolution first.

**Comment by RubenatorX** [comment]
The "config" plugin is designed to correct the aspect ratio to how its meant to be, You may want to try it out.
What UI scale setting are you using?
Are you using the Borderless Window option?

**Comment by Keishito** [comment]
I will try the “config” plugin.  I tried different UI settings, the ones that get closer but no quite yet are 1.5x and 1.6x inside windower.  I am using full screen.  The mouse is definitely unusable if I set it more than 1.0x.  But at 1.0x I cant read anything. The standard ffxi configuration work flawlessly with all UI settings, it is when I change the UI in windower that things get weird.

**Comment by Keishito** [comment]
I realized that there's an issue with the fullscreen mode (macros get shrinked because the game thinks the screen is 30%-40% smaller horizontally and vertically, so the mouse can't go farther).  But I tried the borderless window and it seems like it's fixed, the mouse is no longer inaccurate and macros are the right size again.
I can't 100% find the right spot where I had the UI but I guess I'll deal with it.  On the FFXI configuration I had it on 7/10 the UI.  And when I put it on 1.5x inside windower it leaves a space at the bottom and the icons a tiny bit smaller.  But when I use 1.6x it goes behind my name at the bottom right, so I guess I have to decide between the two.
I downloaded the "Config" plugin but didn't notice any difference.  I did notice that it changes some settings inside the game though.

Where can I find a tutorial for key binding? I would like to make spells or abilities able to be casted with a key I choose, like the windows key plus a number for instance, or the ~ key.  Do I need to create a file or do it from inside the game with console commands? and how?.  I don't know how to resize or reposition the timers on the screen or if that is even possible.
I'm pretty lost about it.  Thank you so much for your reply.

**Comment by RubenatorX** [comment]
Copying this over from discord for documentation that the question was responded to:

> There is an in game command that binds keys to commands, but they do not persist through shutdown, so, if you want them to be around all the time, they need to be put into a script (probably init), so they will bind every time you run the game or whatever
> https://docs.windower.net/commands/input/#bind--keyboard_bind

If you have any more questions about it feel free to chat with us on discord

**Comment by Nifim** [comment]
Support issue that is better handled in discord.
