### ISSUE TITLE
Windower.exe crashes after disconnecting second monitor

### ISSUE THREAD

**Issue by tim-chaplin** [Windower/Issues#1058]
When I set Windower up, I had a second monitor connected to my laptop. Now I'm trying to run it without the second monitor plugged in and it just crashes immediately after showing the splash screen. If I reconnect the monitor it works again.

Here's what's in crash.log:

`````````````````````````````````````````````````````````````````````
[ 4.3.6774.38955 ] 2020-03-16 00:13:07.9850434 UTC
---------------------------------------------------------------------
System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
   at Launcher.Display.GetCurrentDisplayMode()
   at Launcher.Core.SendInitializationReport()
   at Launcher.Core..ctor()
   at Launcher.LauncherApplication..ctor(SplashScreen splashinit, LauncherOptions options)
   at Launcher.Bootstrap.Main(String[] args)
`````````````````````````````````````````````````````````````````````

**Comment by RubenatorX** [comment]
Make sure your windower game resolution setting matches that of your "main" display (which may be a different value between your monitor and your laptop)

**Comment by RubenatorX** [comment]
Also make sure your laptop display resolution matches the resolution that the screen actually is

**Comment by tim-chaplin** [comment]
How can I view or change the windower game resolution setting without being able to run Windower?

**Comment by RubenatorX** [comment]
It wasn't clear which splash screen you were referring to (windower or POL)
Have you tried something like this?:
https://github.com/Windower/Issues/issues/1002#issuecomment-520068181

**Comment by tim-chaplin** [comment]
Sorry it took me forever to respond to this. I had found that comment thread, but the options it was talking about weren't available in my nvidia control panel. However, I was able to finally fix this by messing around with options in my *intel* control panel. Right click on desktop -> graphics options -> panel fit -> maintain aspect ratio. I don't remember which setting was selected before.

**Comment by Nifim** [comment]
User fixed the issue through intel control panel
