### ISSUE TITLE
Inventory don’t load completely 

### ISSUE THREAD

**Issue by Robertdbz** [Windower/Issues#1064]
Since the last update from today September 18th
2020 my Inventory don’t load all stuff.

I’m @ 69/80 but it’s shown 59/80, if I buy stuff I can only get 11 stacks. So it’s just visual.

Other Problem is Mog Wardrobe don’t load all stuff too and with my macros I can’t equip the not shown/loaded stuff.

Please fix this.

w/o Windower FFXI is loading all stuff.

**Comment by RubenatorX** [comment]
Does the problem persist if you unload all addons and plugins and then zone?
`//unloadall` -- unloads plugins
`//lua unloadall` -- unloads addons
if the problem goes away, then you'll have to turn stuff back on slowly and figure out which addon or plugin is causing the issue.

**Comment by Robertdbz** [comment]
Just tried //unloadall and all stuff is now shown after zoning.

So time to figure out which Addon/Plugin is bugged

**Comment by Nifim** [comment]
Also, are you on retail or a private server?

**Comment by Robertdbz** [comment]
I’m on Quez not private

**Comment by RubenatorX** [comment]
Are you using dressup?

**Comment by Robertdbz** [comment]
Yes dressup is loaded

**Comment by Robertdbz** [comment]
I zoned now about 20 times with Tele, Warp and so on and inventory did always load completely w/o having dressup loaded

I hope that was it, thx

I will see tomorrow once I login 👍

**Comment by Robertdbz** [comment]
Seems to be fixed with the LUA update from today 
Now also with dressup loaded 👍
