### ISSUE TITLE
Game CRASHES when expanding chat window

### ISSUE THREAD

**Issue by joeip1217** [Windower/Issues#1066]
Instant Crash when I open my chat log. This is strange because I did not have this issue until today. I logged into FFXI today and windower updated when I logged in just like it always does. Now I crash when I open my chat log and it has to be related to something that was changed to windower/addon/plugin.
Please help. Thx

**Comment by Nifim** [comment]
This PR resolves the issue but is not yet merge to live. https://github.com/Windower/Lua/pull/1949

**Comment by Nifim** [comment]
Additionally issues maybe caused by XIView if you are using it and have not updated since Oct 12th 6:41 AM PDT

Conversation on Discord Support Channel:
    https://discord.com/channels/338590234235371531/338713865812574219/765345969649877003

**Comment by RubenatorX** [comment]
The crash from opening the chat log is not a windower bug and is due to using outdated dat mods as described by Nifim
