### ISSUE TITLE
Windower crashes and late Windower program load times in game

### ISSUE THREAD

**Issue by Lehmie** [Windower/Issues#1072]
I can log in the first character normally, as soon as it is online, no windower programs load and no init script. In addition, as long as the init script is not loaded, I can't log in any other characters, but the windower exe closes immediately on the second character. This is repeated at the second/third Char.... after that the game crashes very often. Hope you can give me some tips.

**Comment by RubenatorX** [comment]
Likely one of your windower files is corrupted. Maybe `windower\plugins\LuaCore.dll`. With everything closed, try renaming it to `LuaCoreOld.dll` and then deleting the folder `windower\updates` and restarting the launcher (note: doing this forces an update of everything, especially missing files).
May be easier to help you if you chat with us in discord #support (link can be found at the top of windower.net). But that's the first thing I'd have you try.

**Comment by Nifim** [comment]
Link to support channel: https://discord.gg/aUrHCvk

**Comment by Lehmie** [comment]
Very nice. I try it and now seems all good ;)   I Joined Discord for next problems. Many many Thanks
