### ISSUE TITLE
Consistent Crashes whenever another program attemps UAC authorization (Windows 10)

### ISSUE THREAD

**Issue by 0xv1n** [Windower/Issues#1073]
I can consistently replicate a crash where any app that attempts to run as Administrator (and requests UAC confirmation) will cause Windower to crash to desktop with no error and without any type of dump to the crash log file.

**Comment by z16** [comment]
This cannot be fixed on our end. You need to lower the UAC setting to not dim your desktop.

**Comment by RubenatorX** [comment]
This is NOT a windower bug. The vanilla game does that.
