### ISSUE TITLE
Windower4 is crashing immediately upon opening

### ISSUE THREAD

**Issue by KanaChikage** [Windower/Issues#1078]
I've been using windower for a good while recently built a new pc and now all of a sudden windower just refuses to open, and im 100% unsure of how to fix it. I do have the crash log and will attach it. Any help would be greatly appreciated, and thank you in advance.
![WIndower4 crash log](https://user-images.githubusercontent.com/85921639/121998154-76097400-cd79-11eb-9a2a-362f0e63542f.png)

**Comment by Nifim** [comment]
Please come to our discord, it is better suited for this type of support. https://discord.gg/aUrHCvk

A few things to include in your post there are, 
    does the game work in vanilla?
    Are you using an day mods?
    Are you playing retail or private server?
    What is the path to your windower.exe?

**Comment by KanaChikage** [comment]
I only play retail, i dont agree with the idea of private servers, the game does work in vanilla, i havent installed any mods and windower.exe is in program files(x86) atm

**Comment by Nifim** [comment]
Was directed to continue discussion on discord.
