### ISSUE TITLE
Itemizer Error

### ISSUE THREAD

**Issue by wuqinpu** [Windower/Issues#1080]
stopped working
case currently not enabled

**Comment by RubenatorX** [comment]
This bug should be fixed tonight. It also affects more than itemizer. Any addon that checks if a bag is `enabled` is affected by today's patch.

**Comment by wuqinpu** [comment]
thanks very much!

RubenatorX ***@***.***> 于2021年10月12日周二 上午9:31写道：

**Comment by Chiaia** [comment]
https://github.com/Windower/Windower4/commit/13db4761cc0642880c4627ce1b1aad8c1688610e

**Comment by wuqinpu** [comment]
Thanks a lot.

Chiaia ***@***.***> 于2021年10月13日周三 下午10:48写道：
