### ISSUE TITLE
Alts won't stop /unfollow

### ISSUE THREAD

**Issue by Mindseven** [Windower/Issues#1082]
Hello 🤗
For some reason when I log onto to windower with 2 different accounts, they won't stop following each other. When I press any button on my controller the other does the same. I created two different profiles, and disabled send addon, and even uninstalled windower and reinstalled several times with the same thing happening. I'm trying to figure it out. Cheer's

**Comment by RubenatorX** [comment]
This is not a bug. This setting in the Windower Launcher determines if controllers will control game windows when they are out of focus or not.
![image](https://user-images.githubusercontent.com/5944121/144336612-8c08ff43-0234-4431-b8da-aa0d417d0daf.png)
ON means it will control game windows when they are in focus or not
 (the setting you are presumably using on at least one character)
and OFF means it will only control the game window that is in focus.
You presumably should change them to OFF

If you have more questions, you can come chat with us in the windower discord (link found at the top of windower.net)

**Comment by Mindseven** [comment]
😆. Sorry for my ignorance. So glad it was an easy fix! Most of all thank
you!
