### ISSUE TITLE
Findall / Itemizer / GearSwap errors related to new inventories

### ISSUE THREAD

**Issue by AlfyCodes** [Windower/Issues#1085]
Seems there is an issue when trying to call ipairs that is affecting both findall and itemizer. I grabbed the findall issue, was unable to recreate the Itemizer issue but it is similar.  

findAll/findAll.lua:418: bad argument #1 to 'ipairs' (table expected, got nil)

Probably because of the new storages.

**Comment by jasonc-87** [comment]
This issue is also happening with gearswap the equipment_processing file, line: 137

`for _,item_tab in ipairs(items[to_windower_bag_api(bag.en)]) do -- Iterate over the current bag`

**Comment by Byrth** [comment]
We need to push out a new Hook / LuaCore to expose the new storages. After that, these problems will be resolved.

**Comment by Byrth** [comment]
This is on the dev branch now if you want to try it.

**Comment by AlfyCodes** [comment]
I updated my lib folder, still having the same issue. findAll/findAll.lua:418 bad argument #1 to ipairs (table expected, got nil)

Perhaps I updated the wrong folder? I only saw libs was updated an hour ago. 

Edit: I went back and updated anything that was updated today (a.k.a x hours ago) Still having findall issues, as far as testing goes. Did not test anything else.

**Comment by Byrth** [comment]
I meant the Dev windower 4 version: https://update.windower.net/dev/windower-dev.msi

**Comment by AlfyCodes** [comment]
Downloaded the client.

The Test
===============
//findall "item"  [Pass]
//findall "Godhands"    (While stored in M. Ward 5, 6, 7, 8) [Pass all Cases]


---------------------------
No further testing done.

Great job!

**Comment by Byrth** [comment]
We are onto different issues now, then!
