### ISSUE TITLE
GearSwap

### ISSUE THREAD

**Issue by jasonc-87** [Windower/Issues#1086]
Similar to the Findall/Itemizer https://github.com/Windower/Issues/issues/1085

Lua runtime error: GearSwap/equipment_processing.lua:137: bad argument `#1` to 'ipairs' (table expected, got nil)

Line 137 in equipment_processing: `for _,item_tab in ipairs(items[to_windower_bag_api(bag.en)]) do -- Iterate over the current bag`

**Comment by Byrth** [comment]
Agreed, this is a duplicate
