### ISSUE TITLE
Windower Crashes

### ISSUE THREAD

**Issue by Benpal2476** [Windower/Issues#1088]
Windower crashes on accept screen for FFXI once addons are being loaded began happening around 8-9 EST. I was playing with previous version of  Windower I had 3 toons logged in. I needed to relog so I closed one Windower session to open another windower session. The new Windower update began to update. Once it completed and launched. I began loggining in, completed the login, click on shortcuts to login into the game and on the Accept screen once the addons began loading Windower crashed unexpectedly. I attempted this same process on a second computer, and the same happened. Logged out, opened Windower, a automatic download began running for Windower, logged on to POL clicked on shortcut, next screen Windower unexpectedly shut down.

**Comment by Byrth** [comment]
Could you try again, please? A new hook version went out that should fix your problem.

**Comment by Benpal2476** [comment]
Yes it is resolved thanks
