### ISSUE TITLE
Issue with fresh install

### ISSUE THREAD

**Issue by ClassicRoch** [Windower/Issues#1092]
I'm not sure if this is a bug with the newest version of Windower, or if it's a bug with the current installer, but I have been trying to fresh install windower all day with no success. It gives a white box on the Plugins menu and fails to load playonline. Crash reports just say timeout error. I was able to recover by deleting everything and copying the entire windower folder from a friend. Near as I can figure, the only noteable difference (besides addons and plugins) is the Hook.dll file, which was missing in all my installs, but present in the folder from my friend. No installation or run attempt produced or generated the Hook.dll file.
[crash.log](https://github.com/Windower/Issues/files/9602031/crash.log)

**Comment by Nifim** [comment]
You likely have Malwarebytes blocking the windower updates web page from being connected to. It is a pretty common issue for users of Malwarebytes or other antivirus software. Adding `update.windower.net` to the whitelist settings of the antivirus software should be enough to resolve the issue, If you need more assistance getting it working please come to our discord: https://discord.gg/aUrHCvk
