### ISSUE TITLE
Autoenterkey crash Win11 22H2

### ISSUE THREAD

**Issue by Jesyvut** [Windower/Issues#1093]
Upon service pack upgrade to Win11 22H2, Autoenterkey crashes game startup when POL goes to full screen.

**Comment by paulframe** [comment]
What evidence do you have that it is caused by autoenterkey?

**Comment by Jesyvut** [comment]
Watching the items load it would hit autoenterkey and crash.  Disabled and it would complete load.  Two PC's experienced this issue.

**Comment by zetaepyon** [comment]
Autoenterkey is an exceedingly simple addon - we'll need more info here...

Private server or retail? How are you loading autoenterkey?

**Comment by Jesyvut** [comment]
Retail; loading via the Windower 4 Add-on's selection.

**Comment by RubenatorX** [comment]
Does it crash if `autoenterkey` is the __only__ addon/plugin set to load?

**Comment by Jesyvut** [comment]
> Does it crash if `autoenterkey` is the **only** addon/plugin set to load?

No - upon testing, if autoenterkey is the **only** addon, it does not crash.  Sorry for wasting everyone's time without testing that.  Back to the drawing board.

**Comment by RubenatorX** [comment]
@Jesyvut
Well, it doesn't mean that autoenterkey is not involved.
Are you using any startup addon(s)/plugin(s)/command(s) that modify the game window? Such as WinControl and/or position_manager?
Are you multiboxing?
Are you using NextGames `scripts/init.txt`?

**Comment by Jesyvut** [comment]
Not using WinControl or Position Manager
I am multiboxing - but I load each instance separately, and it crashes on each.  I was able to get an instance loaded by disabling Autoenterkey and then the next instance I loaded with Autoenterkey enabled, and it loaded up.
I am using init to load SW, PorterPacker, React
