### ISSUE TITLE
Windower not launching POL 

### ISSUE THREAD

**Issue by Trajik327** [Windower/Issues#1095]
After shutting down ffxi last night and packing my laptop now I get no launch of ol from windower. The console file seems to be blank which im assuming the issue is do you have the text commands that should be present in that file to test my theory.

**Comment by Nifim** [comment]
Do you mean the console window for say xiloader? If so someone in our discord claimed this was due to windows terminal we could not replicate the problem but once the uninstalled windows terminal it work as normal

**Comment by Trajik327** [comment]
Im official servers didnt do anything to console file but when i checked it this morning it is blank. windower 4 launches but does not boot pol so im guessing this is the problem but not certain.

**Comment by Trajik327** [comment]
[console.log](https://github.com/Windower/Issues/files/10373784/console.log)

**Comment by Trajik327** [comment]
This is the crash log im getting

[crash.log](https://github.com/Windower/Issues/files/10373790/crash.log)

**Comment by Nifim** [comment]
Seems like a failure for windower to auto-identify the region. if the issue persists please come to our discord.
