### ISSUE TITLE
Timers 3.7.5.0 - Duration bonus from Blurred Harp +1 is not shown

### ISSUE THREAD

**Issue by radectheblm** [Windower/Issues#1096]
Naked, Ballad shows as 2:00 instead of true 2:48
Other songs show as 2:00 rather than the true 2:24

**Comment by RubenatorX** [comment]
@radectheblm -- naked? I thought we were supposed to be talking about Blurred Harp +1?

**Comment by zetaepyon** [comment]
I'm going to give them the benefit of the doubt and assume they meant naked except for the harp.

Neither Blurred Harp +1 nor the NQ version are present in the current buff checking code, so this appears to be a valid issue.

**Comment by radectheblm** [comment]
Correct, yes. Naked except for the harp, timers shows 2:00 instead of 2:48/2:24

**Comment by zetaepyon** [comment]
Should be corrected in Timers 3.7.5.1, please reopen if the issue persists after updating.
