### ISSUE TITLE
When trying to boot up FFXI through Lutris: "Unhandled exception: unimplemented function winegstreamer.dll.winegstreamer_create_video_decoder called in 32-bit code"

### ISSUE THREAD

**Issue by elijahbartolome** [Windower/Issues#1097]
I can't boot up FFXI, either through Windower or just booting up through FFXI directly. I get the same error in both cases: `Unhandled exception: unimplemented function winegstreamer.dll.winegstreamer_create_video_decoder called in 32-bit code`

I followed the directions [here](https://docs.windower.net/linux/) for installing FFXI and Windower, and also set Windower's Wine version to 4.21 as well.

Log:

[ffxi_log.txt](https://github.com/Windower/Issues/files/11228521/ffxi_log.txt)

**Comment by Nifim** [comment]
If you can not launch the game at all this in not a "windower" issue, be feel free to come to our discord for support we have a Linux channel
