### ISSUE TITLE
[Timers] - Can't change sort order of buffs high to low duration

### ISSUE THREAD

**Issue by rceglie** [Windower/Issues#1100]
Unable to change sort order of buffs by high to low duration. There is a field in the settings file BuffsLowToHigh but it doesn't seem to work when setting it to false. It only sorts the buffs from low to high, no matter what I change.

**Comment by RubenatorX** [comment]
You appear to be correct that it appears to be sorting low to high regardless of the setting -- but I want to point out that, I wouldn't necesarilly expect a `false` value to sort high to low, I'd only necesarilly it expect it to "not sort it low to high". Meaning that, at least with the verbiage, it could just be unsorted.

Out of curiosity though, in what situation (for what reason) would you want it sorted high to low anyway? 🤔

**Comment by rceglie** [comment]
To your first point - if the flag really were to just mean either sort it low to high (true) or do not sort it at all (false), this would seemingly contradict the other flag of "SortType". If SortType is set to Duration, why would you then be able to turn that off by selecting false for BuffsLowToHigh. Though I agree it very well may be implemented in that way, but it doesn't change the fact that it is not a good "feature," if you can even call it that.

To your second point, it is inherent to the concept of sorting itself that you should have to specify in which direction to sort. "Sort by time" has no meaning on its own - you must sort by time incrementing or decrementing, same with any other field you sort. If, by design, you can only sort in the default low to high direction, then this is instead a request for you to be able to sort in the other direction. As for my personal use, I just want the longer buffs to remain on top, while the shorter buffs appear at the bottom. I could ask anyone else why they would want it sorted in the opposite way (the current direction), and they would give the same response.

**Comment by RubenatorX** [comment]
> I just want the longer buffs to remain on top, while the shorter buffs appear at the bottom

That's not a reason, that's a sentiment. Like, what benefit does that give you? By sorting it the other way, the buffs that wear off next may not even be visible when they expire so, that's why I'm asking. For what reason do you want that feature at all?
If you don't have a reason and you are just reporting buggy behavior, that's fine, I'm just trying to understand why you desire that feature at all.

**Comment by rceglie** [comment]
> By sorting it the other way, the buffs that wear off next may not even be visible when they expire so, that's why I'm asking.

There is a different field which lets you set how many buffs you have showing up. By setting that to a large number, you can avoid that problem. At the end of the day, it _is_ a matter of preference. I prefer to have it high to low, while others prefer to have it low to high.

The "BuffsLowToHigh" field is bugged. The sorting behaves the same (sorted low to high) regardless of if it is true or false. I've just tested it again to confirm - it will always sort low to high, even if false. If this is some insurmountable technical challenge to fix, then I recommend removing the field entirely. If not, then "true" should sort low to high. and "false" should sort high to low. That is only logical.

**Comment by joshk6656** [comment]
Try creating another record in the settings file that is "BuffLowToHigh" and see if that works.

**Comment by LordTreyBennett** [comment]
Wouldnt it be more logical for false on sortlowtohigh be unsorted/first in first out type of deal? another sorthighttolow with a true value would seem needed if you want it to have both. Idk, I am one of those crazy people that turns off the graphics and just uses 8pt text name + recast time using minimal space, so my logical may be only logical to me.
