### ISSUE TITLE
Infobar with Windower 3.4 & 4

### ISSUE THREAD

**Issue by RKI027** [Windower/Issues#166]
Two issues with infobar:
1, horizontal position of the text seems a bit random across instances ( i use only the standard config). I don't care much, but for your info. I saw this mentioned in a forum by another user as well

2, in the default infobar config, there are lines configured to show airships/ferries schedule (notarget.2 and notarget.3). I bound shortcuts to rotate between the different lines configured. When I do rotate to the first of the airship schedule, infobar (only infobar, windower/ffxi keeps running well) crashes. This happens both with 3.4 and 4.

Rgds

**Comment by Nifim** [comment]
the InfoBar plugin has been deprecated
