### ISSUE TITLE
ChatMon: Allow Per-Character settings in CHatmon.xml

### ISSUE THREAD

**Issue by Brytor** [Windower/Issues#194]
Allow support for character specific settings for ChatMon in Chatmon.xml

Currently ChatMon supports only global settings and triggers which can override some global settings.   However, the triggers correctly can not cover all cases if you run multiple characters.

An example of this is the examine sound.  This event may be wanted on main character but not on mules that are for bazaar only.  Currently the trigger for examine matches to Examiners name and provides no way (or at least obvious to me) to match the character examined to filter out bazaar mules.

Allowing per-character settings and triggers would solve this and other similar cases.

**Comment by Nifim** [comment]
This plugin is depreciated, but the addon version does support by char setting.
