### ISSUE TITLE
Logger duplicating NPC texts

### ISSUE THREAD

**Issue by grevenilvec75** [Windower/Issues#214]
Actually have evidence in my logs going all the way back to 2011, so It's not something that's recent.  Possibly timestamp related since its showing two stamps for duplicated text.  Can't figure out how to use [code] tags or whatnot so forgive the free pasting.

Only seems to be NPC texts and things like kupowers and mog house exit messages

>[19:32:28]Horst : If there is anything you wish to know regarding Abyssea, it would delight me so to share my knowledge with you.
>[19:32:30][19:32:28] Horst : If there is anything you wish to know regarding Abyssea, it would delight me so to share my knowledge with you.
>[19:32:30]Horst : You'd like to teleport to a cavernous maw?
>[19:32:30]Through the power of the little red pretties we call cruor, I shall be overjoyed to assist you!
>[19:32:34][19:32:30] Horst : You'd like to teleport to a cavernous maw?
>[19:32:34][19:32:30] Through the power of the little red pretties we call cruor, I shall be overjoyed to assist you!
>[19:32:34]Horst : 200 cruor is required to teleport to the gateway to Abyssea - Uleguerand.
>[19:32:37][19:32:34] Horst : 200 cruor is required to teleport to the gateway to Abyssea - Uleguerand.

**Comment by Byrth** [comment]
The Logger plugin has been deprecated, so I'm going to close this issue.
