### ISSUE TITLE
Launcher: 'About' tab

### ISSUE THREAD

**Issue by Zireael** [Windower/Issues#241]
Hi,
How about adding an "About" tab (or button) to the Launcher and including there links to Windower forums, Bug Tracker page (so people know where to write up their bugs/suggestions), LUA addon page (in case anyone can/wants to contribute), "making a crash dump" link and maybe some "Latest news/issues" message?

**Comment by Nifim** [comment]
Implemented, links below each addon and plugin take you to the various related support and documentation.
