### ISSUE TITLE
Adding Storage Preferences for Gear Collector

### ISSUE THREAD

**Issue by Feary** [Windower/Issues#257]
I used Whitewing's Gearcollector app for a short time before it was discontinued. GC was then a made a plugin and has lost some functionality. i was able to set where my items went to by adding storage="sack|safe|etc" for example. here a post of the feature,

http://web.archive.org/web/20101013035535/http://wiki.windower.net/third_party_apps/gearcollector

i was wondering if this feature can be readded. i cannot use GC because i have a very carefully organized structure by each storage. otherwise i wouldnt be able to find my gear and switch gear with my current inventory. i have at least 10 jobs that are fully/decent geared.

**Comment by Byrth** [comment]
I have this logic implemented in Organizer, GearCollector's replacement. The hardest part turns out to be how you define the goal inventories and then prioritize ambiguous movements. Anyway, because it's not going to be implemented in GearCollector I will close this issue.
