### ISSUE TITLE
Game crashes when i want to start a new Windower for a 2nd char (Win7)

### ISSUE THREAD

**Issue by Mindicat** [Windower/Issues#364]
Hello, 
i have a new harddrive and installed windows 7, 64 bit. The Windower seems to work fine, but as soon as i want to start a 2nd session it crashes the already logged in character instant. 

Is there anything i can/need to do so i can log in 2 characters?

Thx Mindi.

**Comment by AnonCoder42** [comment]
Sorry to bump an old issue, but I ran into this problem as well. AlphaOne2’s suggestion to lower the AUC setting to the 2nd lowest whereby windows wont dim the screen solved my problem. 

Given that a common use of Windower is to run more than one copy of the game, would it be possible to add this problem/solution to the website FAQ? I would be happy to write a PR if someone can point me in the right direction.

Thank you

**Comment by zetaepyon** [comment]
I have added a new entry in the FAQ page related to this issue:
https://docs.windower.net/faq/#the-game-crashes-when-i-load-a-second-character-through-windower

Thanks for the idea!
