### ISSUE TITLE
Infobar [ Error on target display ?]

### ISSUE THREAD

**Issue by jafness** [Windower/Issues#413]
This might be because I have no idea how to customize Infobar but here goes...

Ingame, when I place the arrow over a 'Worker Crawler' in 'Crawlers Nest' the Infobar display makes no sense. It reads, "buff=_" on one line and "NNE 14" on the second line. I thought Infobar was supposed to display specific status details like how the particular mob aggros and such.

I need to know either where I can access some kind of guide/tutorial on using Infobar or if there's anything else I need to know. I basically just installed the PlugIn using the Windower 4 interface, made sure it was 'On' and... that's it.
I searched 'Infobar' and rummaged through a few previously reported issues but none seemed on par with this one.

Thank you so much for any help on this and if the problem IS that I just plain don't know how to use Windower, my sincerest apologies. Direct me to whatever guide I need and I'll take it from there. Mucho thanks!

P.S. I did /check the target Crawlers and got a good default display of details that read...
'It seems to have low evasion and defense'
Worker Crawler seems like level 41 (EP)

**Comment by Nifim** [comment]
the InfoBar plugin has been deprecated
