### ISSUE TITLE
Locker Availability

### ISSUE THREAD

**Issue by Byrth** [Windower/Issues#501]
Windower's plugin API has no way to tell whether or not a storage space is currently "available." For instance, when my mule's mog locker lease expires, Gearcollector still attempts to put things into it. In order to fix this, we need to come up with some way to tell which bags are actually available and implement it.

**Comment by Nifim** [comment]
This has been done, the `windower.ffxi.get_bag_info` returns if the bag is "enabled". when locker is not available it shows as false.
