### ISSUE TITLE
[Request] Gamepad Lock - init setting

### ISSUE THREAD

**Issue by EclipseSin** [Windower/Issues#562]
So recently I've been dual boxing using my brothers character, and I figured out how to run XI with more than one controller at a time. Basically you enable each controller one at a time in device manager as you open multiple XI windows. I made two reg files, 360.reg and logitech.reg to load the configuration of each controller, respectively. 

Now when POL is open, this works fine. I can control my character in the background with POL having focus, while the second controller works in POL. However, once the game starts up, losing window focus stops gamepad input now, however the individual controllers are correctly grabbed by each process. (I.E. .I can control the one i started with logitech controller with logitech controller when in focus, and the one i started with 360 controller, works with 360 controller when in focus)

The button mapings are different so I know the individual controllers are being used correctly, it just seems when dual boxing it lets go of controller when not in focus. Can windower add a lock gamepad option? Kinda like the reverse of the block mouse input.... Or is this a windows problem?

**Comment by IBHalliwell** [comment]
Hello,

I'm not sure when Square Enix added it, but in the Final Fantasy XI Config for Gamepad, you now have TWO new options:

1) Enable XInput
2) Enable gamepad when game is inactive.

Number 2 might help you.  It is allowing me to use my gamepad regardless of the focus status of the game.

It might be something to look into....  Hope this information helps.

**Comment by EclipseSin** [comment]
Ah, yes, I had noticed this a while ago. I believe it was added the end of the year, almost like 1 year after this topic was made. Haha. Thanks for the update though. If I had remembered this request at the time I would have updated the issue with comments too. 

Thanks for taking the time to reply.
