### ISSUE TITLE
Unable to install Etherpad in Windows, reported Error 0x80010135 (path too long). 

### ISSUE THREAD

**Issue by Majoar** [Windower/Issues#575]
Hi, I downloaded etherpad lite for windows, but when i try to extract the files i keep getting an Error 0x80010135 (path too long). What should i do? Thanks, Majoar

**Comment by Alexiaroksolana** [comment]
I've tried with Long Path Tool and It's working great,It will get the job done.

**Comment by Svetlanaa** [comment]
I've tried with Long Path Tool and It get's the job done,try It out.
