### ISSUE TITLE
RPC Bug; doesn't communicate if another instance starts a few hours(perhaps minutes) later

### ISSUE THREAD

**Issue by amadeus1171** [Windower/Issues#613]
There's an IPC bug that's been bugging me for a while now.
If I log in my main then decide to login my mule at a later time, I find that IPC does not work.  However, if I login my mules right after I login my main, then IPC works.  The same is true if one of my mules DC.  When they come back, IPC doesn't work.  It's almost as if the later instances get confused as to what port to use for IPC.  And while you're at it, when can we see RPC?  ^.^

**Comment by Byrth** [comment]
For a more thorough characterization of the problem, here is the setup:
1) Make a script named echoback.txt that contains: `send @all echo worked`
2) Login instance A
3) Immediately login instance B
4) Use `send @all exec echoback.txt` on instance A

This works all of the time, in that instance A displays 2x "worked" and instance B also displays 2x "worked", which implies two-way communication.

5) Wait some amount of time (This is required, unfortunately)
6) Log out instance A
7) Log in instance C
8) Use `send @all exec echoback.txt` on instance C

This only displays 2x "worked" on instance B and 1x "worked" on instance C, implying that instance C can talk to instance B, but not vice versa.

9) Use `send @all exec echoback.txt` on instance B

This only displays 1x "worked" on instance B and nothing on instance C, consistent with the idea that nothing is getting through to instance B. 

I am going to try and figure out the exact conditions required for Step 5. I'm not sure how long is needed, but it's very reliable if you play for a hours and I can't get it to happen when waiting <5 minutes. I'm going to try logging in to two instances, confirming the IPC connection works, and never logging in to characters, then closing one and logging back in in the morning. I figure this should be a minimally complicated example.

**Comment by Byrth** [comment]
I waited 1 hour and 20 minutes and it happened.

**Comment by cairthenn** [comment]
Closing this and leaving #978  open
