### ISSUE TITLE
LuaCore - Event registration/unregistration stack issue

### ISSUE THREAD

**Issue by Byrth** [Windower/Issues#619]
Hello! We've talked about this, but I figured I'd formalize it in an issue just to be sure. The following code causes stack issues:

```
windower.register_event('prerender',function()
    if ev then
            windower.unregister_event(ev)
    end
end)

ev = windower.register_event('prerender',function() end)
```

We hypothesized that the problem was the unregistering of an event that hadn't processed yet, so the stack gets popped one too many times by the handler for some reason. Also, the code works with any event.

**Comment by Byrth** [comment]
I long for the day when I can change jobs without unloading gearswap!

**Comment by tim-chaplin** [comment]
Any updates on this? This seems to still be an issue with an addon I'm developing. Is the workaround to just never unregister your event handlers?

**Comment by z16** [comment]
Not from within the same event. This will likely not be fixed, I am sorry to say.

**Comment by tim-chaplin** [comment]
I was running into the same issue even when unregistering outside of the event. My use case was a "one-time" handler that would get unregistered after waiting for a certain condition, eg:

```
local some_event_happened = false
local id = windower.register_event('incoming chunk',function(id, data)
    if some_condition then
        some_event_happened = true
    end
end)

while not some_event_happened do
    coroutine.sleep(1)
end

windower.unregister_event(id)
```

However, I was able to work around it by just not calling unregister.

**Comment by z16** [comment]
This is a bit weird, the first time I heard of this happening, I think. I remember specifically having an issue with this, and fixing it. It *should* work, but if you say it does not, I believe you. Sadly, the answer is the same as above, so not unregistering is probably the right thing to do here.

**Comment by Nifim** [comment]
Not planned at this time
