### ISSUE TITLE
Timers: wrong durations

### ISSUE THREAD

**Issue by Sechs** [Windower/Issues#628]
1) Adloquium and Animus Augeo/Animus Minuo got their duration swapped.
Currently Timers reports the first as 3mins base duration and the other 2 spells as 1min base duration.
It's the other way around.

2) Regen spell durations wrong while Light Arts is up and Perpetuance is used.
Without Perpetuance times are right. Timers correctly applies the bonuses from Job Points and from the item "Coeus".
When you use Perpetuance though something goes wrong, Regen lasts more than Timers displays.
This probably means that there's a part of the formula that isn't currently being multiplied by the 2,5x factor given by Perpetuance.

3) Protect/Shell spells do not get accounted when you use them after Perpetuance (2,5x more duration).
Contrary to what many may believe, Perpetuance works perfectly on Protect/Shell, and Timers did account correctly for the additional duration up to some versions ago at least.

4) DNC Sambas do not take into consideration the additional duration from Job Points (+2 seconds per level)

**Comment by Humetaru** [comment]
Hi, didn't want to make a new threat about this, but Timers has been showing the wrong duration with Composure. It is only considering Double time instead of Triple duration time. I've tested this with and without Composure and with and without enhancing gear on so I'm pretty sure that's the issue.

**Comment by z16** [comment]
I thought Composure did that, double the duration time? Or is there something else?

**Comment by Sechs** [comment]
It's triple:
http://wiki.ffxiclopedia.org/wiki/Composure

**Comment by Humetaru** [comment]
Sorry for the delayed reply, as Sechs mentioned it's Triple duration.

**Comment by z16** [comment]
Ok, I'll adjust that today.

**Comment by z16** [comment]
This has since been fixed.
