### ISSUE TITLE
strange crash

### ISSUE THREAD

**Issue by smd111** [Windower/Issues#629]
here is my dump
http://www.filedropper.com/polexe3628

the addons and plugins i have loaded
plugins
JAZero
LuaCore
AutoExec
ChatMon
ConsoleBG
StatusTimer
TParty

addons
cancel
distance
DressUp
GearSwap
pointwatch
Treasury

no external apps and this is incredibly random

**Comment by smd111** [comment]
here is a new dump not sure if there tied to this crash or not but it happens the same way
uncompressed(21.4 mb)
http://www.filedropper.com/polexe3268
rar compressed(4.37 mb)
http://www.filedropper.com/polexe3268_1
7zp compressed(3.95 mb)
http://www.filedropper.com/polexe3268_2

**Comment by smd111** [comment]
ok i have been doing some testsing by turning off and on plugins and i think the jazero plugin is causing the issue

**Comment by smd111** [comment]
yup its the jazero plugin

**Comment by Byrth** [comment]
Are you using a second program that might ve messing around in memory? I use jazero with no problems.

**Comment by smd111** [comment]
no

**Comment by Byrth** [comment]
I assume this was fixed because you've kept playing. Please feel free to reopen it or open a new issue if it wasn't.
