### ISSUE TITLE
GearCollector not opening storage

### ISSUE THREAD

**Issue by rijaxo** [Windower/Issues#639]
Gearcollector doesn't seem to open up storage anymore (redownloaded, and checked that configure had openstorage set to true).  This was very helpful as I have some files setup that can fill up inventory completely.

**Comment by Byrth** [comment]
GearCollector will soon be replaced, but this was not a feature that I intended to add to Organizer. Why do you want it?

**Comment by rijaxo** [comment]
Actually opening wouldn't really be necessary but if something could show up if your inventory runs out of room while collecting that would be great.

I've got a few files I use to clear up my inventory that collect tons of stuff so it's nice to know when to stop the collection.  This would also be useful if you've got too much gear in one of your job files.

**Comment by Byrth** [comment]
Okay, I can implement a mode in the new add-on that prints out gear that could not be collected.

**Comment by rijaxo** [comment]
That would be awesome.  For me it would be great if it would truncate at some point and just spit out the number missing (inventory cleanup ones I use would spew out tons of stuff)

**Comment by Byrth** [comment]
Okay, I'm going to close this issue because I've opened a new one on my tracker for the organizer addon (which will replace GearCollector):
https://github.com/Byrth/Lua-Byrth/issues/365
