### ISSUE TITLE
d3d8.dll crashes

### ISSUE THREAD

**Issue by mattwells** [Windower/Issues#656]
I was have been having issues with it crashing d3d8.dll to the point where it was unusable. A friend suggested under clocking the memory and this did help but I am still getting random crashes, sometimes multiple times per day. I have noticed that it happens more often while multi-boxing, I will get a little alert from nVidia saying the graphics drivers have crashed. When this has happened the game will be come unresponsive for some time, after this the game will "play" (as in I can hear my character's steps) but the screen will not change, a short time after this it will completely freeze up.

The windows event log shows the following:

http://pastebin.com/616zssut
http://pastebin.com/bugY0W6f

In the last link there was one file in the "C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_pol.exe_d67d6cfd32ad429e739c86947d6fc7f30cd3b1d_52d02681_0f31be3e" location which was Report.wer which you can find here:

http://pastebin.com/EXdAJERs

This is a brand new PC that I built over Christmas running the Windows 8.1 with all patches applied and UAC disabled.

CPU: Intel Core i5-4690K
GPU: nVidia GeForce GTX 980 driver version 347.09
RAM: HyperX FURY 16GB
HDD: Samsung XP941 256GB

Plugins:
-    luacore (1.8.1.2)
-    binder (1.4.1.1)
-    chatmon (1.10.0.3)
-    drawdistance (2.2.1.3)
-    ffxidb (0.9.2.1)
-    guildwork (1.4.2.7)
-    lightluggage (4.0.1.1)
-    sandbox (1.0.1.5)
-    ssorganizer (1.5.1.6)
-    timers (3.6.1.2)
-    tparty (1.2.2.9)

Addons:
-    Cancel
-    Distance
-    DressUp
-    GearSwap
-    Itemizer
-    reive
-    Shortcuts
-    Silence
-    timestamp

If someone could tell me how to retrieve more useful debug information please let me know. 

Edit: I am now running the automatic crash dump hopefully I should have something useful soon.

**Comment by Byrth** [comment]
Crash will be useful in determining whether or not it has anything to do with windower.

However, just to brace you for what is to come, FFXI isn't very compatible with Windows 8 or newer nvidia cards. The odds of it being windower related are pretty low. If you want to test whether it is or not, you could try using the official windowed mode (no windower) and see if you can replicate the issue.

**Comment by mattwells** [comment]
Ok it has just happened to me now and I haven't got a dump file. It does seem as though the game will loose connection to the server but not actually fully crash the game until I try to get focus on the window.

**Comment by mattwells** [comment]
I have been talking to my friend Saevel (he said he knew you @Byrth) he said he has exactly the same problem but running except Windows 7. He has been experimenting to see if its one of the plugins or addons and although it happens less often with fewer extra it does still happen. I have asked him to post he findings here but as yet hasn't really been around very much. I'll keep asking him though.

**Comment by mattwells** [comment]
Finally crash dump: https://drive.google.com/file/d/0B0WlK1EjPd-oZll3ZjNLaWxCSm8/view?usp=sharing

**Comment by Nifim** [comment]
Windows 8.1 is no longer supported, also potentially the time where the proxy had anti windower code in it?
