### ISSUE TITLE
SMN Blood Pact Timer Issues

### ISSUE THREAD

**Issue by Crevox** [Windower/Issues#657]
Cool that these got added, but there's some issues.

-Occasionally, even when wearing Summoning skill over 500 (like 546) Blood Pacts that should be 6:20 show up as other durations (5:55 Dream Shroud for example).

-New Blood Pacts added recently are not tracked. These are Hastega II, Crystal Blessing, and Soothing Current. These are all base 3:00 duration, max 6:20 with 500 skill.

-Earthen Ward and Aerial Armor are receiving boosts to their duration. As far as I know, these are flat 15 minute duration, but I could very easily be wrong. Earthen Ward, for example, came up as 17:55 when I used it.

-When I zoned, some of the timers changed from Aerial Armor [AoE] to Aerial Armor [Unknown].

-Is there any way to disable the timers, or move them to the right side once they are fixed up? I prefer having the Blood Pacts on the third column of timers so it's easier to see my buffs versus the summons, which is currently running off my Gearswap file adding the timers. I often have 7-9 buffs from avatars going up at once, so having them in the same column really makes it hard to see my own buffs. These are also currently putting in the right times versus the wrong times of the official support, with fancy icons.

-No fancy icons! Here are some: 

```
        ['Earthen Armor']   = 'spells/00299.png', -- 00299 for Titan
        ['Shining Ruby']    = 'spells/00043.png', -- 00043 for Protect
        ['Dream Shroud']    = 'spells/00304.png', -- 00304 for Diabolos
        ['Noctoshield']     = 'spells/00106.png', -- 00106 for Phalanx
        ['Crimson Howl']    = 'spells/00298.png', -- 00298 for Ifrit
        ['Inferno Howl']    = 'spells/00298.png', -- 00298 for Ifrit
        ['Soothing Current']    = 'spells/00169.png', -- 00169 for Water Icon
        ['Crystal Blessing']    = 'spells/00269.png', -- 00269 for Ice Icon
        ['Hastega']         = 'spells/00358.png', -- 00358 for Hastega
        ['Hastega II']         = 'spells/00358.png', -- 00358 for Hastega
        ['Rolling Thunder'] = 'spells/00104.png', -- 
        ['Frost Armor']     = 'spells/00250.png', -- 00250 for Ice Spikes
        ['Lightning Armor'] = 'spells/00251.png', -- 00251 for Shock Spikes
        ['Reraise II']      = 'spells/00135.png', -- 00135 for Reraise
        ['Fleet Wind']      = 'abilities/00074.png', -- 
```

**Comment by z16** [comment]
> Occasionally, even when wearing Summoning skill over 500 (like 546) Blood Pacts that should be 6:20 show up as other durations (5:55 Dream Shroud for example).

This is a rather difficult to fix issue, but we have some ideas. To clarify, the reason for this is that the packet containing skill information (which is what we base our skill on) is not sent every time you change gear, so if the spell goes off shortly after you changed gear into a Summoning skill set (which you're likely to do for BPWs) it's not guaranteed that we have the most up-to-date skill information. But like I said, we have some ideas that we'll try to implement tomorrow.

> New Blood Pacts added recently are not tracked. These are Hastega II, Crystal Blessing, and Soothing Current. These are all base 3:00 duration, max 6:20 with 500 skill.

These have been added.

> Earthen Ward and Aerial Armor are receiving boosts to their duration. As far as I know, these are flat 15 minute duration, but I could very easily be wrong. Earthen Ward, for example, came up as 17:55 when I used it.

This has been fixed.

> Is there any way to disable the timers, or move them to the right side once they are fixed up? I prefer having the Blood Pacts on the third column of timers so it's easier to see my buffs versus the summons, which is currently running off my Gearswap file adding the timers.

There is no way to do that and there won't be. If you want that you'll have to do it as you do now, use GS for it (or any addon) and filter the ones that Timers creates with the blacklist feature.

> No fancy icons! Here are some:

The icons are determined automatically by their, we don't supply them. We can override them manually though... We'll think about it.

**Comment by Crevox** [comment]
Also, typing "timers" into the console crashes the game.

What is this blacklist feature? I found the xml but not sure how to input the IDs or what the IDs even are.

**Comment by z16** [comment]
Please open new tickets for different issues, makes it easier to manage them.

For the "Unknown" thing, did you zone to make that happen? Or did someone else you cast the buff on zone?

**Comment by z16** [comment]
> Also, typing "timers" into the console crashes the game.

Fixed, will push that out with the other changes later.

**Comment by Crevox** [comment]
Yes, zoning makes that happen. I apologize for putting too much into this issue.

**Comment by svanheulen** [comment]
Reraise II from Cait Sith should also be a fixed duration with no bonus from Summoning skill. Also, my ward timers are still about 6 seconds short but that's not a big deal. Thanks for adding this feature :)

**Comment by z16** [comment]
The problem, as described above, has not yet been fixed. All skill adjustments for BPWs are currently inaccurate and will be until we find a way to implement this. Thanks about Reraise II, I didn't know that, I'll add that to the next Timers release.

**Comment by Crevox** [comment]
Well is this another bug then? Cause this isn't working with Hastega II:

```
 <blacklistMode>true</blacklistMode>
        <whitelistMode>false</whitelistMode>
        <recastList />
     <buffList>602</buffList>
```

**Comment by Nifim** [comment]
Chiaia implemented this 2 years ago
