### ISSUE TITLE
Crashes when switch from POL to FF

### ISSUE THREAD

**Issue by Spearbx** [Windower/Issues#658]
as the title says when switching from POL screen to FF screen windower crashes. I've uninstalled/re-installed W4 several times with no success. could use some assistance, any would be appreciated. I'm not tech savvy but I'll follow any instructions to resolve this issue, thanks in advance.

**Comment by z16** [comment]
Are you on Windows 8?

**Comment by Spearbx** [comment]
8.1

**Comment by Byrth** [comment]
Sorry, but this seems to be an issue with Windows 8 that we don't know how to solve. They seem to arise randomly and then rarely disappear. There are other people that have had similar issues and have had varying amounts of luck fixing them:
https://github.com/Windower/Issues/issues/136
