### ISSUE TITLE
Pet commands & windower.ffxi.get_abilities().

### ISSUE THREAD

**Issue by trv6** [Windower/Issues#661]
Pet commands appear under the job_abilities key in the table returned by windower.ffxi.get_abilities().

**Comment by z16** [comment]
I don't think this is a bug. They're also in the `job_abilities.lua` resources file. What were you expecting them to be? In-game they behave as job abilities

**Comment by Byrth** [comment]
We debated this for a while the last time they changed those packets and couldn't see any reason to separate "pet commands" and "job abilities." They're handled in exactly the same way in every notable case.

**Comment by trv6** [comment]
Did the packet originally separate the abilities? It's no big deal, so this can be closed, but I thought I remembered the key existing.

**Comment by z16** [comment]
Honestly, I don't remember... the "pet_commands" key kinda rings a bell, but I'm not seeing it anywhere in LuaCore, so not sure. Too lazy to search the history atm. But looks like this can be closed.

**Comment by Byrth** [comment]
Pet commandshave always been continuous with JAs, show up in the same DAT, etc. Afaik

**Comment by Byrth** [comment]
Pet commandshave always been continuous with JAs, show up in the same DAT, etc. Afaik
