### ISSUE TITLE
Timers failing when zoning in delve

### ISSUE THREAD

**Issue by Cptbirdseye** [Windower/Issues#663]
When entering a delve the addon crashes and puts a ghost image of the addon in the top-right corner that won't be removed even when reloading or unloading it or changing characters.  This also pops up in the console:

20:17:49 > timers encountered a fatal error and must be terminated. Error: Access violation in IncomingChunk method.
20:17:49 > timers - Plugin successfully unloaded.

**Comment by Byrth** [comment]
This was likely update-related. It should be fixed now. Please reopen this issue or make a new one if it is not.
