### ISSUE TITLE
Guildwork crashing

### ISSUE THREAD

**Issue by Cptbirdseye** [Windower/Issues#664]
No idea what triggers this but it's the same error Timers has.  I think it happens when I zone but it's inconsistent.

01:41:09 > guildwork encountered a fatal error and must be terminated. Error: Access violation in IncomingChunk method.

**Comment by Byrth** [comment]
Once you get one error like this, it tends to propagate until you restart your FFXI process.

**Comment by Byrth** [comment]
This problem was, as far as we know, an update-related plugin problem. We now view it as solved. If you are having trouble loading plugins and still get this error, first check this list to make sure that the plugins haven't become unsupported:
https://gist.github.com/z16/f73d0912e5c5ed02c58b
