### ISSUE TITLE
crash on log in 

### ISSUE THREAD

**Issue by swordwiz420** [Windower/Issues#665]
i keep crashing as soon as i go to log on i can get to were it picks my char and shows the black screen of it logging on that char but aright as the scoreborad pops up it crashs

**Comment by Byrth** [comment]
There was an update that changed a bunch of signatures. Try rerunning launcher now.

**Comment by Byrth** [comment]
There was an update that changed a bunch of signatures. Try rerunning launcher now.

**Comment by Byrth** [comment]
There was an update that changed a bunch of signatures. Try rerunning launcher now.
