### ISSUE TITLE
Highlight/highlight.lua:207:"name" is not defined for numbers

### ISSUE THREAD

**Issue by AntFFXI** [Windower/Issues#667]
Highlight: Lua runtime error: Highlight/highlight.lua:207:"name" is not defined for numbers

This error appears ALL the time. I have turned plugins and add-ons off and on, nothingg stops it. even reinstalled  Windower.. HELP! thank you in advance.

**Comment by z16** [comment]
The error should disappear if you unload Highlight (the addon). Either way, I pushed a fix for it just now. Run the Windower launcher to update.

Also, please report Lua errors on our [Lua issue tracker](https://github.com/Windower/Lua/issues) in the future.

**Comment by Byrth** [comment]
Going to close this issue, because it was fixed. If you are having problems getting the update that fixes the issue, use this link to get a zip of the current repository:
https://github.com/Windower/Lua/archive/4.1.zip

Then copy the highlight folder over to your addons directory.
