### ISSUE TITLE
FindAll feature request

### ISSUE THREAD

**Issue by sebyg666** [Windower/Issues#668]
the plugin Find had a command to be able to manual add an item to track. I used this to track different things on different jobs. for example i do not need to track angons when not playing drg. could the "//find track add whatever" functionality be added to findall. this would be much apreciated.

**Comment by z16** [comment]
Will do!

**Comment by sebyg666** [comment]
awsome. thankyou.

**Comment by Byrth** [comment]
I'm pretty sure this was added.
