### ISSUE TITLE
Playonline viewer crash

### ISSUE THREAD

**Issue by ddloreman** [Windower/Issues#669]
After playonline viewer goes through its load and you push the last play button it says the viewer crashed.  I can load without windower 4 if I default the config prior to every load directly off of Playonline viewer.  This all started after the update on the 15th this month.  The dump file is to big to put in this post.  Let me know how I can get it to you.

**Comment by z16** [comment]
Are you sure you're talking about a dump file? It ends in `.dmp` and it's not a text file, so you can't post it here regardless of size. You can post it on any file hoster online or use DropBox/Google Drive or some similar service to get it to us.

Here's a tutorial on how to create dump files:
https://github.com/Windower/Issues/wiki/Enabling-automatic-crash-dumps

**Comment by ddloreman** [comment]
The dump file was created just need to know I guess how to send it to you.

**Comment by ddloreman** [comment]
The file is pol.exe.4720.dmp

**Comment by z16** [comment]
Any which way. Any random file hoster, DropBox, Google Drive, forum attachment, even E-Mail for all I care.

**Comment by Byrth** [comment]
Given the lack of a response over the last few months, I'm going to assume the dump file either no longer exists or is no longer useful. Closing. Please re-open if you still have the issue and can post the dump file somewhere.
