### ISSUE TITLE
AutoUpdate not functioning correctly?

### ISSUE THREAD

**Issue by sharinganheir** [Windower/Issues#670]
The last few days on the loading screen the bar flashes quickly but updates nothing. Noticeable by the lack of any newer Addons on the list (lack of consolebg addon used as example):
![addon](https://cloud.githubusercontent.com/assets/10589744/5794987/a96798e2-9f52-11e4-853c-5329f38e710b.JPG)
All the "missing" addons are also missing from the \updates\addons.xml file.

May be more of an issue for XP users as it seems to be an issue with myself and another LS mate, and may be related to the same issues in this thread. (pointed out by another LS friend as the topic came about due to the exact same GS error.) 
http://www.bluegartr.com/threads/115131-Windower-4-Discussion-and-Support?p=6320273&viewfull=1#post6320273

Hope this is the correct place to report this.

**Comment by z16** [comment]
This is as fixed as it'll get.
