### ISSUE TITLE
Gearswap Feature Request

### ISSUE THREAD

**Issue by sebyg666** [Windower/Issues#672]
ok this is aimed at geaswap.lua line 554.

windower.register_event('gain buff',function(buff_id)

could we possibly have this function and its counter part lose buff also return the ID of the buff and not just the name.
reasons for feature:
- different kinds of buffs with same name. for example "Haste" with ID's 33, and 580. I'm pretty sure 580 is indi-haste buff from geo which is rather different then standard haste. would be nice to be able to script for it. Another that comes to mind is the sleep buff. I think one refers to the kind of sleep u can only wake from a cure (nightmare mandies in valkurm do this).
its either that or rename the buffs with same name in resources. which I'm pretty sure is never going to happen lol ^^.

- I actually cant think of another reason but i think this one is pretty good as is. thanks in advance if you do change it.

(quick note: If there is some methodolagy for the above I can call within a user file that I'm not aware of please let me know of it and delete this issue.)

**Comment by Byrth** [comment]
Yeah, I agree that is a problem. If I ever release another major version update to GearSwap I'll probably revise the event to only pass the buff resource table instead of buff name. As it is, I may just add a third argument that is the resource table for the buff.

**Comment by sebyg666** [comment]
that would be fantastic. thanks for the reply

**Comment by Byrth** [comment]
Added on -dev~!
