### ISSUE TITLE
Run Plugin doesn't accept "\"s in file paths

### ISSUE THREAD

**Issue by KenshiDRK** [Windower/Issues#676]
run plugin seems to don't work after the update, it will print file path don't found in the console regardless the file path is ok.

**Comment by KenshiDRK** [comment]
After looking into it its seems after update it won't work using \ for the file path, but it is working using /

**Comment by z16** [comment]
Any chance you're on Windows XP?

**Comment by KenshiDRK** [comment]
no, Im on Vista

**Comment by Nifim** [comment]
Works fine now :D
