### ISSUE TITLE
Lua error not showing line number

### ISSUE THREAD

**Issue by amadeus1171** [Windower/Issues#678]
I'm writing my own addon and I accidentally write the line

input

That's an error, of course.  But when I load the addon I get the error:

addon name: Lua runtime error: attempt to call a string value

But it doesn't specify a line number.

**Comment by z16** [comment]
Yes, I've dealt with that before, I'm not entirely sure what causes this, but something is wrong with certain types of syntax errors. They just give a generic error message without line numbers. I'll look into this.
