### ISSUE TITLE
BoxDestroyer - Doesn't Work on Meebles Chests

### ISSUE THREAD

**Issue by FFXI-Misora** [Windower/Issues#679]
The chests in Meebles work differently then the standard gold chests:
They are more like the Abyssea ones where you enter a number each time and then get BOTH a higher or lower based off the number you entered plus a hint about the number. (I haven't checked if the plugin is working on abby gold chests as everyone just keys those anyway.)

The old BoxHelper plugin was buggy with the meeble chests and would only show the results for one of the two hints but that was still helpful. However, BoxDestroyer doesn't show anything for these chests at all.

Also, an option to make the suggestions pop up as soon as you get the hint rather than next time you click the chest (like plugin did) would be nice. Thanks!

**Comment by Byrth** [comment]
Closing this to open an issue on the BoxDestroyer maintainer's tracker.
