### ISSUE TITLE
Timers - Duration Error

### ISSUE THREAD

**Issue by FFXI-Misora** [Windower/Issues#680]
Hello,

Thanks for fixing the recent problem with Composure. Timers when casting on myself are all correct again!

However, durations when casting on others are still off:
When casting Haste 2 on someone else with Composure, Emp+2 set and Emp Cape duration is being calculated as 3 x 1.8 = 5.4 min, when the actual duration is 3 x 1.5 x 1.3 = 5.85 min.

The gear (10% from cape and 20% from feet) should be added together and then multiplied with composure's set bonus of 50%. This calculation is being done correctly for self casting but not for casting on others.

Thanks again for all the hard work. Your plugin is what lets me keep a whole alliance hasted while doing all the other stuff that comes with the job! :)

**Comment by z16** [comment]
Do you happen to know if the set bonus is applied before or after the individual item bonus?

**Comment by FFXI-Misora** [comment]
The item bonus' are added up 10% + 20% = 30% and the multiplied with the both the 50% set bonus and the base duration.

You have the calculation exactly right for self casting where you have:
3 min x 3 (composure) x 1.46 (items) = 13.14 min.
Where the items are 10% cape, 20% feet, and 16% AF+1 hands.

**Comment by z16** [comment]
Where does the set bonus fit in there?

**Comment by FFXI-Misora** [comment]
The set bonus is what makes composure give a 50% bonus to others (with all 5 pieces). Normally composure does nothing for others.

So it should be Base Time x Composure Set Bonus x (Sum of Item Bonus).

It was working properly up until a few weeks ago. It got messed up the same time as all the JAs started showing up as different names.

**Comment by z16** [comment]
Ah, so the set bonus does nothing for oneself... Ok, thanks, I'll incorporate that today.

**Comment by z16** [comment]
This has been fixed, by the way, but not sure if it has been pushed to live today. A new version will be pushed regardless later today.
