### ISSUE TITLE
Rolltracker not calulating Barataria Ring correctly

### ISSUE THREAD

**Issue by mrjdj1998** [Windower/Issues#686]
Rolltracker does not recognize Barataria Ring, Phantom Roll +5 is not calculate when rolling. Rolls calculate as if there was no ring on. Works fine when I switch to the Merirosvo Ring Phantom Roll +3. Only using one or the other ring because they do not stack.

**Comment by Byrth** [comment]
I opened an issue on the author's bug tracker, here:
https://github.com/Podginator/Lua/issues/13

Going to close the issue now.
