### ISSUE TITLE
Timers - BST Ready Charges

### ISSUE THREAD

**Issue by FalkirkBST** [Windower/Issues#687]
Hello! :)
With the upcoming changes to Sic/Ready recast timers, would it be possible to implement something similar to SCH Stratagems (where we can see how many stratagems have been consumed as they're recharging)?

The current situation is:

Ready Charges replenish every 60 seconds (and we get 3 Charges maximum).
Sic can currently be used every 120 seconds (since Ready/Sic share a recast timer, this essentially consumes 2 Charges).

After the mid-February update:

Ready Charges replenish every 30 seconds (still 3 Charges maximum).
And Sic recast timer will be lowered to 90 seconds (so this consumes all 3 Charges, post-update).

Thank you!

**Comment by z16** [comment]
I'll add this after the update. Could you please link me to the update info?

**Comment by FalkirkBST** [comment]
Awesome. :)

Here's the info link:
http://forum.square-enix.com/ffxi/threads/45934-dev1254-Job-Adjustments?p=539407#post539407

**Comment by Byrth** [comment]
I believe this was handled months ago, so I'm going to close the issue now. Please reopen it if it is still a problem.

**Comment by FalkirkBST** [comment]
Hi!

I almost forgot about this... He must've been too busy to implement it, but it would've just been a cool thing to have (being able to see remaining charges) - not critical though, so no worries. :)

**Comment by Byrth** [comment]
Do you know if it displays for Stratagems and such? If so, then the framework already exists. I'll reopen it for now.

**Comment by FalkirkBST** [comment]
Yessir. :)

Timers puts a little "[2]", "[3]", etc as you consume your Strategem charges so there's a sort of "Countdown" as they return.

**Comment by Byrth** [comment]
Okay, I looked at this today. The most difficult-to-solve problem is that we can't know whether we're waiting on Sic (no charges) or a Ready move (charges) without knowing pet type (Jug vs. Charmed), something we don't currently track.

As far as technical minutiae past that point:

Ready recast gear/merits have an effect when you use the move and reset your remaining timer for all charges, which is strange (but fortunately simple) behavior.

Ex. A player has Warlike Patrick out and uses Infrasonics (2 charges) with 5 Sic/Ready recast merits and 100 JPs but no gear on (-10s). The game says it's 20 seconds until the next charge (40 seconds until fully recharged) and there is 1 charge remaining. The player then puts on Desultor Tassets / Charmer's Merlin (-20s) and uses Secretion (1 charge). The game now says it's 10 seconds until the next charge (20 seconds until fully recharged). It is counter-intuitive, but spending a charge actually decreased the amount of time to 3 charges.

In terms of what people actually use, I think it's pretty rare for people to Charm these days (and thus setting Ready to the default would be more accurate) and you sacrifice pet iLevel when you swap to Charmer's Merlin, so it's uncommon to find a BST who uses that piece either. Tassets might be used but I'm not sure.

**Comment by FalkirkBST** [comment]
Heyo, Byrth. Thanks for following up on this. :]

So do you suppose this is possible to implement based on all that? Would be awesome, if so. And yeah, Charm/Sic are *maybe* something a BST would use from level 1-23... I don't really see it being relevant outside of that, so if it makes your task easier by focusing on Ready instead, then great!

All of the endgame BSTs will be using Merlin/Tassets to minimize the timer to 10-sec charges. Many will equip Charmer's Merlin in the offhand so they don't lose iLvl at all. Even with single-wielding, I find Gearswap can handle it and receive iLvl stats in time for the Ready move to complete. 10 second Ready charges is the gold standard everyone is after, but many will be stuck at 30/25/20/15 during their levelup/CPing process.

I get the sense it's a bit of a hassle because the Charge recast isn't as static as the Stratagem recast, but thanks again for looking into it!

**Comment by Nifim** [comment]
I did this a month ago! good job me!
