### ISSUE TITLE
SOLVED - Windower 4 full crash when expanding chat log (Due to Old version of XiView 2.20)

### ISSUE THREAD

**Issue by Jurbie** [Windower/Issues#688]
Description of issue: Instant Crash when I open my chat log. This is strange because I did not have this issue until today. I logged into FFXI today and windower updated when I logged in just like it always does. Now I crash when I open my chat log and it has to be related to something that was changed to windower/addon/plugin in the last 24 hours. This was not an issue yesterday so I am wondering what happened in the updates to cause this.

Operating system:  windows 8.1 64 bit. Before you say “This is a windows 8 issue” just know I have been playing with Windower4 on windows 8 since it came out with 0 issues. I have even reformatted and done full install twice with no issues the community is reporting and even helped about half a dozen people resolve windows 8 windower 4 issues. I have been playing fine for at least a year with 0 crash issues and in the last 24 hours something changed and now I crash when I expand chat logs.

Windower version: Windower 4

Windower plugins/addons/other: Addons = Aecho, boxdestroyer, Chatlink, consolebg, distance, findall, gearswap, lottery, rolltracker, scoreboard, silence, speedchecker, timestamp, tparty, translate, zonetimer
Plugins = autoexec, blinkmenot, chatmon, gearcollector, guildwork, lightluggage, ssorganizer, statustimer, tickle, timers.
3rd party tools = 0, happens without running any.

Windower settings: Please state the settings you are using, you can copy these from the settings.xml (v4) or launcher.ini (v3.4) in your Windower folder, make sure they are for the correct profile though.

Details of how the issue happened: I open my chat log, and it crashes. I am multi boxing, but it does it with 1 account or 3 accounts open. It did not do this yesterday 2/5/2015 but with windower 4 auto updateing now when I logged in today I crash when I maximize any chat log in any zone.

I also have the crash dump if needed.

**Comment by IryokuChevalier** [comment]
The last change to Hook was 22 days ago, so that seems unlikely. The last plugin update was 7 days ago to a plugin you're not using. The last plugin that was updated that you *are* using was Timers 11 days ago. Something else has to have changed, as it seems very unlikely (but not impossible) that an addon could be causing this. We'll definitely need to see the crash log; post it to Dropbox, Google Drive, or whatever your personal favorite file sharing website is, and leave a comment with a link to it here.

**Comment by z16** [comment]
This is likely a XIView issue.

**Comment by Jurbie** [comment]
Ok will do, I wasn't paying attention to what was updating when I loaded up for the day so that was a total assumption on my part. Good to know nothing has really changed. I don't know if this matters, but I would like to add this all happened in west adoulin right near the MH congestion, but when I just tried to open my log in mhaura it didn't crash me.... kinda odd. I was able to get it to crash all my accounts in west adoulin one after the next just by opening the log multiple times while testing, (even in the Mog hosue) but in other zones it isn't doing it. I also have not had any PC changes of any kind software/hardware in the last 24 hours. (automatic updates are off) and I am having no other issues on my PC. here is the link to the crash dump.

https://www.dropbox.com/s/6137jppr7tuv0fo/pol.exe.6820.dmp?dl=0

**Comment by Jurbie** [comment]
Thanks for the quick replies guys and everything you guys do! If this is caused by XiView 2.20 that would be a VERY easy fix if the default items that are in the download are still "Current". That makes total sense that it would be adoulin only because XiView has had many issues since the adoulin expansion. It is possible that I have not maximized my chat logs in adoulin since I fiddled with XiView 2.20 stuff last, but I am not certain. If the crash dump isn't clear, I can reload default values from XiView and retest to see if that was in fact the issue. Any alternative to XiView 2.20?

**Comment by KenshiDRK** [comment]
XiView was fixed for this sometime ago, so you are using a outdated version:
Wildman version https://github.com/W...XIView/releases
Caradog version http://bit.ly/1zojoe2
