### ISSUE TITLE
Timer Plugin doesn't recognize RDM's  Ghostfyre Cape's Enhancing Duration+%

### ISSUE THREAD

**Issue by jonnycbad** [Windower/Issues#689]
I have a Ghostfyre Cape for RDM with Enhancing duration +15%, it doesn't work though for Timers.

**Comment by z16** [comment]
Can you do some tests for me? Does the Ghostfyre Cape stack with either Atrophy Gloves or Estoqueur's Houseaux +1/+2? What about the Estoqueur's set bonus or Composure? I need to know the answer to these questions before I can add it. If anyone could post those, I'd appreciate it.

**Comment by jonnycbad** [comment]
Yes it stacks exactly the same way as the other piece. For example, without the cape it says my haste should last a little over 12 minutes with Conposure, Estoq Feet, Atrophy+1 hands. But a few months ago, when timers worked fine, with all of those + ghostfyre, haste lasted over 14 minutes. 

If i understand how the stacking works it should be like:

Haste durarion base: 180s
Composure: x3.0
Atrophy+1: x1.16
Estoq boots: x1.20
Ghostfyre: x1.15

That gives me 864 second haste which should be around 14minutes and 20ish seconds. But ghostfyre's augment is random and can range from 0-20.

**Comment by z16** [comment]
The boni of these items are all added. Composure is multiplied before those. So the result should be this:
Haste duration base: 180s
Composure: 2.00 first multiplier
Atrophy Gloves +1: 0.16 second multiplier
Estoqueur's Hoseaux +2: 0.20 second multiplier
Ghostfyre Cape: 0.15 second multiplier

The base first and second multipliers are both 1.00 and those values are added on top of it. So it should result in:
180s * (1.00 + 2.00) * (1.00 + 0.16 + 0.20 + 0.15) = 180s * 3.00 * 1.51 = 815.4s = 13min 35.4s

The only thing I'm not sure about is whether or not Ghostfyre Cape was the first, second or third multiplier (which also exists). So if you can do me a quick favor and test the following setup:
Haste with Composure, only Estoqueur's Hoseaux +2 and Ghostfyre Cape equipped.

If the duration is 11min 20s it means the cape contributes to the first multiplier. If it's 12min 9s it falls under the second multiplier. If it's 12min 25s it falls under the third multiplier. If it's something else, something went wrong.

**Comment by jonnycbad** [comment]
Composure+Estoq feet+Ghostfyre= 12:42

It makes sense to me. 

Haste=180s
180*3.0*1.15*1.20=745.2 or 12min 42s
I dont think it matters what order it is because it's commutative. The bonuses are not added together, in other words, the formula isnt 180 * (3.0+1.15+1.20) its 180*3.0*1.15*1.20.

**Comment by jonnycbad** [comment]
With feet hands cape and composure, haste should be 14:42 duration

**Comment by z16** [comment]
12:42 makes no sense, those numbers multiply up to 12:25. Do you have job points or anything else that could affect the results?

**Comment by jonnycbad** [comment]
180 x 3.00 = 540s
540 x 1.15 = 621s
621 x 1.20 = 745.2s
745.2/60 = 12.42
Haste on myself is lasting 12min and 42 seconds. I dont see the issue.

**Comment by jonnycbad** [comment]
Theres no job points for rdm that enhance duration by the way

**Comment by IryokuChevalier** [comment]
745.2 seconds is floor(745.2 / 60) = 12 minutes, 745.2 % 60 = 25.2 seconds. You can't just divide by 60, because that gives you a decimal result, not a sexagesimal (base 60) result. You have to take the fractional part (0.42) and multiply that by 60 to get the number of seconds.

**Comment by jonnycbad** [comment]
I can test again later but haste definitely lasted 12:42 according to the icon timer :/

**Comment by jonnycbad** [comment]
I just checked, you were right. 12:25. Its off by a second or two cuz timestamp is a bit inaccurate but the status timer was 12:25 before it clicked off

**Comment by z16** [comment]
Ok, thanks, I'll add this now and push this along with some other Timers changes.

**Comment by Byrth** [comment]
Keep in mnd that zoning will add a few seconds to buffs, as will talking to certain NPCs. When doing this testing you pretty much need to cast and afk.

**Comment by z16** [comment]
This is incorporated and will be pushed shortly.

**Comment by jonnycbad** [comment]
Oh real quick while we're on the topic, i dont think grapevine cape is adding the +30second duration to refresh from blue mage's battery charge. Battery charge is a 5min duration so should be 5:30 with grapevine.  Thanks!

**Comment by z16** [comment]
Added that as well.
