### ISSUE TITLE
LuaCore - Errors need line numbers

### ISSUE THREAD

**Issue by amadeus1171** [Windower/Issues#691]
I wrote the line:

windower.add_to_chat(5, "Auto Fight: " .. tostring(autofight)

The error is that windower.add is missing a closing parentheses.

windower.add_to_chat(5, "Auto Fight: " .. tostring(autofight))

The error lua gave me was:
plugin_name: Lua runtime error: attempt to call a string value

but the error did not include a line number.

**Comment by amadeus1171** [comment]
This error is still driving me nuts. Write several hundred lines of code. Get excited about your masterpiece.  Load your newly modified add-on with all the latest wizbangs and fizwops. Then...
Attempt to call a string value

Call hair club for men because you just pulled all your follicles out. x.x

**Comment by z16** [comment]
This has actually been fixed on the dev version. Did you try it there? Or do you still get that message on the dev branch of Windower?

The reason we haven't pushed it live yet is because some people are crashing on addon load with it and it's nasty to track down why that happens.

**Comment by cairface** [comment]
As far as I can tell, this has been fixed for syntax errors.
