### ISSUE TITLE
Gearcollector no longer functions after update

### ISSUE THREAD

**Issue by amadeus1171** [Windower/Issues#692]
Gearcollector doesn't seem to want to collect gear properly. It behaves as if it's on the marijuana. It starts to collect then kinda stops in a few seconds then outputs the message, "Dude, I'm so high right now..." Well, maybe not the last part.

**Comment by amadeus1171** [comment]
Found the error.  items_armor.xml was cut short for some reason.

**Comment by z16** [comment]
Cut short how? Missing some items? If so, which?

**Comment by amadeus1171** [comment]
It stopped at about line 800.  But I saw that you're refreshing the resources.  That should fix it.
