### ISSUE TITLE
Timers: Enhancing Magic Duration Augments

### ISSUE THREAD

**Issue by rightfront** [Windower/Issues#698]
I have a Ghostfyre cape with +19 enhancing magic effect duration, and if I cast in that and nothing else, timers thinks my buffs should last twice as long as they do (+100%), rather than the +19% it should be.

Meanwhile, I have a Telchine cap with +10 enhancing magic effect duration, and timers doesn't account for that at all.

**Comment by z16** [comment]
Is the augment on Telchine gear the exact same augment as on the Ghostfyre Cape? I.e. `Enh. Mag. eff. dur. +x`? Also, can you augment all Telchine pieces with it or just the cap?

**Comment by rightfront** [comment]
It's the exact same augment name yes, I assume it has the same ID as well but I haven't directly checked.

The augment can occur on every piece of Telchine.  (I just only have the cap).



Date: Wed, 11 Mar 2015 08:39:11 -0700

**Comment by z16** [comment]
Ok thanks, I fixed the *Ghostfyre Cape* and I will implement the changes for *Telchine* gear tomorrow and then push all of that out together.

**Comment by rightfront** [comment]
Great, Thanks.

Date: Wed, 11 Mar 2015 16:20:03 -0700

**Comment by Byrth** [comment]
This occurred months ago, so I'm going to close it now! Please open a new issue if you find more problems!
