### ISSUE TITLE
Organizer

### ISSUE THREAD

**Issue by sebyg666** [Windower/Issues#703]
This is not an issue ^^

I just didnt know where to make a comment to show my appreciation for this addon where i know it would get seen.
This addon is amazaballs, im still having an orgasm at this. thank you for the work you've put into it.
If it was possible (you have probably though of it already) to have the addon also store shit to slips I think id die from over orgasming ^^. This addon is going to save me easily 15 minuits of gearring up everytime i change job. 
Again thankyou. and kind regards to you guys.

**Comment by Byrth** [comment]
No problem! I pushed some more minor changes to organizer-lib just now that should improve its speed.

Just so you know, you can include organizer-lib in any gearswap file and then trigger it to run using "//gs o". It will collect all of the gear that is in your sets table.

Anyway, thanks for the positive feedback and I hope you continue to enjoy it! Let me know if you find any bugs!
