### ISSUE TITLE
Gearswap

### ISSUE THREAD

**Issue by jllove** [Windower/Issues#706]
I have a previous post #705 and I have since been able to load 2 of my 3 characters into the game. However when cast spells, my character puts on the gear i have defined in GS, but doesn't cast any spells.  However, when i unload GS i can cast spells.

**Comment by Byrth** [comment]
Hmm... do you use cancel_spell at some point?

**Comment by Byrth** [comment]
I'm going to guess this started working due to the lack of further responses. Please reopen it if the issue persists.
