### ISSUE TITLE
Windower Crash on DNC moves

### ISSUE THREAD

**Issue by Chanceikin** [Windower/Issues#707]
Any time I do Waltz, Samba or jig - whether from macro or not - windower crashes. "PlayOnline Viewer has stopped working - A problem caused the program to stop working correctly. Windows will close the progrram and notify you if a solution is available."

Why is this happening? Am I the only one?

**Comment by Byrth** [comment]
I am pretty sure this was caused by get ability recasts and should be fixed now. Going to close the issue. Feel free to open another if you still have issues.
