### ISSUE TITLE
Findall error spam

### ISSUE THREAD

**Issue by sebyg666** [Windower/Issues#710]
Found the addon causing the spam of text.
the text reads
Invalid number of method arguments, Expected 2, got 1.
this is repeated over several lines (more than 20).

**Comment by Byrth** [comment]
That indicates it is trying to add to chat a nil. This I'd probably due to outdated item resources. Could you please check your items.lua for any Boii gear?

**Comment by z16** [comment]
Any update on this?

**Comment by sebyg666** [comment]
yes sory for delay, can close this, i looked and for some reason my res folder did not update, so i grabbed latest from here and error went away.

**Comment by z16** [comment]
Alrighty!
