### ISSUE TITLE
Config crashing pol

### ISSUE THREAD

**Issue by KenshiDRK** [Windower/Issues#712]
Config will crash pol when unloaded on login out (using plugin_manager).

**Comment by z16** [comment]
Can you please check if [this](https://googledrive.com/host/0B1-GYvFFRpK6WlVQZnBKbzdycTA/Config.dll) version of Config works for you?

**Comment by KenshiDRK** [comment]
Yes, this one is working, no crash on log out, tried several times. ty^^
