### ISSUE TITLE
Timers - New COR AF3/+1 hands

### ISSUE THREAD

**Issue by KitF** [Windower/Issues#713]
Hey,

Timers needs to be updated to recognize the new Empyrean upgrades. They are a straight duration buff to Phantom Roll (+45 seconds for the NQ and +50 for the +1).

Thanks!

**Comment by Byrth** [comment]
Okay, I was wondering about this. I do not think I implemented it yet because their descriptions were inconsistent with how the armor previously worked.

**Comment by KitF** [comment]
I am just assuming, since ~45 seconds is how much the fully merited non-reforged gloves did. I can do some better testing later today.

**Comment by KitF** [comment]
Well, the NQ reforged is definitely +45 seconds.

**Comment by KitF** [comment]
Confirmed, +45 seconds for NQ, +50 seconds for HQ.

**Comment by KitF** [comment]
Just an FYI, they added a piece of gear (Compensator) that adds 20 seconds, and added 5 more job points.

**Comment by Byrth** [comment]
Job Points should already work and I just added Compensator. The next time Timers is rebuilt it will be added.

In the future, please either open a new issue or re-open the issue when there's something new. We might not see it otherwise.
