### ISSUE TITLE
Timers: Colours order issue with the 06/04/2015 live version update

### ISSUE THREAD

**Issue by Sechs** [Windower/Issues#714]
Arcon you messed up something with the new Timers that went live today
The order of colours with the "Buffs" window is wrong
It correctly goes High > Med > Low for Buffs
But it does the other way around for Buffs
Just casted buff (full duration) uses the "Low" colour (should be High)
Mid is the same
Buff that's about to expire uses the "High" colour (should be Low)
Same happens in the custom window btw, just checked.

**Comment by z16** [comment]
The colors are correct for me. It's possible that you use some custom settings and that the settings parser broke at some point, because of some case-sensitivity issues. Can you check if you have some duplicate settings in your settings XML that only differ by case and which contain different values? For example:
```xml
        <BuffsLowToHigh>false</BuffsLowToHigh>
        <buffsLowToHigh>true</buffsLowToHigh>
```

**Comment by Sechs** [comment]
Checked, but that wasn't the case.
Whatever I write inside the BuffsLowToHigh, either true or false, it keeps doing the same thing.
http://pastebin.com/bMWpyTzb

If you can see any error just lemme know and I'll fix it, but it was working fine before yesterday's update.

**Comment by z16** [comment]
It works fine for me with that file. You have high set to white, medium to green and low to red. Your `BuffsLowToHigh` setting is `true`, meaning it goes from low to high. And sure enough, it starts at red (low), goes through green (mid) to white (high). Is that not what you're experiencing?

**Comment by Sechs** [comment]
Yes, but the same happens if I set "BuffsLowToHigh" to "false".

**Comment by Sechs** [comment]
The behaviour is exactely the same (Red on high, White on low) regardless of what I put into the "BuffsLowToHigh" field. Be it False or True, the result is always the same.
