### ISSUE TITLE
Timers crashing in skirmish/delve

### ISSUE THREAD

**Issue by Cptbirdseye** [Windower/Issues#715]
Every time I enter a skirmish or delve this happens:

17:43:11 > timers encountered a fatal error and must be terminated. Error: Access violation in IncomingChunk method.
17:43:11 > timers - Plugin successfully unloaded.

What happens is the addon then creates a collapsed copy of itself at the top-left corner of the screen and refuses to go away even when loading/unloading/reloading it.

**Comment by hypnotizd** [comment]
This seems to happen to me when I warp to an area and start casting an AoE spell before all of the players have loaded fully. I assume something to do with the list of players the AoE affects.

**Comment by Byrth** [comment]
When you warp to a new area, it is possible to get action packets containing mob index / player IDs for characters that don't exist in memory yet (because you haven't gotten a PC update packet for them). That sounds like the most likely culprit.

**Comment by cairface** [comment]
Another better late than never fix.
