### ISSUE TITLE
LuaCore - Expose player stats

### ISSUE THREAD

**Issue by smd111** [Windower/Issues#717]
please expose player str,agi, etc.

**Comment by trv6** [comment]
Wouldn't the stats only update when you opened the equipment screen (similar to the max_HP event)?

**Comment by IryokuChevalier** [comment]
They update more frequently than that, but it's not real time.

**Comment by Byrth** [comment]
It's slow enough to almost be entirely useless. You get something like one update every 30 seconds unless you cue it by opening the menu.

**Comment by z16** [comment]
Now that I think about it, this is probably also why it has never been exposed yet...

**Comment by smd111** [comment]
that maybe the case but even if it cant keep up with gear changes it would still be nice to have

**Comment by smd111** [comment]
after testing with
```
reg_event.incoming_chunk_id = windower.register_event('incoming chunk', function reg_event.incoming_chunk(id, data, modified, injected, blocked)
    local triggered = false
    if id == 0x061 then
        local packet = packets.parse('incoming', data)
        for i,v in pairs(packet) do
            Player[i] = v
        end
    end
end)
```
i found that its updated on zone change, when you open the equip menu, and 0-2(the smalest time i could get was 1 s because i cant find a way to count ms) seconds after you change gear

**Comment by smd111** [comment]
any news on this
it would be best if windower did this and not addons or plugins because when you reload a plugin it resets every thing

**Comment by z16** [comment]
I don't feel it's a good idea to be exposing it, and the reason was stated before. The packet is not sent when changing gear at all (unless you're in the equipment menu). The only way to reliably keep it up is to send an equipment menu opening packet with every gear change, and even that would introduce a delay big enough to make it pretty much useless for GS users. And outside of GS I hardly even see a benefit for it. That's why I'm very hesitant to implement that feature, especially because the people who actually need it can already use it easily (as little as it may help them) by using the above code.

**Comment by Byrth** [comment]
I'm willing to add this to GearSwap specifically if you want it and say it works. I already added the infrastructure to add arbitrary fields to the user tables, so it should be fine.

Also, Defence should be Defense.

**Comment by smd111** [comment]
@Byrth you can but if gearswap is ever reloaded it will cause it to error unless you (wait 30 seconds after the lats time you opened the status window) open the status window
which is the same issue im having now

this is the reason is better to add it to the windower api so it will always keep it up to date

**Comment by joshk6656** [comment]
Is the last packet function exposed to lua? This would make it doable from LUA instead of the API

**Comment by alphaONE2** [comment]
Please understand that adding anything to the plugin API in hook is a very laborious process, usually resulting in every single plugin needing to be recompiled. I can completely sympathize with @z16's reluctance.

Thankfully in this case I don't think it needs to be added to the plugin API, because, as @joshk6656 hinted, this information is all contained in a single packet. Hook already stores a copy of the last packet received of each type, and exposes a function in the plugin API to retrieve it for just this reason. This can be implemented in LuaCore, or the last packet function can be exposed to Lua and it can be implemented by addons as needed.

**Comment by smd111** [comment]
@alphaONE2 that's actually what the request was to add it to the lua core api

**Comment by alphaONE2** [comment]
I would vote to just add the last packet function to the API and let addons extract the information if they want it. If enough addons need the functionality it can be abstracted into a lib, but I think it's pretty niche.

**Comment by z16** [comment]
@smd111 It's not necessary, addons can do it even if they are reloaded, as @Iryoku pointed out. I'm fine with GearSwap doing it, but like I said, due to its unreliability I don't think the feature belongs in either Hook or LuaCore.

To use it in an addon right now, you can use this:
```lua
require('packets')

packet = packets.parse('incoming', (windower.packets.last_incoming()))
```

**Comment by joshk6656** [comment]
I was looking for that damn function and you posted before me! This should fix your reload issue for sure.

http://dev.windower.net/doku.php?id=lua:api:functions:packets:start#windowerpacketslast_incoming_id

**Comment by smd111** [comment]
so this should do it correct??
```

    local data = windower.packets.last_incoming(0x061)
    if data == nil then
        return
    end
    local packet = packets.parse('incoming', data)
        Player['STR'] = packet['Base STR']
        Player['DEX'] = packet['Base DEX']
        Player['VIT'] = packet['Base VIT']
        Player['AGI'] = packet['Base AGI']
        Player['INT'] = packet['Base INT']
        Player['MND'] = packet['Base MND']
        Player['CHR'] = packet['Base CHR']
        Player['STR+'] = packet['Added STR']
        Player['DEX+'] = packet['Added DEX']
        Player['VIT+'] = packet['Added VIT']
        Player['AGI+'] = packet['Added AGI']
        Player['INT+'] = packet['Added INT']
        Player['MND+'] = packet['Added MND']
        Player['CHR+'] = packet['Added CHR']
        Player['Attack'] = packet['Attack']
        Player['Defence'] = packet['Defence']
        Player['Fire Resistance'] = packet['Fire Resistance']
        Player['Wind Resistance'] = packet['Wind Resistance']
        Player['Lightning Resistance'] = packet['Lightning Resistance']
        Player['Light Resistance'] = packet['Light Resistance']
        Player['Ice Resistance'] = packet['Ice Resistance']
        Player['Earth Resistance'] = packet['Earth Resistance']
        Player['Water Resistance'] = packet['Water Resistance']
        Player['Dark Resistance'] = packet['Dark Resistance']
```

**Comment by joshk6656** [comment]
Yep, on load. Then handle it ongoing as you were before...

nil should only occur if hook has not yet seen the packet.

**Comment by joshk6656** [comment]
You could check which is newer, zone or change packet... im sure change will almost always be newer though?

**Comment by smd111** [comment]
ok thanks
well if @Byrth would like to add it to gearswap proper he can but i will verify it works first
