### ISSUE TITLE
Random pol crashes

### ISSUE THREAD

**Issue by omgitskae** [Windower/Issues#718]
They seem completely random. I can leave my game idle overnight and it will crash sometime between 2 and 5 hours after being logged in, or I can be out exping or doing other content, they're completely random but usually happen after a few hours. I have seen them happen much sooner or later though.

Here's the generated .dmp file from the most recent one.

https://www.dropbox.com/s/274j686rx62ommz/pol.exe.29188.dmp?dl=0

Edit: Thought it might be useful to add that this isn't like some kind of crash that gives me a Windows error or anything. The game just stops responding randomly and I get the message for that. This is the Windows event error text for it, if it's helpful:

Faulting application name: pol.exe, version: 1.18.13.0, time stamp: 0x4e3bcddc
Faulting module name: KERNELBASE.dll, version: 6.3.9600.17415, time stamp: 0x54504ade
Exception code: 0x40000015
Fault offset: 0x00014598
Faulting process id: 0x7204
Faulting application start time: 0x01d0791f39f1119b
Faulting application path: F:\Program Files (x86)\PlayOnline\SquareEnix\PlayOnlineViewer\pol.exe
Faulting module path: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
Report Id: 23b0d0aa-e52b-11e4-bed1-bc5ff473a362
Faulting package full name: 
Faulting package-relative application ID: 

Edit2: It doesn't seem like anyone sees this but I'd really like some help (I can't seem to register on the Windower forums), I've been googling around and trying to find out what could be causing this but I'm not very smart with this stuff. I ran a manual dump and this is what showed when the crash happened:

"(2780.28a8): C++ EH exception - code e06d7363 (first chance)
8:47:12 PM| [28a8] ffxidb: Map: Created succesfully. Setting "render" state to true.
(2780.280c): Unknown exception - code 40000015 (first chance)
(2780.2414): Unknown exception - code 40000015 (first chance)
(2780.289c): Unknown exception - code 40000015 (first chance)
(2780.289c): Unknown exception - code 40000015 (!!! second chance !!!)
**\* WARNING: Unable to verify checksum for Hook.dll
**\* ERROR: Symbol file could not be found.  Defaulted to export symbols for Hook.dll - 
KERNELBASE!RaiseException+0x48:
76b34598 8b4c2454        mov     ecx,dword ptr [esp+54h] ss:002b:07a3fe7c=3dfe08aa
0:032:x86> g
WARNING: Continuing a non-continuable exception
(2780.7c0): Unknown exception - code 40000015 (first chance)
(2780.7c0): Unknown exception - code 40000015 (!!! second chance !!!)
**\* ERROR: Symbol file could not be found.  Defaulted to export symbols for Guildwork.dll - 
KERNELBASE!RaiseException+0x48:
76b34598 8b4c2454        mov     ecx,dword ptr [esp+54h] ss:002b:23fffe84=19a208b2"

Any help at all would be GREATLY appreciated. Also, I do not think this is Guildwork causing it since I've experienced the crash with Guildwork toggled off in the loader. I have tried deleting hook.dll and letting Windower redownload it but that did not work.

**Comment by Byrth** [comment]
I find that problems like this are frequently caused by addons taking up crazy amounts of memory or corrupting the stack.

I'm going to assume you resolved this issue and close the report, but feel free to reopen it or make a new one if it's not resolved.
