### ISSUE TITLE
Visual C++ Runtime Library crash

### ISSUE THREAD

**Issue by Nezkeys** [Windower/Issues#719]
Just experienced this crash after zoning into my mog house and the error was apparently to do with "Visual C++ Runtime Library". This is totally random. I have changed nothing within my windower files manually, and I have never even experienced this error/crash in 3 years of playing. I logged in again as normal and a few moments after being inside my mog house I get the same crash again. I am not sure if this is directly related to the mog house only (Unfortunately that is where I am logged) or something else. I would appreciate any help regarding this error asap please

**Comment by IryokuChevalier** [comment]
Does this happen without Windower? If it only happens with Windower loaded, please download and reinstall the [Visual C++ 2008 Redistributable](http://www.microsoft.com/en-us/download/details.aspx?id=29) and the [Visual C++ 2008 SP1 Redistributable](http://www.microsoft.com/en-us/download/details.aspx?id=5582) from Microsoft.

If you still experience a crash after reinstalling these components, we will need a crash dump.

**Comment by Nezkeys** [comment]
Well I will try that if it happens again. For now it seems to have stopped doing it. I find it odd that it just happened out of nowhere and then all of a sudden stopped doing it (after several login attempts I may add). Something that just came to my attention though which I was unaware of though is that I am missing several system dll files which I am thinking may be the cause of all my problems with windower recently. Framedyn.dll and api-ms-win-core-synch-1-2-0.dll were mentioned during a failed driver update I just tried. However when I google fixes for these missing files its not as simple as just downloading the necessary dll file as they all warn you not to download them lol. I have no idea why they are even missing. I dont even think i have visual c++ 2008 anyway only 2013 iirc.

**Comment by Nifim** [comment]
Not enough information, if issue has persisted please come to our discord for support.
