### ISSUE TITLE
Cannot register on forums/account/dev/wiki.windower.net, Apache 404

### ISSUE THREAD

**Issue by Morath86** [Windower/Issues#720]
When trying to register for a new account, I'm getting redirected to [here](http://account.windower.net/pwm/public/NewUser):

# HTTP Status 404 - /pwm/public/NewUser
**type:** Status report
**message:** /pwm/public/NewUser
**description:** The requested resource (/pwm/public/NewUser) is not available.
##### Apache Tomcat/7.0.26

**Comment by IryokuChevalier** [comment]
Thanks for reporting this, @aureus1 is looking into it.

**Comment by IryokuChevalier** [comment]
This should be fixed now.
