### ISSUE TITLE
Can't set prefrences for different resolutions on Timers Plugin

### ISSUE THREAD

**Issue by Nyruul** [Windower/Issues#721]
Can't seem to get it to work.  I've tried specifying only one character and after reloading it edits and deletes that character tags. If I do all 3 of my characters it will edit out all of them and set the default positions(I'm guessing its the default.) I've also tried including every setting within each character and that also caused the file to default.

```
<!-- 1600x900 -->
<Nyruul>
        <RecastX>850</RecastX>
        <RecastY>600</RecastY>
        <BuffsX>1030</BuffsX>
        <BuffsY>600</BuffsY>
        <CustomX>1210</CustomX>
        <CustomY>600</CustomY>
    </Nyruul>
<!-- 1366x768 -->
<Nyruru>
	<RecastX>650</RecastX>
        <RecastY>500</RecastY>
        <BuffsX>830</BuffsX>
        <BuffsY>500</BuffsY>
        <CustomX>1010</CustomX>
        <CustomY>500</CustomY>
    </Nyruru>
```

This kind of correlates and I have always wished there was a monitor selection setting for each profile and maybe isolate the profiles active addons/plugins rather than having an addon for it. Separate plugin/addon configs and init/etc for profiles. I guess it's more of a convenience thing that isn't worth making the effort for.

**Comment by Byrth** [comment]
The issue here is probably that Timers saves a copy of the settings when it exits. You need to unload Timers on all accounts and then reload it after editing. Going to close this as it has been months since the original post and I'm pretty confident that is the solution.
