### ISSUE TITLE
Gearswap perp set issue

### ISSUE THREAD

**Issue by rookie6256** [Windower/Issues#722]
Since the update last night my gearswap is no longer able to recognize whenever my pet is out and swap to the designated perp set.  How would i go about fixing this issue?

**Comment by z16** [comment]
You need to report it to us on our [issue tracker](https://github.com/Windower/Issues/issues). We'll take it from there :)

**Comment by rookie6256** [comment]
Isn't this the Issue Tracker? Do i need to create a new issue ticket and or upload the .lua file im using?

**Comment by IryokuChevalier** [comment]
@z16 is just saying (in a very round about way) that opening this ticket is how you go about fixing it. 

However, it's much more helpful if you provide as much detail as you can. "It doesn't work" is not very useful. A detailed description of the problem, including the steps required, and any files needed to reproduce the problem, make it much easier to locate, diagnose and fix the bug. A bug that appears easy to fix is more likely to get worked on, and will get fixed faster. More information is rarely a bad thing when dealing with this kind of thing.

**Comment by z16** [comment]
I honestly don't know *what* I was saying. My reply makes no sense at all. Ignore!

I think I thought that you posted on the wrong issue tracker, but you didn't... I had a lot of tabs open because people spammed error reports after this update, I probably got something mixed up!

**Comment by rookie6256** [comment]
Looks like the issue has been resolved perp sets are working once again thanks!
