### ISSUE TITLE
Status timer is realy messed up

### ISSUE THREAD

**Issue by smd111** [Windower/Issues#723]
Statustimer plugin is really messed up

**Comment by smd111** [comment]
im not sure why you closed this 
Statustimer plugin is giving false buff timers on screen plus its not going away when you unload the plugin

**Comment by z16** [comment]
"Really messed up" is not really a great bug report and doesn't help us to find the issues. What you said now is more helpful. There is a lot wrong right now because of a bug in hook, I'll look into it when I get home today.

**Comment by smd111** [comment]
oh sorry about that i was realy tired when i made that post and i know that lots are messed up with the new update

**Comment by z16** [comment]
Can you see if it works now?

**Comment by smd111** [comment]
looks good now thx
