### ISSUE TITLE
timers crashing

### ISSUE THREAD

**Issue by jebasffxi** [Windower/Issues#724]
"timers encountered a fatal error and must be terminated.  Error: Access violation in incomingChunk method."
"timers - Plugin successfully unloaded."
Happens when a bard song finishes casting.
Doesn't happen when casting white & black magic or job abilities.
No gearswap or ingame gearsets being used.

**Comment by z16** [comment]
Might be fixed, can you check again?

**Comment by jebasffxi** [comment]
fixed.
works fine now.
thanks a lot.
