### ISSUE TITLE
Small Timers issues post update

### ISSUE THREAD

**Issue by Sechs** [Windower/Issues#729]
*Debuff Display*
This happened several other times post patch in the past as well.
Timers currently displays debuffs (DNC Steps, Gambit, Rayke, Elegy, Requiem, Finale etc) in the Buff window. Most of these timers are wrong too, they multiply each time used instead of stacking (steps, songs, etc) and there is no way to disable it. This practically fucks up the buff window, pushing buffs beyond the threshold of the buff number you set up in the settings.xml.

*Missing buffs*
A couple of patches ago, Timers implemented SMN Blood Pact Ward and started tracking their duration.
Granted that now those durations would probably be wrong (SE recently increased all of them), they're still useful. Atm Timers produces no timer at all for any Blood Pact Ward used.

**Comment by Sechs** [comment]
Bump

**Comment by Byrth** [comment]
I assume these problems have been fixed in the last three months. If not, please reopen the issue.
