### ISSUE TITLE
Timers - Chocobo Jig wrong duration

### ISSUE THREAD

**Issue by Sechs** [Windower/Issues#735]
Currently Chocobo Jig and Chocobo Jig II used with Maxixi Toe Shoes +1 and Horos legs +1 display ~35 seconds more than they should on the timers buff window.

That is: Timers thinks they are going to last ~35 seconds more than they actually do.

**Comment by Byrth** [comment]
Same as BMN, I recompiled Timers yesterday probably to address this issue. Going to close the issue.
