### ISSUE TITLE
Blinkmenot - Broken "Others" after patch

### ISSUE THREAD

**Issue by Sechs** [Windower/Issues#736]
Since last patch Blinkmenot fails at recognizing people as part of your Party or Alliance.
It will keep making them blink unless you activate "Others", at which point it will work for everybody whether they're part of your party/alliance or not.

**Comment by Byrth** [comment]
I believe that I recompiled this plugin yesterday and thus it is likely fixed. Going to close the issue. Please reopen it if it is not.
