### ISSUE TITLE
Random crashes - mysterious source of the issue!

### ISSUE THREAD

**Issue by Sechs** [Windower/Issues#737]
For the last few weeks I've been having random crashes. They seem to be happening more often when I'm dualboxing, but they do happen even when I don't.
Odd thing, they seem to happen even when I'm idle doing absolutely nothing and just looking at the screen.

I uploaded a full memory crash dump. Can anybody at least help me understand what is causing it?

https://drive.google.com/file/d/0BxZYiqQngWFqODhmWlo5NE41Q00/view?usp=sharing

**Comment by Sechs** [comment]
Anybody managed to get a chance to check those crashdumps? It keeps happening, and it keeps being random. I.e. sometimes you're just in town standing there reading shouts/yells, and the second after you get a crash

**Comment by Byrth** [comment]
You've kept playing, so I assume these were resolved.

Please reopen this issue or open a new issue if not.
