### ISSUE TITLE
Continuous freezes and C++ runtime errors (dump)

### ISSUE THREAD

**Issue by Nyruul** [Windower/Issues#744]
Seems to mostly happen when there is a lot of animation going on at once but has happened in mog house also. It hasn't happened on vanilla client and I have reinstalled windower to try and resolve it. Also reinstalled C++ to try to fix it.

Here's the crash dump.

**Comment by z16** [comment]
This crash dump cannot be read. You created a 64-bit crash dump. Either create a 32-bit crash dump or a 64-bit crash dump with full heap information, otherwise we cannot use this.

**Comment by Nyruul** [comment]
Ok, took me a bit to find out how to get an x86 dump on the x64 windbg(can't manage to just get the 32bit version.) When I made a dump the file came out very small and since I've put in the x86 command I can't attach windbg to windower anymore. I noticed I have 4 dump files in the windower dumps folder so I put them on in the drive folder with the unusually small dump I got. Not sure if they will help. I am having trouble getting the DumpSetup.exe to make dumps, I think it is because usually FFXI hangs instead of completely crashing. Anyways here's a new link.

http://1drv.ms/1KBUexE

**Comment by z16** [comment]
There are quite a few files in there, which one is the correct version?

Also, [here](https://github.com/Windower/Issues/wiki/Enabling-automatic-crash-dumps) is a guide for setting up crash dumps very easily. You should follow that, then you don't need to mess around with WinDbg anymore.

**Comment by Nyruul** [comment]
The one that is named ffxidump2 is the Windbg dump I made.

The others must have been made from the file giving in that link. Like I said, the automatic crash dump that is suggested in that link is not making dumps, or at least not every time.

Problem seems to be that windower mostly ends up freezing/hanging so maybe that's why it is not catching them. 

But the extra 4 in there I can almost guarantee are dumps involved with the same issue.

**Comment by Byrth** [comment]
Windower's next minor version update (v4.3) was released today on -dev. To try it out, duplicate your entire Windower directory, then download http://update.windower.net/dev/Windower.exe , replace your existing Windower.exe, and log in. I think there's a pretty good chance that it solves your problem, or at least changes it substantially. You can read more here: #877

I am going to close this now. Please let us know in that thread (and reference this thread) if you still have crash issues.
