### ISSUE TITLE
StatusTimer and Cancel inside Salvage

### ISSUE THREAD

**Issue by ibm2431** [Windower/Issues#745]
**StatusTimer**
I've come across a weird bug with StatusTimer and Cancel inside Salvage after the June 2015 update.

After removing Pathos, there's now-frozen ghost timers where the icons used to be. Gaining buffs/statuses after the fact (like Sneak/Invisible) pushes the location of these phantoms timers away, while displaying misplaced (and incorrect) timers for the new buffs. Removing Sneak/Invis (manually, see Cancel below) causes some of the timers to disappear (I suspect those tied with Snea/Invis), but not the ones which I suspect originally belonged to the removed Pathos.

Right after clearing a set of Pathos from lamp:
![timers1](https://cloud.githubusercontent.com/assets/13112942/8424231/46c43216-1eac-11e5-9835-1d6b37e0c349.jpg)

After using Spectral Jig:
![timers2](https://cloud.githubusercontent.com/assets/13112942/8424228/3e6c743e-1eac-11e5-95e5-2750b72288e4.jpg)

After attacking a mob and losing Sneak/Invis
![timers3](https://cloud.githubusercontent.com/assets/13112942/8424236/542659b6-1eac-11e5-92b0-de1a7453c7a9.jpg)

**Cancel**

During all this, Cancel simply doesn't work, either through auto-canceling through Gearswap (Sneak while using Spectral Jig), or through the full command (keybind of 'cancel Invisible').

I'll note that I've only seen this happen while inside Salvage. Both work as they always have anywhere else (that I've been recently, anyway).

**Comment by z16** [comment]
Looks like they adjusted buffs in some fashion. I can examine it later today. But for the record, this is the StatusTimer plugin, not Timers.

**Comment by ibm2431** [comment]
So it is. >.>

Sorry about that. I run both and sometimes forget they're separate. I'll edit the Issue to correct.

**Comment by ibm2431** [comment]
I thought I could implement a naive solution for Cancel (which is what I'm truly concerned with) - maybe the buff IDs were different inside Salvage and I could modify Cancel to use the "new" IDs for Invis/Sneak if we're in Salvage, right? But after some cursory poking around, I don't think this an issue with Cancel (and StatusTimer) itself, but some core issue with buff gain/lose events.

Windower doesn't seem to be firing a buff gain event when I apply Sneak/Invis (inside Salvage) through Spectral Jig, and doesn't get a buff lose event when I manually cancel them. The events fired outside Salvage, gain fired when I got pathos at the start, and lose fired when I removed some from the lamp. Grabbing get_player().buffs and printing each item in the table only prints the ID for a single pathos (259, Encumbrance). Both Cancel (and ffxi.cancel_buff) probably "aren't working" simply because they check to see if the buff exists before sending the outgoing packet.

It gets a little more interesting. At the moment, I have both Encumbrance and Debilitation. But as before, the buffs table only contains Encumbrance. As I was getting lamp buffs prior to trying Spectral Jig, a lose buff event fired for 263 - Debilitation, which may tie into this. I'll admit I don't know exactly how Windower handles buffs/gain/lose, but I venture a guess that removing a single stat-down pathos probably shouldn't qualify as losing the entire buff. I'll also note that I got both HP and CHR from the lamp - how does Windower handle a buff loss event (from server) when as far as its concerned, you don't have the buff (removing CHR down after HP down)?

Recalling that in the last update, FFXI's action packets were changed to include a lot of "empty data", and that SE's announced that for the next update player's will be able to see others' buffs, I'm guessing the currently "empty" data is where SE intends to put in buffs IDs. I'm not experienced enough to examine/play with the packets myself, but is it possible that they're already using this in some capacity for Salvage pathos? That when a sub-type pathos (Debiliation of HP flavor) is lost, it sends a buff loss packet (as before), but now with the specific type in the "extra" space? Assuming that Windower is simply ignoring the "extra" data (at the moment), would it see the buff loss packet, check the master/family ID, and just register the entire buff family as lost?

I'll openly admit that this is wild speculation from my limited view. I'll do another test later with some Prism Powder/Sneak Oil prior to interacting with the lamp. And take better notes when I do interact with the lamp.

**Comment by ibm2431** [comment]
Alright, confirmed that StatusTimer and Cancel are working "as they should be", the real issue lies somewhere in core breaking when removing pathos through the lamp. Removing a single pathos (in the example below, just Sub Job restriction) causes Windower to fire a lose buff event for *all* pathos except for 259. At this point it doesn't properly register gain buff events. This effects Cancel for Sneak, Gearswap for Steps (and most likely Shadows), and probably other addons.

I tossed together a testing .lua to look at this. It attached a simple print buff ID function to gain/lose buff events (as fired by Windower), a print param1 function as a listener for incoming chunk 0x29 (action message packet), a command to print the current contents of windower.ffxi.get_player().buffs, and a command to manually inject an outgoing cancel packet *without* checking against the player's current buffs provided by Windower.

Results:
**Standing outside AR II. (Control tests)**
Use Spectral Jig.
Windower events: gain buff 69, gain buff 71
//test buffs, result: {69, 71}
Manually cancel invisible
Incoming chunk event: id: 41, param1: 69
Windower event: lose buff 69
//cancel sneak
Incoming chunk event: id: 41, param1: 71
Windower event: lose buff 71
//test buffs, result: {}
**Enter Salvage, receive pathos**
Windower events: gain buffs 259, 260, 261, 262, 263
//test buffs, result: {259, 260, 261, 262, 263}
Use Silent Oil
Windower event: gain buff 71
//test buffs, result: {259, 260, 261, 262, 263, 71}
//cancel sneak
Incoming chunk event: id: 41, param1: 71
Windower event: lose buff 71
**Talk to lamp, remove Support Job restriction
Windower events: lose buffs 260, 261, 262, 263
//test buffs, result: {259}
Use Silent Oil
No buff gain event
//test buffs, result: {259}
//cancel sneak (nothing happens, as expected)
//test cancelsneak (hard injection of outgoing cancel packet without checks - works)
Incoming chunk event: id: 41, param1: 71
No buff lose event**
Use Fireflies to exit, new zone loads
Windower event: lose buff 259  (All StatusTimers clear at this point)
Use Silent Oil
Windower event: gain buff 71
//cancel sneak (now works again)
Incoming chunk event: id: 41, param1: 71
Windower event: lose buff 71
