### ISSUE TITLE
Timers Problem On Corsair

### ISSUE THREAD

**Issue by lewyo** [Windower/Issues#746]
It's been happening for a few months now so i know the last update did not break it but as you can see in the picture i posted when ever i do any rolls on Corsair the timers it's giving me for each roll are over 15 min, It's like it's doubleing the time up and i don't know how it's happening, i know it was working fine a few months back and i have not changed or added anything into the Cor gearswap lua i use but here is my lua for referance just incase.    http://pastebin.com/SsTKQwvv 

![20150705_085501](https://cloud.githubusercontent.com/assets/4061947/8510830/bc307d88-22f4-11e5-9515-a70995638f25.jpg)

**Comment by lewyo** [comment]
After playing around with my lua i have finally tracked down the problem and it has to do with the  phantom roll duration buff that the Navarch's gants +2 give it should only give you a 10% duration buff to all rolls but it's giving 100% making the timers for each roll over 15 min. I don't know if the same problem is on the upgraded versions but i guess it would be worth checking them out .

**Comment by Byrth** [comment]
Okay, I've fixed this and it will go live whenever Timers is rebuilt and pushed next. Thanks!
