### ISSUE TITLE
Plugin: Timers (icons)

### ISSUE THREAD

**Issue by joso33** [Windower/Issues#749]
Lot of the newer recast of spells/trust got a '?' icon next to it. Is it possible to change these?

**Comment by finnigantime** [comment]
I expect particular examples will help track this down. Is this just for new spells? Which ones have you seen this problem with?

**Comment by joso33** [comment]
Top of my head for example blue magic: Erratic Flutter (also the recently added spells) and ALL trust magics.

**Comment by Byrth** [comment]
I believe this has been fixed as of this past update.

Please open another issue if you have problems!
