### ISSUE TITLE
luacore crash

### ISSUE THREAD

**Issue by smd111** [Windower/Issues#750]
not sure why it crashed but i was trying to test to see if the pol anti blink was what was causing me to crash at random times so i turned it off and this is what happened

my theory was for this:http://forums.windower.net/index.php?/topic/841-random-crashing-windbg-report-included/
is because it started after that added the pol anti-blinker so i turned it off to see if it still crashed and it did but not in the same way

dump:http://www.filedropper.com/polexe4708

**Comment by Byrth** [comment]
Again, I assume this was resolved because you've kept playing.

Please reopen it or make a new issue if it wasn't.
