### ISSUE TITLE
pol crash

### ISSUE THREAD

**Issue by yamasi** [Windower/Issues#753]
as soon as i hit the last ok and the game starts to load, for some reason i get a message saying pol viewer has stoped working. i just tried playing it without windowers and it runs fine. is anyone else having this problem? is it because i recently upgraded to windows 10?

**Comment by shivaeyes** [comment]
Hello, I have the same problem. I'm on Windows 8.1 :x

**Comment by Chaoticpotato05** [comment]
Also having this issue, I upgraded to windows 10 and was running FFXI using windower just fine until i did the quest "Breaking the Ice" which I know gives issues for windower, and it ended up black screening my game and after that, I can no longer get the game to load in windower. I've uninstalled and reinstalled everything, cleared the registry, and I cannot get windower to work again and just noting the game does load without windower.

**Comment by Byrth** [comment]
Windower's next minor version update (v4.3) was released today on -dev. To try it out, duplicate your entire Windower directory, then download http://update.windower.net/dev/Windower.exe , replace your existing Windower.exe, and log in. I think there's a pretty good chance that it solves your problem, or at least changes it substantially. You can read more here: #876

I am going to close this now. Please let us know in that thread (and reference this thread) if you still have crash issues.
