### ISSUE TITLE
windows 8.1 launcher problem

### ISSUE THREAD

**Issue by cjewell77** [Windower/Issues#756]
Ok any help is appreciated. ive searched the forums before posting. When I launch windower " as admin " it does the era loader two lines in the window then about 30 seconds later says closing. Not really so much an error as it kind of looks like a compatibility issue. Also launching the pol manually does the same.  Now I did the tutorial on you tube if you look up final fantasy 11 private server. Downloaded his torrents etc. I am tech savy been so for about 1 5years. Please let me know what you think. My email is tankerdrver@gmail.com

**Comment by alphaONE2** [comment]
If it's doing it with without Windower in the mix then it's not a Windower bug, and this is not the right place to ask for support.
