### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by keithguinn13** [Windower/Issues#760]
I've noticed anytime you do anything to open or change something outside of windower it crashes. Just like normally if I have my monitor hooked up and I switch it back to my laptop POL will crash. Also sometimes pol crashes at startup right when it gets to the story intro and I have to restart again to get it to work.

**Comment by z16** [comment]
Anything that changes the screen settings (like resolution or output location) will always crash POL and there's nothing we can do about it. The other problem you describe sounds very generic and we will need much more detailed issues, including a [https://github.com/Windower/Issues/wiki/Enabling-automatic-crash-dumps](crash dump) before we can help you.
