### ISSUE TITLE
POL crashes when launched by Windower v4

### ISSUE THREAD

**Issue by Shuudoushi** [Windower/Issues#761]
The crash happens just after pressing 'launch' in windower and it closes. POL also seems to crash twice for some odd reason, both dumps are included below.

http://www.mediafire.com/download/up02v5qqoikaiw7/pol.exe.27600.dmp
http://www.mediafire.com/download/3nk6n665odj65sd/pol.exe%281%29.27600.dmp

Had to blow the dust off of that account...

**Comment by Byrth** [comment]
Does your POL crash if launched directly as well?

**Comment by Shuudoushi** [comment]
Negative, only when launched by windower.

**Comment by Byrth** [comment]
Windower's next minor version update (v4.3) was released today on -dev. To try it out, duplicate your entire Windower directory, then download http://update.windower.net/dev/Windower.exe , replace your existing Windower.exe, and log in. I think there's a pretty good chance that it solves your problem, or at least changes it substantially. You can read more here: #877

I am going to close this now. Please let us know in that thread (and reference this thread) if you still have crash issues.
