### ISSUE TITLE
[Timers] - Duration of Stratagems lowered from 48 to 33

### ISSUE THREAD

**Issue by Sechs** [Windower/Issues#762]
If a SCH reaches the 550 Job Points gift, their Stratagems Recast time will go down from 48 seconds (as it is now) to 33 seconds.
Can Timers be updated to reflect this change please?
It's unusable if you have the 550 gift :'(

**Comment by z16** [comment]
Will do! Working on a number of changes, but I might be able to get to it later today.

**Comment by Sechs** [comment]
Arcon did you get a chance to further develop this fix for Timers? Do you need help with betatesting or anything?

**Comment by z16** [comment]
Nope, all I need is time :( This weekend should be better

**Comment by Sechs** [comment]
Allright, I'll just keep waiting then and cheer you up from the background! :D

**Comment by Sechs** [comment]
I apologize for bumping this up and annoying poor Arcon, but any update on this upcoming patch? :D

**Comment by z16** [comment]
I forgot to mention my PC has been borked for a while, but I'll get a new one this Thursday. I've been working so much that I didn't even have time to buy a new one :\

This weekend for sure. Super pinky promise.

**Comment by Sechs** [comment]
I feel guilty for putting so much pressure on you. You're working for free, it's not like you're working for us under a contract and we're paying you.
Still, it's a bit annoying playing SCH without a working stratagem counter (once you get used to it).

Thanks once more for all the support Arcon :)

**Comment by Byrth** [comment]
This should be fixed on -dev now.

**Comment by Byrth** [comment]
Going to close this. Please reopen it or post a new issue if it doesn't work somehow.
