### ISSUE TITLE
[Timers] Increased duration of SMN Blood Pact Ward in a recent patch

### ISSUE THREAD

**Issue by Sechs** [Windower/Issues#763]
Blood Pact Ward have a fixed duration (mapped in resources). This duration can be increased according to the amount of SMN skill the moment these BPs go off.
Timers already track that.
Thing is there used to be a cap of 500 skill, meaning any skill above 500 didn't increase the duration further.
This cap was removed a few patches ago and atm there is no known cap.

Timers should be updated in light of this, because currently he still thinks SMN skill caps at 500 for the duration bonus.
Further information here:
https://www.bg-wiki.com/index.php?title=Blood_Pact:_Ward

**Comment by z16** [comment]
It's actually not that simple, we still have no reliable (or easy) way to determine the skill at any point accurately. The way Timers does it often leads to incorrect results. I can remove the skill cap it currently imposes (and will do so, given the new information), but it will still not work right if gear is swapped quickly before casting.

**Comment by Sechs** [comment]
Yeah Arcon, but that won't be any worse than it's always been, and I think we can all accept that degree of approximation. Just unlocking the cap will be very welcome ;)

**Comment by Sechs** [comment]
Was this ever implemented? Timers' way of tracking SMN buff duration, even if not super-accurate, was actually useful.
Just removing the cap on duration would've been good enough even with teh same level of accuracy.

**Comment by Nifim** [comment]
Chiaia did this 2 yeas ago! good job Chiaia!
