### ISSUE TITLE
[FFXIDB] Requesting zoom level as a zone-specific preference

### ISSUE THREAD

**Issue by Kainsin** [Windower/Issues#765]
Would it be possible to save the zoom settings for the FFXIDB mini-map as a zone-specific preference rather than using the same zoom level for each map? Thanks!

**Comment by Byrth** [comment]
Anything is possible, but with the way the current settings are this is unlikely to happen on v4. I'm leaving it open as a record of the feature request for when we move to v5.

**Comment by Nifim** [comment]
This has be has been implemented
