### ISSUE TITLE
windower.ffxi.get_player() buffs tables not correct in salvage

### ISSUE THREAD

**Issue by Petewilmer** [Windower/Issues#766]
In salvage the buffs table returned by windower.ffxi.get_player() only contains 1 value, 259 (which is encumbrance) and doesn't contain any other values despite many other buffs active. For instance if I cast light arts, reraise, protect and shell, windower.ffxi.get_player() still doesn't contain anything other than encumbrance (or any of the other pathos effects active).

**Comment by Petewilmer** [comment]
When I completely removed encumbrance, windower.ffxi.get_player() stopped returning any buffs at all.

**Comment by Byrth** [comment]
Packet in Salvage:
```  XX  00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F```
```  00  37 2E A5 01 03 FF FF FF 07 28 29 25 2B FD FF FF ```
```  10  FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF ```
```  20  FF FF FF FF 82 D7 05 00 08 0D 56 02 32 00 64 00 ```
```  30  00 52 FB 38 00 00 20 00 00 00 00 00 20 A0 03 00 ```
```  40  8A 07 E4 19 00 00 00 00 00 00 00 00 01 01 00 00 ```
```  50  00 00 00 00 00 00 00 00 00 03 00 00 ```

I had Encumberance (0x103), Nothing (0xFF), Nothing (0xFF), Nothing (0xFF), Debilitation (0x107), Protect (0x28), Shell (0x29), Stoneskin (0x25), Refresh (0x2B)

You basically have to keep parsing the buff array to the end instead of returning when you hit the first 0xFF.

**Comment by teschnei** [comment]
i wonder if the nothings are placeholders for the other salvage debuffs..

**Comment by Byrth** [comment]
They are, and this is fixed now.
