### ISSUE TITLE
Bidder - Three-eyed fish cannot be bought

### ISSUE THREAD

**Issue by Byrth** [Windower/Issues#768]
Every time I try to buy three-eyed fish through the command line, it tells me the AH is closed and refuses my bid.

**Comment by pcdavid52a** [comment]
I believe Gugru Tuna is also subjected to this bug.

**Comment by Byrth** [comment]
This is likely because there are two Three-eyed Fish (and Gugru Tuna) in the .dats and it's using the wrong ID.

**Comment by Byrth** [comment]
I confirmed today that the string->ID search is indeed returning an unactionable item. Fish names are ambiguous, as there are two copies of each in the .dats.

In an ideal world, Bidder would check for the "Actionable" flag in the resources. However, its current lookup function is in WindowerPlugin, which disposes of most of the resources for overhead reasons. It would be more trouble to fix than it's worth, so I'm not going to do it!

**Comment by Byrth** [comment]
I solved this by creating an addon with Bidder's functionality, but have no official way to distribute it. Going to close the issue anyway.
