### ISSUE TITLE
Follow and Gearswap

### ISSUE THREAD

**Issue by TheGodchild** [Windower/Issues#770]
After the September update the /follow command breaks after any kind of gear swap.  Blinkmenot is still working as intended but my alts still break follow after any gear switch.  /lockstyle does not prevent the break nor does locking onto the target and enabling autorun.  Anyone got any ideas?

**Comment by Byrth** [comment]
This was likely caused by BMN/DressUp's weirdness, as I have not been able to replicate it. Given that both are fixed now, I'm going to close this issue. Please open a new issue or reopen this issue if the problem persists.
