### ISSUE TITLE
ohshi

### ISSUE THREAD

**Issue by zaxtiss** [Windower/Issues#772]
Was wondering if it would be possible to make the add on ohshi work in vagary to alert  you to the change in the bosses weakness cuz we all know ppl don't see it most of the time

**Comment by nitrous24** [comment]
Honestly i've done nothing with the addon in so long. But i have no clue what bosses you're talking about, nor do i know if there's a chat about a weakness change. If you can go into detail about what you mean i can see what i can do.

**Comment by zaxtiss** [comment]
in vagary the NMS that drop the mats to 119 empy legs and body  both change
weakness  during the fights or they can atleast. and they say something
like "lighthing is the key to victory"  you know they said something cuz
you see that you  proc'd the change muchb like in voidwatch or in aby

**Comment by nitrous24** [comment]
if there's something in chat i can definately add it. Just ge tme a list of
all the things to check for, i don't do vagary so i have no way to find it
out really.

**Comment by nitrous24** [comment]
oh and it would be really nice to have exact strings for it.. as it's much
easier to add when i know exactly what to look for.

**Comment by zaxtiss** [comment]
yeh  np i should have most of the proc notice's on my onevent chat thing i
was trying to make you have an IM ? email seams a bit slow would be alot
easier  on some form of chat

**Comment by zaxtiss** [comment]
Ice is the key to victory!
 Fire is the key to victory
 Lightning is the key to victory
 Wind is the key to victory!
Water is the key to victory!
 Ice is the key to victory!
 those should be them

**Comment by nitrous24** [comment]
ok, i added this to the dev branch. If you want to try it out on live
you'll need to get the files on the github. All i changed was ohshi.lua and
text_handling.lua

can get them from here (i think you can at least):
https://github.com/Windower/Lua/tree/dev/addons/ohShi

**Comment by Byrth** [comment]
I believe this has been fixed and pushed live. Going to close it now. Please reopen the issue if it persists.
