### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Punisher316** [Windower/Issues#774]
Not sure what plugin or add-on causing this,but every time i make a purchase from a bazaar game crashes.

**Comment by nitrous24** [comment]
You'll need to give a lot more information than this. As there is no possible way to know what addons/plugins you are currently running. And i'm sure there's other info that they would love to have.

You could also provide a crash dump. The way you do that is here: https://github.com/Windower/Issues/wiki/Enabling-automatic-crash-dumps

**Comment by Punisher316** [comment]
well I turned off blink me not and now everything is running fine. so apparently it was the Blink me not plugin. Sorry for being so Vague.

**Comment by Byrth** [comment]
BMN has been fixed, so you can go back to using it. Please let us know if the problem persists by reopening this issue or opening a new one.
