### ISSUE TITLE
Mighty Guard (Other Unbridled Learning spells for BLU also)

### ISSUE THREAD

**Issue by Schliematt** [Windower/Issues#776]
In September we got 4 new spells for blu. All are used under unbridled learning. I dunno bout the other 3 as they are learned in Vagary but Mighty Guard is an awesome spell and Id like to use my relic feet when diffusion is up (It extends the duration or w/e).
When using gearswap with showswaps and debug mode on:

Unable to execute command. Blue magic must be set to cast that spell (Mighty Guard)
Entering filtered_action
Entering aftercast
Entering buff_change
Entering buff_change
Entering buff_change

It shows three buff changes because of diffusion/unbridled learning wearing and mighty guard buff gained. Being an undridled spell it doesnt need to be set. As far as i can tell the new spells are in the spells.lua in the res folder. So its not registering a precast or a midcast. and no actual gear is being swapped.

**Comment by Byrth** [comment]
Does this work now? I added them to GearSwap a while ago. If it does not, there's probably a change that needs to happen inside LuaCore.

**Comment by Schliematt** [comment]
Yes the unbridled learning issue seems to be fixed thank you, sorry for the late reply.

Date: Thu, 24 Sep 2015 09:48:02 -0700
