### ISSUE TITLE
Dev branch crashes while loading plugins

### ISSUE THREAD

**Issue by Subadai** [Windower/Issues#779]
Live version launches fine, but dev branch crashes at FFXI menu while loading plugins. Was fine yesterday.
Plugins used: P: Autoexec, Binder, DelayMeNot, FishingCrashFix, Timers

Dump & log:
https://drive.google.com/file/d/0Bz0L6fKCB4GrcG9tOXI1MU5GeFk/view?usp=sharing
http://pastebin.com/F94HynKB

**Comment by z16** [comment]
Fixed.
