### ISSUE TITLE
DressUp - Custom gear/race models not working for others.

### ISSUE THREAD

**Issue by VGGGT** [Windower/Issues#780]
Since the update on the 15th DressUp no longer applies custom model settings from settings.xml to other players.  Also, this feature still works for changing my own gear or race but reverts back after speaking to NPCs.

**Comment by Byrth** [comment]
I just pushed a new DressUp version live. Could you please tell me if this problem still persists for you?

**Comment by Byrth** [comment]
No response in 3 weeks, so I'm going to assume it works again and close this because it works for me.
