### ISSUE TITLE
Findall- Missing Safe 2

### ISSUE THREAD

**Issue by Schliematt** [Windower/Issues#781]
For some reason Line 172:

storages_order_tokens  = L{'temporary', 'inventory', 'wardrobe', 'safe', 'storage', 'locker', 'satchel', 'sack', 'case'}

Safe 2 has gone missing. Not sure why it was removed. should be:

storages_order_tokens  = L{'temporary', 'inventory', 'wardrobe', 'safe', 'safe 2', 'storage', 'locker', 'satchel', 'sack', 'case'}

**Comment by Byrth** [comment]
Actually, going back over a month ago I can't find any evidence that it was added to -dev. Perhaps someone put it only on the live branch and it was overwritten by a merge from -dev.

Regardless, it is fixed now.
