### ISSUE TITLE
Random POL Crashes.

### ISSUE THREAD

**Issue by nitrous24** [Windower/Issues#782]
No clue what is actually causing it because it's happening at random things when i'm doing different things. Not even sure this crash dump will help at all. 

https://dl.dropboxusercontent.com/u/184438010/pol.exe.1332.dmp

**Comment by Byrth** [comment]
Dump link is broken.

Are you using register_event('incoming chunk') inside of gearswap files?

**Comment by nitrous24** [comment]
no i wasn't, but since this was opened it has stopped, not sure what caused it and i had forgotten i posted this, gonna close it
