### ISSUE TITLE
Player models I'm targeting will change into chocobos randomly

### ISSUE THREAD

**Issue by highqualityshaun** [Windower/Issues#785]
Players I'm targeting will change models suddenly, examples:

 - Hume ally is suddenly a black chocobo
 - Hume ally is suddenly a yellow chocobo
 - Hume ally is suddenly a Tarutaru
 - Self (typically Mithra) is suddenly a Galka, gear equipped is gear I own, changing gear again reverts to normal Mithra model
 - Elvaan ally is suddenly a Mithra
 - Mithra ally is suddenly a Hume

I like to use the BlinkMeNot setting: "bmn 85e"

I've tried uninstalling Windower, deleting the Windower folder, and reinstalling Windower, no change.

unloading the plugin prevents it from happening but I miss this plugin a lot

Related links, others saying they're having the same problem:
https://github.com/Windower/Issues/issues/773
http://forums.windower.net/index.php?/topic/945-blinkmenot-is-not-working/
http://forums.windower.net/index.php?/topic/933-chars-random-race-choocobo-change/

**Comment by highqualityshaun** [comment]
made a video of described behavior:

https://youtu.be/wfTdtavsCxE

**Comment by Pasimoso** [comment]
I'm having the same issues, I thought it was gearswap but it is blinkmenot. Everytime I cast a spell or do a JA, I change model's in to a Hume. Did you ever fix this problem?

**Comment by nitrous24** [comment]
cross posting before i close this since you posted this twice just in case someone reads this:

Do not use blinkmenot, it has been having issues for a while now. There is
an addon alternative called dressup.
