### ISSUE TITLE
Windower Launcher with the latest .NET Framework 4.6

### ISSUE THREAD

**Issue by Shuzaku1** [Windower/Issues#786]
I recently downloaded and installed .NET Framework 4.6 and ran Windows update to download all of the latest updates (I haven't updated for almost a year). Upon doing so (and rebooting), the Windower Launcher v4 would fail to launch, outputting a "crash.log."

This crash is the launcher itself, before POL even has a chance to open. I received no on-screen errors whatsoever and didn't realize the launcher was crashing until I opened the Windower directory and found the crash log after wondering why Windower was refusing to boot. This happened with both the profile shortcuts and Windower.exe itself.

After trying various solutions such as multiple reboots, double checking I had all Windows updates, disabling my anti-virus (Avast), reinstalling Visual C++ 2008 redistributable, etc, I found that uninstalling the .NET Framework 4.6 resolved the issue, which I had to do so by going to Control Panel -> Uninstall a program -> View installed updates -> Uninstall an update with the code: KB3045563.

After uninstalling it, I decided to reinstall the framework to see if I could reproduce the issue and sure enough the crash came back after a reboot. The issue was resolved again after removing the KB3045563 update and rebooting.

I captured a .dmp file to compliment the crash log, which I'll link along with some basic system information if that helps: [Dropbox Download Link](https://www.dropbox.com/s/etvhygnyp7xhfc2/WindowerLauncher_Crash_Info.zip?dl=0)

It's included with the system information, but yes I'm using Windows 8.1. For now I'll stay away from installing the .NET Framework 4.6 as that seems to be the best workaround for now, at least until there's a solution to the crash. I hope this information can be of some help until then.

Edit: I forgot to mention, but vanilla POL would launch just fine and boot all the way into the game. It was just the launcher itself that would crash.
I remembered to "Run as Administrator" as well to rule that out of potential issues.

**Comment by alphaONE2** [comment]
This looks like a an incompatibility with Eazfuscator. And I'm not sure there's anything we can do to fix it short of paying the 399 USD to upgrade to the latest version.

I'm going to close this since you've managed to work around the issue, and there's not much we can do to fix it.

**Comment by wildsprite** [comment]
I'm having this issue too but there is no way to uninstall dot net 4.6 in windows 10 version 1511 :/
