### ISSUE TITLE
Gearswap - Changing me into a Hume

### ISSUE THREAD

**Issue by Pasimoso** [Windower/Issues#790]
I recently came back to the game 11/5/15 and started playing around with my gearswaps. I noticed that every time I casted or did a JA, I would instantly convert to a Hume on all 3 of my toons. All the same blonde haired toon.  After that, Gearswap would not work and kept telling me "gearswap: Lua runtime error: gearswap/refresh.lua:234: attempt to index field '?' (a nil value)" also "Gearswap: Lua runtime error: libs/tables.lua:172: bad argument #1 to 'pairs' (table expected, got nil)"

Help?

**Comment by Pasimoso** [comment]
Actually, gearswap works fine until I change into a Hume. I was going through the recent Issues and found someone who is having the same issue as to changing models. It's the cause of Blinkmenot. Any solutions?

**Comment by nitrous24** [comment]
Do not use blinkmenot, it has been having issues for a while now. There is
an addon alternative called dressup.

**Comment by Pasimoso** [comment]
Thank you!
