### ISSUE TITLE
Can't Equip items

### ISSUE THREAD

**Issue by defthand** [Windower/Issues#794]
So i'm playing on a private server, using windows 10.

Problem i am having is:
Under status/equipment/etc it gets stuck saying 'downloading data'.
If i level up, it fixes it.

I have this issue on multiple servers, so it is something on my end. Is it a weird combo of W10 and windower? Has anyone else had this issue.

Disabled windows defender just to see, no change. Reinstalled client/game, no change.

**Comment by alphaONE2** [comment]
I don't think this is Windower. try playing without Windower and seeing if the problem persists.

**Comment by z16** [comment]
Yeah, many private servers have not been updated to work with the latest update yet. It's probably because of that, many people on private servers initially reported this issue, but no one outside of private servers did.

**Comment by Byrth** [comment]
Going to close this issue because it cannot be replicated on retail servers.
