### ISSUE TITLE
Plasticsurgeon

### ISSUE THREAD

**Issue by xbmitchx** [Windower/Issues#796]
Dont know if this plugin is updated or intended to be kept up on but thought i'd at least let people know its bugged. When doing some of the Rhapsodies of Vana' Diel last night i changed my race and it made my weapon and armor freak out also in one of the cutscenes my characters right arm was missing all together.

**Comment by Byrth** [comment]
Are you sure it wasn't BlinkMeNot?

**Comment by xbmitchx** [comment]
Yes, not only does it cause the skeleton of the character to become messed up while in cutscenes, after interacting with NPCs, survival guides, etc. it kicks you out of whatever you changed to.

**Comment by Byrth** [comment]
That sounds like the same problem that DressUp and BlinkMeNot had. SE changed model updating behavior a few patches back.

I don't really know what to suggestion. Is PlasticSurgeon even supported anymore @z16 ? Hasn't its functionality pretty much been taken over by DressUp?

**Comment by z16** [comment]
It has, functionally it's completely a subset of *DressUp*, but it's used differently, so it hasn't been discontinued as of yet. This may be a good point to do so. Does *DressUp* work properly yet?

**Comment by xbmitchx** [comment]
I have recently been using DressUp and it has worked just fine actually. Be sure that plasticsurgeon is not active or Dressup will not work.

**Comment by Byrth** [comment]
DressUp is fully functional as far as I can tell. I vote that you remove PlasticSurgeon from the manifest and then close the issue!
