### ISSUE TITLE
Can't target objects in windower

### ISSUE THREAD

**Issue by bleenky** [Windower/Issues#797]
Ran into an interesting problem this evening while using windower. I can't tab to NPC's or use my controller to move the cursor around.

No sounds or anything when trying to do so, I can type /targetnpc while standing in front of a door or other NPC, but to change NPC's I have to move to another one and type /targetnpc. Once I have the NPC targetted, it shows >Locked< under the NPC's name in red lettering. Once I have something selected, when I hit the "H" key, the >Locked< text flashes for half a second then goes back to red.

![](http://i.imgur.com/1mdcdbe.png)

Same results with characters and the /targetpc command. Once I have anything selected I also can't move the cursor off of them; either by using the controller buttons or by tabbing. I also can't select or deselect anything using the mouse.

![](http://i.imgur.com/3udjkLB.png)

Since I can't deselect an object I can't heal/rest using the "H" key but /heal works to rest me. If nothing is selected, like when I first log on, I can heal/rest just fine using the "H" key and/or its corresponding controller button.

I'm using typical plugins/addons, tparty, tickle, timers, distance, on my default profile, but I also have a profile with no plugins/addons selected. Both profiles are experiencing the same issue.

Finally, when I log into ffxi using the ffxi shortcut (and not through the windower), I can tab around just fine. 

Using Windows 7 and was playing just fine this afternoon, came back and logged back in this evening with no changes and this is happening.

Any ideas? For now, I'm just using non-windowered ffxi and I can't handle not having my regular content.... >.>

**Comment by z16** [comment]
Can you try loading Windower without any plugins and see if the issue persists? To load without plugins it's not enough to have an empty profile, that will still load LuaCore. Instead start FFXI through Windower (with any profile) and before you go from POL to FFXI go to Windower/scripts/autoload/ and open the autoload.txt file in there. Remove every line from the file and save it. Then proceed to load FFXI (without starting Windower again, or the file will be overwritten again). If the issue persists then it's not something we've done recently. If it does not, it's one of the plugins. Try loading the plugins one by one after that to find out which one.

**Comment by bleenky** [comment]
Thank you very much for your reply. Removing all the plugins listed in that file;

wait 5;
load LuaCore;
load Config;
load Tickle;
load Timers;
lua load distance;
lua load TParty;
exec init.txt;

and running the game worked. I was able to target and do everything as expected.

I then started to add them one by one back into the file with the following results

SUCCESS
wait 5;
load LuaCore;

FAILURE
wait 5;
load LuaCore;
load Config;

SUCCESS
wait 5;
load LuaCore;
load Tickle;
load Timers;
lua load distance;
lua load TParty;
exec init.txt;

So loading all normal plugins - config works. Looks like config is the culprit, this leads to two questions; 
1) Is it needed? Can I just omit config and be ok? If so, how do I permanently remove it from autoload.txt. 
2) What else can I do to assist you in sorting this issue out?

Thank you

**Comment by alphaONE2** [comment]
Config does things like adjusting draw distance and aspect ratio, and frame rate. It's completely optional, though the game will generally not look as nice without it.

Posting the settings you use for Config may help narrow down where the problem is.

**Comment by bleenky** [comment]
<?xml version="1.0"?>

-<settings>


-<global>




<AdjustAspectRatio>true</AdjustAspectRatio>




<AspectRatio>1.33333</AspectRatio>




<ClippingPlane>10</ClippingPlane>




<AnimationFrameRate>0</AnimationFrameRate>




<FootstepEffects>true</FootstepEffects>




<FrameRateDivisor>2</FrameRateDivisor>




<AutoDisconnectTime>0</AutoDisconnectTime>




<BattleAutoTarget>true</BattleAutoTarget>

</global>

</settings>

**Comment by bleenky** [comment]
<?xml version="1.0"?>

-<settings>
-<global>

<AdjustAspectRatio>true</AdjustAspectRatio>

<AspectRatio>1.33333</AspectRatio>

<ClippingPlane>10</ClippingPlane>

<AnimationFrameRate>0</AnimationFrameRate>

<FootstepEffects>true</FootstepEffects>

<FrameRateDivisor>2</FrameRateDivisor>

<AutoDisconnectTime>0</AutoDisconnectTime>

<BattleAutoTarget>true</BattleAutoTarget>
</global>
</settings>

**Comment by bleenky** [comment]
Ok, the comment box is loading the XML haha

here is an image of the xml;

http://i.imgur.com/eqHNmOv.png

**Comment by bleenky** [comment]
Could it possibly be <BattleAutoTarget>true</BattleAutoTarget> that's causing the issue?

**Comment by z16** [comment]
Possibly, yes. It should not have the `BattleAutoTarget` option defined in there at all, unless you manually added it. Can you try setting it to `false` and see if that fixes it?

**Comment by z16** [comment]
Is there any new activity on this?

**Comment by Nifim** [comment]
This works fine now, I use `BattleAutoTarget`
