### ISSUE TITLE
Incorrect information passed to 'add item' and 'remove item' events.

### ISSUE THREAD

**Issue by trv6** [Windower/Issues#801]
The wiki lists the bag parameter as being an integer corresponding to the bag's id, while the actual argument passed is the bag table containing all items, etc. This is inconvenient, since that information isn't usually needed (and would be easily accessible if it were), and there's no way to determine which bag the table corresponds to.

**Comment by trv6** [comment]
Also, the index and id parameters seem to be out of order and the id argument is not the actual id of the item.

**Comment by cairface** [comment]
Identified the issue with Index and ID being switched.. as for the table, I traced it as far as the event being scheduled and I can't really figure out why Lua ends up with something other than a number.
