### ISSUE TITLE
Windower Crashes from POL to FFXI

### ISSUE THREAD

**Issue by Hockeybeast** [Windower/Issues#802]
Hey guys. Since SE had login problems on 12/21/15, i've been having problems logging into ffxi using windower. When i try to log in it comes up with a white screen (yes i did tried the workaround for the white screen) that says error "Playonline Viewer has stopped working."  I've had no problems with windower up to that date and everything was running good. I tried uninstalling and reinstalling both ffxi and windower and no luck. 
Here is a copy of the dumpfile from the error,

http://www.mediafire.com/download/lfebpl0y63t0bmy/pol.exe

I'm running windows 10 
Please help!! ; ;

**Comment by Iyouboushi** [comment]
Try messing with the resolution of the game in windower.  Laptops are especially picky when it comes to resolutions.  For example, on my laptop the default resolution of 1024x768 and the full screen resolution 1920x1080 both cause this crashing error (crashing as soon as the game switches to FFXI).  The only way I ever found to stop this from happening was to set the resolution to 1280x720 and run it as 'windowed' mode.

**Comment by Byrth** [comment]
Windower's next minor version update (v4.3) was released today on -dev. To try it out, duplicate your entire Windower directory, then download http://update.windower.net/dev/Windower.exe , replace your existing Windower.exe, and log in. I think there's a pretty good chance that it solves your problem, or at least changes it substantially. You can read more here: #876

I am going to close this now. Please let us know in that thread (and reference this thread) if you still have crash issues.
