### ISSUE TITLE
Timers Plugin: Augments from Telchine set are not adjusting displayed duration of Enhancing spells in Timers

### ISSUE THREAD

**Issue by dilbertson** [Windower/Issues#804]
The augments from the Telchine armor set are not being factored into calculating the total duration of enhancing magic spells in Timers.

Note:Firestorm has a base duration of 180 seconds. Perpetuance includes the augment from sch empyrean bracers ilvl119, Actuals are compared to durations displayed by built in status timers.

**Case 1:** no perpetuance, no telchine pieces 
*Expected and Actual:* Timers creates a 180 second timer.

**Case 2:** with perpetuance, no telchine pieces
*Expected and Actual:* Timers creates a 459 second timer.

**Case 3:** with perpetuance, with telchine pieces (+36 enhancing magic duration)
*Expected:* Timers creates a 624 second timer
*Actual:* Timers creates a 459 second timer.

Telchine armor provides a percentage increase to the duration of enhancing magic and I believe is calculated as follows: 
(base spell duration) * (total telchine set bonus) * (perpetuance SCH JA)

Timers would need to check your midcast equipment, add up the random augments from the enhancing magic duration buff, and factor in any other sources of duration extension. I've only tested with SCH thus far and have not had the chance to test w/ Composure on RDM.

Here is a sample of what the augments look like from a gearswap export:

```
sets.exported={
    head={ name="Telchine Cap", augments={'Enh. Mag. eff. dur. +7',}},
    body={ name="Telchine Chas.", augments={'Enh. Mag. eff. dur. +10',}},
    hands={ name="Telchine Gloves", augments={'Enh. Mag. eff. dur. +10',}},
    legs={ name="Telchine Braconi", augments={'"Mag.Atk.Bns."+13','"Fast Cast"+3','Enh. Mag. eff. dur. +9',}},
    feet={ name="Telchine Pigaches", augments={'Enh. Mag. eff. dur. +10',}}
}
```

**Comment by z16** [comment]
Fixed.
