### ISSUE TITLE
Windower Crashes When Opening POL

### ISSUE THREAD

**Issue by Kincard** [Windower/Issues#805]
Crash dump here: http://www.filedropper.com/polexe560

Using Windows 10.

I often run into a very strange issue where if my computer has been on long enough, Windower will begin to crash upon attempting to launch POL. The weird thing is that there doesn't seem to be any consistent trigger for it, sometimes it happens just a few minutes after I've turned on my computer, sometimes I can keep it on for days and this issue never occurs. It doesn't seem to happen because of any specific program, either. Being able to launch XI normally when this is happening is pretty consistent, though.

I can resolve it just by rebooting my computer, so it's not really a big deal or anything, just kind of annoying. Thanks for your time!

**Comment by Byrth** [comment]
I know it was a while ago, but does this still happen for you?

**Comment by Byrth** [comment]
Windower's next minor version update (v4.3) was released today on -dev. To try it out, duplicate your entire Windower directory, then download http://update.windower.net/dev/Windower.exe , replace your existing Windower.exe, and log in. I think there's a pretty good chance that it solves your problem, or at least changes it substantially. You can read more here: #877

I am going to close this now. Please let us know in that thread (and reference this thread) if you still have crash issues.
