### ISSUE TITLE
addons updating incorrectly in windows XP

### ISSUE THREAD

**Issue by retroman** [Windower/Issues#806]
For some reason, when running windower on windows XP it pulls in an ancient version of the addon archive (from 3/21/2015) and overwrites the current updates when they are obtained when running windows 7 with the same installation.  Everything still works fine with XP as long as the current addon file versions are used, so it would be swell if you could fix this.

**Comment by alphaONE2** [comment]
This has been known for a *very* long time, but we honestly have no idea why it happens. And it doesn't seem to happen to everyone using XP. We've spent a considerable amount of time trying to reproduce and analyze the cause and the search has been mostly fruitless. Our best guess at this point is that there's some strange bug in the SSL implementation in the XP version of the .Net Framework on XP (GitHub insists on using SSL). In any case, It only happens on XP, and both we and SE officially stopped supporting XP ages ago (only about 1% of our users use XP), so we have no plans to fix or work around the bug at this point.

**Comment by retroman** [comment]
Thank you for the information.  I'm sorry I didn't search well enough to learn you've wasted time on it already. I'm surprised there is anyone at all still using XP -- thought I was the last holdout!

**Comment by alphaONE2** [comment]
Really no problem. If it were simple we would have fixed it a long time ago, even though it started happening after we dropped XP support. At the time, we still had somewhere around 20% of our users on XP (it's been a while, so that number may be off), and it was causing a pretty significant increase in the number of false bug reports.
