### ISSUE TITLE
Coordinates in the mouse event are not scaled when the UI scale is greater than 1.

### ISSUE THREAD

**Issue by trv6** [Windower/Issues#807]
This was posted in the windower forums here: http://forums.windower.net/index.php?/topic/1035-need-help-moving-addons/
I checked to make sure it was the UI scale.

**Comment by alphaONE2** [comment]
Ah, good, I had totally forgotten about this.

**Comment by alphaONE2** [comment]
After thinking about this for a bit, I think the best course of action is to put the scaling in LuaCore, the only other plugin that uses this feature right now is FFXIDB, and it seems to handle everything correctly already; putting it in Hook means we break FFXIDB.

**Comment by funkworkz** [comment]
Bumping this for interest. would love to have this fixed.

**Comment by calebcassel** [comment]
+1 This would be really nice to have working.

**Comment by Nifim** [comment]
This seems resolved, please let me know if the issue does still persist with a full reproduction procedure.
