### ISSUE TITLE
Help please, windows 7 crash:

### ISSUE THREAD

**Issue by Monkeyman2769** [Windower/Issues#810]
[Dump.txt](https://github.com/Windower/Issues/files/140668/Dump.txt)

**Comment by Monkeyman2769** [comment]
No idea what this is..always happens randomly

**Comment by alphaONE2** [comment]
No idea what this is either. Not much we can do with this.

**Comment by Monkeyman2769** [comment]
No idea at all?

**Comment by z16** [comment]
Can't do anything without a [crash dump](https://github.com/Windower/Issues/wiki/Enabling-automatic-crash-dumps). This "dump" file does not tell us a thing.

**Comment by Monkeyman2769** [comment]
Hey man, I uploaded the crash file can you please look at it asap

https://github.com/Windower/Issues/issues/816



ty
