### ISSUE TITLE
infobar broken after last update

### ISSUE THREAD

**Issue by maja6791** [Windower/Issues#811]
InfoBar just shows the "notes" for all targeted mobs, npc's, and pc's.

**Comment by mbsaxplayer** [comment]
Still broken as of now. Any ideas?

**Comment by z16** [comment]
Too lazy to fix, it's a giant pile of poo. Someone should do a recode already with some of our existing API. I wouldn't hold my breath for this getting fixed anytime soon.

**Comment by KenshiDRK** [comment]
I'm working on an addon version but I don't know how to deal with databases and will need help here so can't say when it will be out.
![Infobar](http://i.imgur.com/VXqqpRd.png)

**Comment by Nifim** [comment]
the InfoBar plugin has been deprecated, the addon version Kenshi mentioned above is what should be used now!
