### ISSUE TITLE
[Timers] RDM buff duration broken

### ISSUE THREAD

**Issue by pcdavid52a** [Windower/Issues#813]
Duration for composure buff on others is broken. Treating it as if it's a self buff with composure.

**Comment by Byrth** [comment]
Composure seems to be working fine now, but RDM JPs were being applied as a percentage boost instead of as +1 second per JP and all Duration +X seconds gear was being applied after Composure instead of before it.

I've fixed the two problems in v3,7,4,19 and pushed it.
