### ISSUE TITLE
POL to FFXI crash only when using windower

### ISSUE THREAD

**Issue by chrisellis111** [Windower/Issues#814]
After the 3/3 MS update FFXI would crash on load up from POL only using windower. This happened to separate laptops at the same time running windows 10, so I reverted one back to windows 7 it now works fine. I bought a new laptop last-night  and installed FFXI, windower etc and it is still crashing on load up from POL . So I downloaded Developer mode it works If i dont plug in my xbox 1 controller, as soon as I do it crashes the game or disables the keyboard. I get the exact same results on both windows 10 computers.

**Comment by Byrth** [comment]
Would you mind potentially creating a crash dump of the crash that occurs when you plug in your x-box controller?

https://github.com/Windower/Issues/wiki/Creating-crash-dumps-with-Windbg

**Comment by Byrth** [comment]
Windower's next minor version update (v4.3) was released today on -dev. To try it out, duplicate your entire Windower directory, then download http://update.windower.net/dev/Windower.exe , replace your existing Windower.exe, and log in. I think there's a pretty good chance that it solves your problem, or at least changes it substantially. You can read more here: #877

I am going to close this now. Please let us know in that thread (and reference this thread) if you still have crash issues.
