### ISSUE TITLE
another POL to FFXI crash thread

### ISSUE THREAD

**Issue by vonduke** [Windower/Issues#815]
After moving my computer from one room to another the other day, and after a Windows and Graphics driver update, windower decided to not load FFXI on me. I redownloaded FFXI from the SE website instead of steam thinking that was the issue but no go on that. both POL and FFXI work just fine on the vanilla client but only POL works on windower and crashes at the transition from POL to FFXI. I made a dmp file on the crash: https://drive.google.com/open?id=0BxiQihzmi6r4RGVTdE9uZW9Jbm8

If the file does not open be sure to let me know so I can use another website to create it. Thanks in advance

**Comment by vonduke** [comment]
If it does not load, this is where it crashes:
(2ba8.540): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
*** WARNING: Unable to verify checksum for C:\Program Files (x86)\PlayOnline\SquareEnix\FINAL FANTASY XI\FFXiMain.dll
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for C:\Program Files (x86)\PlayOnline\SquareEnix\FINAL FANTASY XI\FFXiMain.dll - 
eax=02470828 ebx=00914200 ecx=02470a58 edx=00821c78 esi=02ffdb20 edi=0019ee6c
eip=00000000 esp=0019ed48 ebp=00a40a58 iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010206

I wish I knew what this meant but I'm guessing that something is wrong between the FFXiMain.dll and Windower

**Comment by Byrth** [comment]
Windower's next minor version update (v4.3) was released today on -dev. To try it out, duplicate your entire Windower directory, then download http://update.windower.net/dev/Windower.exe , replace your existing Windower.exe, and log in. I think there's a pretty good chance that it solves your problem, or at least changes it substantially. You can read more here: #876

I am going to close this now. Please let us know in that thread (and reference this thread) if you still have crash issues.
