### ISSUE TITLE
Crash when update to windows 10

### ISSUE THREAD

**Issue by Monkeyman2769** [Windower/Issues#816]
[pol.zip](https://github.com/Windower/Issues/files/171156/pol.zip)

Hello, here is my crash uploaded. Please help crashes on windows 10 to ffxi.

**Comment by Byrth** [comment]
Windower's next minor version update (v4.3) was released today on -dev. To try it out, duplicate your entire Windower directory, then download http://update.windower.net/dev/Windower.exe , replace your existing Windower.exe, and log in. I think there's a pretty good chance that it solves your problem, or at least changes it substantially. You can read more here: #876

I am going to close this now. Please let us know in that thread (and reference this thread) if you still have crash issues.

**Comment by Monkeyman2769** [comment]
Thanks brother it's Andrew (Kon). Thanks for everything you do for this
game too Btw.
