### ISSUE TITLE
Timers - Tracking debuff songs in the buff side

### ISSUE THREAD

**Issue by Sechs** [Windower/Issues#818]
Same issue that happened many other times in the past. Not sure how long it's been up this time because I haven't played BRD in quite some time.
Basically it tracks stuff like Carnage Elegy, Foe Lullaby and Pining Nocturne (they are debuff songs) in the buffs window of Timers, saying the target you cast them on and how much time is left.

Putting them in the buff filters into the xml config doesn't do shit, Timers still tracks them.
Please fix it, it creates a fuckton of screen clutter, to the point it makes it impossible to track your songs/buffs.

**Comment by Nifim** [comment]
This appears to have been resolved, I can not replicate it on my BRD.
