### ISSUE TITLE
windower.ffxi.get_items() returning an item status of 12 for Bead Pouches

### ISSUE THREAD

**Issue by Petewilmer** [Windower/Issues#821]
When using pouches I encountered an issue with gearswap where /item "Bead Pouch" <me> would stop working. After debugging for a while I determined it was because Gearswap was not finding a useable item in the inventory, despite there being Bead Pouches in the inventory. 

`for i,v in pairs(items.inventory) do
            if type(v) == 'table' and v.id == item_id and (v.status == 5 or v.status == 0) and (not bool or is_usable_item(v)) then`

The above if statement fails due to v.status == 5 or v.status == 0. Looking at http://dev.windower.net/doku.php?id=lua:api:functions:ffxi:start#windowerffxiget_items_bag_index I can see that the status should indeed always be 0,5,19,25 for any item, but for Bead Pouches I'm seeing a status of 12. This means gearswap is detecting the item as not useable and preventing the spell from finishing.

**Comment by z16** [comment]
Interesting! That is new. Do those bead pouches do anything special? The status value indicates special usage of the item (regular, equipped, bazaared, etc.). Do those pouches have any special functions for you right now?

**Comment by Petewilmer** [comment]
I've done some further testing and it looks like the status of the item changes when it's used. I created a function that outputted all of the statuses of items in my inventory, and when I ran it, the pouches were all 0. However when I used a bead pouch, it's status updated to 12. Specifically the bead pouch stack that I used was the one to have a status update. I had 2 stacks of bead pouches and the unused one was still status 0. I then tried a silt pouch and the same thing happened, as well as a Frayed sack of opulence and a boulder case (which are very different to the bead/silt pouches).

There's no special campaign going on for all these items right now, although there is a campaign where unity coffers give 2x items instead of one.

**Comment by z16** [comment]
That's good to know. I'm not up to date on anything FFXI-related, what happens to those items when you use them? Can you reuse them after a while? Do they stay used?

**Comment by Petewilmer** [comment]
They're consumeables, not re-useable at all. I just tried a food item, and the same effect happens, it changes to status 12 once used. Once you use the item, the item disappears, so if I only had 1 item, I wouldn't see a status of 12 because the item is gone from the inventory. If however I have a stack of the item, when I use one, it's updating the status of the rest of that stack to 12. It seems to be any item that you can use in your inventory that this affects.

**Comment by z16** [comment]
Huh... that's strange indeed. For now we can add it as an allowed item status, but I wouldn't mind if this was investigated a bit more to figure out why the client needs its own status for this.

**Comment by Byrth** [comment]
I wonder what is special about this compared to, for instance, eating one cookie from a stack.

**Comment by z16** [comment]
Item statuses are usually so the client knows how to treat items as objects... 5 means it will display green and greyed out when trying to move them, same for bazaaring and linkshell, which all have special mechanics in one way or another. I don't know what is special about those consumables...

**Comment by Petewilmer** [comment]
I just tested it with cookies too, and yet again eating 1 changes the rest of the stack to status 12. If however I take one cookie out of the stack using manual sort, and it auto-sorts it back to a full stack, it immediately resets to 0 again. The antacid I used also went to 12 after use. A further test showed that if I split a stack that has status 12, both of the subsequent item entries have status 0.

**Comment by Petewilmer** [comment]
I don't know the specifics of how the item status gets updated in the API, but could 12 represent item in use? Perhaps when the item gets used the API is picking up a new status of 12, but when the item use is completed it's not resetting it back to 0? I would have thought that if windower detects an item being updated to status 12 as it happens, it would have detected it resetting back to 0 too. Does windower read the status directly from memory whenever get_items() is called, or does it maintain its own table by listening to packets?

**Comment by z16** [comment]
This could be the case.... could you test that with an item that takes longer to use?

**Comment by z16** [comment]
Or, if you look at packets, you could find out very quickly.

**Comment by Petewilmer** [comment]
I'm terrible with packets, however I found a slow use item, scroll of instant warp. When I use it, sure enough the status updates to 12. When I cancel use by resting, the status resets to 0. It seems like if I cancel usage midway the item resets to 0, but if I don't the 12 sticks. I could only test this on the scroll of instant warp and a boulder case. Everything else was used too quickly for me to cancel in time.

**Comment by z16** [comment]
I guess that's pretty conclusive then. The only question remaining is why it does not reset. But this might as well be attributed to SE just being messy.

**Comment by Byrth** [comment]
No, it turns out they added item status to the 0x1E packet. We need to integrate that into the API and this problem will be resolved.

Allowing 0x0C status in gearswap would cause problems because that status exists specifically to stop you from double using items.

**Comment by Byrth** [comment]
I pushed a fix for GearSwap and changed 0x01E incoming's fields.lua entry, but this changes needs to propagate to LuaCore's windower.ffxi.get_items() so I'll leave the issue open

**Comment by z16** [comment]
I pushed a new Hook to dev. Since it contains some mild refactoring for the latest changes, I'd like to leave it here for a day or so, to make sure it doesn't break more than it fixes. I assume this is not an urgent issue?

**Comment by Byrth** [comment]
Not too urgent, no

**Comment by z16** [comment]
All done!
