### ISSUE TITLE
Windower crashing PlayOnline on launch

### ISSUE THREAD

**Issue by KikodeYusaku** [Windower/Issues#823]
I was using Windower without any issues for a month or so and then suddenly it began to crash PlayOnline after the initial PlayOnline splash screen.
![image](https://cloud.githubusercontent.com/assets/17287958/14631154/23a8946e-0666-11e6-9729-2f8dfb82a20a.png)
I have tried running as an administrator, disabling/enabling UAC, uninstalling all addons/plugins, trying different settings on both the Steam and standard versions of FFXI.
Here is the crash dump: http://www.mediafire.com/download/jt8e3ctz5iepe1v/pol.exe.4604.dmp

**Comment by Byrth** [comment]
Windower's next minor version update (v4.3) was released today on -dev. To try it out, duplicate your entire Windower directory, then download http://update.windower.net/dev/Windower.exe , replace your existing Windower.exe, and log in. I think there's a pretty good chance that it solves your problem, or at least changes it substantially. You can read more here: #876

I am going to close this now. Please let us know in that thread (and reference this thread) if you still have crash issues.
