### ISSUE TITLE
Windower's menu is all white

### ISSUE THREAD

**Issue by BoneCheck** [Windower/Issues#826]
Hello, I can't figure out why Windower's menu is just all white.  It still has everything and I can launch the game, but I can't see any settings so I can fix some resolution issue (where the game is bigger than my screen even though its all set for 1920 x 1080 via the settings file.

<img width="775" alt="windower" src="https://cloud.githubusercontent.com/assets/18618791/14748471/e2f26282-0887-11e6-9d36-385b24002bfd.png">

**Comment by alphaONE2** [comment]
http://forums.windower.net/index.php?/topic/588-white-screen-at-windower-launch/#entry3453

**Comment by BoneCheck** [comment]
Thank you!  I tried to search for the solution before posting, but I suck at searching for stuff like this. lol. Thank you very much for taking the time. I am doing it now. I have 100% faith it'll work
