### ISSUE TITLE
Windower/Issues

### ISSUE THREAD

**Issue by Byrth** [Windower/Issues#827]
We need to make OS and Server Type required fields for this issues tracker.

**Comment by alphaONE2** [comment]
I've wished GitHub would add something allowing us to do this for a while, but no dice. Only contributors and owners can set issue labels on GitHub, so we can't use them, and there's no way to enforce a template that all issues need to follow. If we do this, it has to be policed by us, and I don't think any one wants that.

**Comment by Byrth** [comment]
Really? I thought kjlotus was saying they did this a while ago for dsp.

**Comment by Byrth** [comment]
Guess not! Closing!
