### ISSUE TITLE
Windower crashing on gameplay

### ISSUE THREAD

**Issue by Stan64** [Windower/Issues#829]
This happens to a lot of people I guess they are just lazy to report it.

Since some update ago (within a month) I've been crashing with Windower in Vagary and gathering exp at Escha Zi'tah #2.

We were pulling and killings with BSTs in Zi'tah and people dropped over and over again when too much happened. I have almost no plugins I mainly use it to get full screen. I switched to vanilla because it was so bad and it never crashed after that.

And I never crash usually and never get disconnected. Since Tuesday I've been crashing 3-4 times when a lot of stuff happens.

**Comment by cairface** [comment]
I believe this is related to the Guildwork plugin. Try playing with it unloaded and see if you crash. I'll try to look into it.

**Comment by Stan64** [comment]
Ok, it's the only plugin I use. I'll turn it off and play for a week and see if I crash. I play like 24/7 so will notice it for sure if I don't crash any more. It was only in party play it crashed. Could idle while sleeping and nothing happened. Incursion (18ppl) and Abyssea (3ppl) crashed some times for me yesterday for example. People don't like when their WHM has a red dot. :D

**Comment by Stan64** [comment]
Yeah, no crashes so far.

**Comment by z16** [comment]
@cairface What made you suspect GW? Do you know where the issue lies?

**Comment by z16** [comment]
This was a GW issue and has been fixed.
