### ISSUE TITLE
Timers incorrect spell names {JP Client}

### ISSUE THREAD

**Issue by Shadowlina** [Windower/Issues#830]
Hello, 
I run FFXI in the Japanese client, there are "minor" issues.
Some Job abilities are not translating into their Japanese names. Every other spell what i've seen on WHM is correct and displaying in Japanese, But Benediction displays as Benediction and Asylum is spelt asylym.
I'm not 100% sure, but i believe the spelling is also wrong in english client also. 

Minor issues, no biggy if they can't be fixed immediately, it's just minor.

**Comment by z16** [comment]
*Asylym* was really a spelling error. I assume English names are only used for SP1 and SP2 abilities?

**Comment by Shadowlina** [comment]
correct. Sorry for slow response.

**Comment by z16** [comment]
Can you see if [this file](https://googledrive.com/host/0B1-GYvFFRpK6WlVQZnBKbzdycTA/Timers.dll) fixes it?

**Comment by Shadowlina** [comment]
Sorry have been having a hard time to push the Japanese client to update.
They're all good and correct. Thank you.
