### ISSUE TITLE
i think KenshiDRK and me found eye glow bits

### ISSUE THREAD

**Issue by smd111** [Windower/Issues#832]
packet: 0x00E
byte 42 (0x2A)
int = bit_map
4 = ?????100 -- no eye glow
5 = ?????101 -- yellow eye glow
6 = ?????110 -- blue eye glow
im betting
7 = ?????111 -- red eye glow
this appears to be accurate for Peistes at lest

**Comment by KenshiDRK** [comment]
thats accurate for peistes, caturae are a little different as you need to take into account the shield, It might be possible that weaknesses animation are around here too.

**Comment by smd111** [comment]
it looks like it based on effects that the model can produce
so it would be effect 1 and effect 2

**Comment by KenshiDRK** [comment]
could try and addon that changes that byte and see how the model changes

**Comment by smd111** [comment]
thats the one thing i dont know how to do

**Comment by KenshiDRK** [comment]
I'll try to make one, thats what I think is:
0x2A (byte 42) 00 00 01 00, that 01 means that it can have model effects
0x2B (byte 43) 00 00 01 00, maybe this means they can have a weakness, cause the caturaes was showing this byte as 4 (100) while peiste was showing 0 (the peistes I checked couldn't have a weakness animation, so probably maju has this byte 4), a pugil were showing 0s for the complete _unknown4, it couldn't have any effect animation)

**Comment by teschnei** [comment]
0x2A is the subanimation.  It depends on the model, and the animation is different on the model.  The lowest 2 bits control the animation itself, and the rest don't appear to do anything.  Examples: Shinryu has wings open/close, yovra have in the sky/down, aern have normal, bracelets, reraise, various aht urhgan enemies have weapon broken, peistes have the eye glow, etc.
2B is a bitmask of various things, including name visibility.

https://github.com/DarkstarProject/darkstar/blob/master/src/map/packets/entity_update.cpp

The weakness stagger proc animation is just a weaponskill with no skeletal animation (just a particle effect), so it's in a 0x28.

https://github.com/DarkstarProject/darkstar/blob/master/src/map/utils/mobutils.cpp#L1417

**Comment by smd111** [comment]
well i did not look at darkstar and windower marks them as unknown

**Comment by z16** [comment]
We're gonna close this issue, as it's not really an "issue" in that sense. The information will always be here if we need it in the future.

That said, you're free to adjust the `fields.lua` file accordingly and submit a pull request. *Darkstar* knows quite a few things that we don't, so it's always worth checking out when working with packets. I've always been meaning to go through some packets and update them with info from *Darkstar*, but so far I've just been way too lazy. Feel free to do it for me :)
