### ISSUE TITLE
ja0wait

### ISSUE THREAD

**Issue by Selindrile** [Windower/Issues#833]
Just wondering if it would be worth it to you to create a version of ja0wait that only allowed movement during the animations that we can already move during sometimes. To prevent getting locked down while cleaving or the like by monster abilities that started while you weren't moving, but still be unable to move when doing your own JA or spell or WS or raising, things like that. It would be less visually detectable, and feel less cheat-like to me personally (and prevent me from accidentally moving when I probably shouldn't). Byrth said that I might have more luck if I mentioned it here.

**Comment by cairface** [comment]
It's a good deal of work with no practical benefit.

**Comment by Selindrile** [comment]
Well I feel like there'd be a practical benefit to those like myself unwilling to use ja0wait due to worry and such, that said, totally understand if it's too much work for too little benefit to the coders to feel like doing, but I was wondering exactly that, how much work it would be to discern between the two, thanks for answering, and I hope it happens in 5.0 then ^^.

**Comment by alphaONE2** [comment]
It's a *lot* of work. No, it's probably not going to happen in Windower 5 either.
