### ISSUE TITLE
POL crashes when attempting to launch FFXI

### ISSUE THREAD

**Issue by Kasaioni** [Windower/Issues#835]
POL Viewer launches just fine through Windower 4, however POL Viewer crashes as soon as it attempts to launch FFXI. Vanilla POL and FFXI launch and run without any issues. 

I have set both POL and FFXI config settings to default with the same results. I have unchecked compatibility boxes for POL and got the same results. I have made sure vanilla FFXI was launching in fullscreen to begin with; same results. I have disabled all UAC notifications and the crash is still consistent. I have made sure to run Windower and POL as administrator and the crash still occurs. I have tried using different resolutions through Windower and the crash still happens.

My operating system is Windows 10.

Windower is version 1.18.15e (or Launcher: 4.2.5564.39855, Hook 4.2.13.9 as shown in the Windower launcher)

I do not have any plug-ins or add-ons installed. Windower was a fresh install.

My settings are:
Console key: Insert
Windowed
Resolution: 1920x1080
UI Scale: 1

The details of the crash are simply that launching the game with Windower enabled as normal results in a crash as soon as POL attempts to start FFXI (i.e. after the ESRB rating and version update check). The crash happens always at the same time.

Here is a crash dump file. http://www.mediafire.com/download/qrk7o0z118vtka1/pol.exe.7316.dmp

I have looked at a few different people who have posted issues here that seem similar to mine, but I have not seen any fixes or definitive answers. So, I thought It would be a good idea to post my specific issue.

**Comment by musicphan27** [comment]
I have this exact issue! I notice when POL opens when using windower, I get the error "Can only be displayed properly in 32 bit true color. Start Playonline Viewer anyway?". The game works fine when I run it without windower, and I don't get that Playonline message listed above.  I'm assuming this has to be a resolution setting somewhere. I've looked in POL, FFXI, and Windower configs.

**Comment by braskasguardian** [comment]
I had the same issue.... I forgot to disable compatibility mode for the Windower executable as well though. As soon as I did that the crashes stopped. (Windows 10, 64-bit, on a virtual machine)

**Comment by Byrth** [comment]
Windower's next minor version update (v4.3) was released today on -dev. To try it out, duplicate your entire Windower directory, then download http://update.windower.net/dev/Windower.exe , replace your existing Windower.exe, and log in. I think there's a pretty good chance that it solves your problem, or at least changes it substantially. You can read more here: #876

I am going to close this now. Please let us know in that thread (and reference this thread) if you still have crash issues.
