### ISSUE TITLE
Windower issue launching

### ISSUE THREAD

**Issue by Atigeve** [Windower/Issues#836]
Ok i have a laptop to play all games on, it has an intel HD4600 integrated gpu AND an nvidia 750m.  Now FFXI will not run off the 750m on its own, so i tried to force it by disabling the 4600 all together.  Windower refuses to launch, well sort of.  If i launch windower and get to the profile select screen, it wont go, it is just a white box.  Now if i make a shortcut to my default profile it tries to launch playonline but errors and closes everytime. I can provide screenshots if necessary.  I am on Windows 10 64bit and all drivers for all gpu are up to date.  can anyone help me figure this out? 

Thank you
Atig

**Comment by Madrooter** [comment]
i'm having the same issue, not sure what i need to change to get text visible.

**Comment by Byrth** [comment]
Windower's next minor version update (v4.3) was released today on -dev. To try it out, duplicate your entire Windower directory, then download http://update.windower.net/dev/Windower.exe , replace your existing Windower.exe, and log in. I think there's a pretty good chance that it solves your problem, or at least changes it substantially. You can read more here: #876

I am going to close this now. Please let us know in that thread (and reference this thread) if you still have crash issues.
