### ISSUE TITLE
Windower without plugins or add-on crashing 100% of time when Firefox has focus.

### ISSUE THREAD

**Issue by IBHalliwell** [Windower/Issues#838]
Hello,

This is a Windows 10 Professional x64 system.  This is a new problem starting with the June 2016 update.  I turned off ALL plugins and add-ons by using the "lua unloadall" and "unloadall" commands.  Even without them Windower still crashes 100% of the time.

NOTE:  The problem doesn't occur immediately.  If you go back and forth between Firefox (or - most likely - any program) Windower continues working fine.  Yet, if you keep the focus on Firefox for awhile it will crash.

I discovered this while reading up on the SoA missions, which I would like to complete.  Again going back and forth didn't cause a problem, but say reading 7 or so missions in a row without returning focus resulted in PlayOnline / Windower crashing.

Second NOTE:  I did NOT noticed this problem, when working on RoV missions and reading them after the May 2016 update and before the June 2016 update.

Thank you.

Please contact me should you need more information, such as dump files, more date, etc.  I don't check in here often so emailing me would be best.  :-)

**Comment by IBHalliwell** [comment]
While the file extension says ZIP, it is a 7z file, as 7zip is the compression program I use.  I tried to upload the dump files directly, but the system wants specific files.

[Pol.exe.10964.11184.13204.dmp.zip](https://github.com/Windower/Issues/files/309960/Pol.exe.10964.11184.13204.dmp.zip)

**Comment by IBHalliwell** [comment]
Happened again almost immediately after giving Firefox focus for the second time.  Basically, I:

1) Started Windower and kept the plugins and addons active, as it happens with them off, too.
2) Gave focus to Firefox to read a mission.
3) Clicked on next mission and put it in a NEW TAB.
4) Clicked on Windower / POL again to cut down on time away from FFXI.
5) Clicked on Firefox and about to change to the NEW TAB.
6) Windower / POL crashed.

Attaching dump.  AGAIN this is a 7zip (7z) file and not real zip.  I renamed only because the website won't accept DMP or 7Z files.

Thanks.

[pol.exe.10284.dmp.zip](https://github.com/Windower/Issues/files/309981/pol.exe.10284.dmp.zip)

**Comment by IBHalliwell** [comment]
Another time ...  This file is a zip file created by 7zip, but in zip format.


[pol.exe.16696.dmp.zip](https://github.com/Windower/Issues/files/310855/pol.exe.16696.dmp.zip)

**Comment by IBHalliwell** [comment]
This time POL died shortly after returning from Firefox.  Again using the zip function on 7zip.
[pol.exe.17232.dmp.zip](https://github.com/Windower/Issues/files/310862/pol.exe.17232.dmp.zip)

**Comment by IBHalliwell** [comment]
Hello,

This problem is still occurring as of July 31, 2016.

**Comment by Byrth** [comment]
Sorry that I didn't see this sooner. This was probably a result of a Flash / Firefox incompatibility. Somewhere around version 31 Firefox's handling of Flash started causing instability in other programs.

I'm going to close the issue because I'm sure you've worked around it by now and it was arguably always a Firefox problem, but personally I just switched to Chrome.
