### ISSUE TITLE
Gearswap errors "attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by eboneezer** [Windower/Issues#839]
I'm on Windows XP (please don't hate, it's the only thing i can get my xbox 360 controllers to work properly on.  
Addons that I use:  Autojoin, Autolockstyle, boxdestroyer, distance, enternity, GearSwap, macrochanger, Silence, Timestamp, Update

I took a break from the game about two months ago.  I just came back.  Windowers downloaded some updates before it launched.  When I first login to my moghouse, I briefly see an error that I believe to be "GearSwap: Lua runtime error:  gearswap/gearswap.lua:255 attempts to index field '?' (a nil value)."  

It pauses for a second and then spams a few more lines to where that original error is off the screen.  Now I see multiple lines of "GearSwap: Lua runtime error:  gearswap/gearswap.lua:379 attempts to index field '?' (a nil value)."  followed by 
"GearSwap: Lua runtime error:  gearswap/equip_processing.lua:256 attempt to index field '?' (a nil value)"
followed by a few lines of 
"GearSwap: Lua runtime error:  gearswap/gearswap.lua:456 attempts to index field inv?' (a nil value)." which is finally followed up by a few lines of 
"GearSwap: Lua runtime error:  gearswap/gearswap.lua:372 attempts to index field '?' (a nil value)."

I uninstalled Windower and deleted the folder in the Program Files.  I redownloaded and installed (including the add-ons) and am still getting the same errors.  

My gear won't change and Gearswap seems to not be functioning with these errors.

**Comment by alphaONE2** [comment]
There's a known issue on XP where it will download very outdated versions of addons. We haven't quite figured out the cause, or a way to fix it. If you could, please try manually downloading the files for the addons you use directly from GitHub at https://github.com/Windower/Lua/tree/live/addons.

**Comment by eboneezer** [comment]
thanks.  I downloaded all the files listed under each add-on.  I just sent them to their prospective folders and told them to override them.  Now when I log in, it lists each add-on with "addon name: Lua runtime error:  attempt to call a string value"  Was I supposed to not just replace the files in the folder?  Maybe i replaced something i wasn't supposed to?

**Comment by z16** [comment]
Just in case you missed some files, try downloading this:
https://github.com/Windower/Lua/archive/dev.zip

This contains all updated files (the link updates automatically, so you can do that periodically). Then just copy the `addons/GearSwap/` folder in there into your `Windower/addons/` folder.

**Comment by eboneezer** [comment]
thank you both for your help.  I tried that zip and still ran into my original errors.  I compared the files in the addons folders from the zip file with the file size of the ones on my other pc (windows 7 and functioning with no problems) and they were different sizes.  I copied the addons folders from the other PC and put them on the windows xp PC and it seems to be working perfectly.  I'm not sure what might be different or why, but it's working and I definitely appreciate the help!  Thanks for all that you guys do!

**Comment by dcameron** [comment]
Hi, just wanted to let you know that I was experiencing this same issue (error on line 255).  I just returned to the game after a 15 month absence.  Apparently, GearSwap didn't auto-update to the newest version.  I found this issue and updated the files manually, as recommended.  It solved the issue for me.  Thanks!
