### ISSUE TITLE
windower.ffxi.get_key_items() missing mounts

### ISSUE THREAD

**Issue by smd111** [Windower/Issues#840]
sorry wrong place

**Comment by z16** [comment]
Just for the record, it was the right place :)

**Comment by smd111** [comment]
i thought lua bug went in to the lua issues

**Comment by z16** [comment]
It's a *LuaCore* bug, so it belongs here. All plugin issues go here, including *LuaCore* bugs. The Lua tracker is for addon or library bugs (i.e. bugs that can be fixed in that particular repository). It's not too important, just so you know.
