### ISSUE TITLE
Windower Crashing after Wardrobe 3 & 4 Purchase

### ISSUE THREAD

**Issue by Georgieee** [Windower/Issues#842]
Hi peeps,

After today's update Windower is crashing when I go to log into game. It starts loading my character and then crashes. I logged in fine x2 until i changed areas and issue keeps happening.. After first login I purchased the 2 new wardrobes and now crashing constantly. Game loads fine when using normal login without windower

Anyone else having same issue?

**Comment by z16** [comment]
I'm pretty sure I know what this is about. I'll try to fix it in a bit.

**Comment by Georgieee** [comment]
Thanks... And crash dump says ffximan.dll. So not sure if last update some changes we're made that windower can't recognise at the moment

**Comment by Georgieee** [comment]
Have done a clean install of windows 10 and the game etc.. Problem still occurring

**Comment by Georgieee** [comment]
Have tested and works when wardrobe 3 and 4 are empty

**Comment by Keaddo** [comment]
If you don't add anything to wardrobe 3 & 4 you can play as normal, but of course it would be cool to be able to integrate them to our usual gearswap usage.

**Comment by z16** [comment]
While this is fixed in Windower/LuaCore, it still needs to be added to GearSwap. There is [a separate issue](https://github.com/Byrth/Lua-Byrth/issues/428) for that on @Byrth's tracker, so I'll close this one.
