### ISSUE TITLE
Wardrobe 3 and Wardrobe 4 support added to the windower API

### ISSUE THREAD

**Issue by EphemeralArcs** [Windower/Issues#843]
Gearswap, Findall, Organizer, Latentchecker and possibly more addons depend on the get_bags and get_info calls, for those using wardrobe 3 and 4 until the API is updated these addons can't work with those bags.  Would it be possible to have these updated?  If cost is an issue I'm sure someone could send $4 to a paypal address?

**Comment by z16** [comment]
Cost is not an issue and it will be updated tonight.
