### ISSUE TITLE
Windower support forums appear to have gone... away?

### ISSUE THREAD

**Issue by frxhaztol** [Windower/Issues#845]
For the last three days, the entirety of the Windower support forums have been blank pages for me. Returning 0 bytes of data, and inspecting the page makes it look like there's literally nothing there.

Considering this is a central repository for Windower support help and chatter, it's super inconvenient to suddenly not have access to it.

Anyone have any ideas?

**Comment by alphaONE2** [comment]
The Windower server unexpectedly rebooted approximately 34 hours ago; we don't know why. As far as we can tell everything is working (PHP, MySQL, all of it), but for some reason the forums are still generating blank pages. The wikis (which are also PHP) are working perfectly.

It's being worked on, but we're a little bit stumped right now.

In any case, it doesn't appear that any data was lost, and we have backups anyway just in case, so hopefully everything will be back to normal soon.

**Comment by Byrth** [comment]
This seems to have resolved itself. Thanks for the notification!
