### ISSUE TITLE
Timers occasionally crashes after Auspice is cast.

### ISSUE THREAD

**Issue by trv6** [Windower/Issues#849]
The crash usually occurs when I cast auspice shortly after zoning into Legion. A text object with the text "Auspice" remains on the screen in the upper left corner after the plug-in unloads.

**Comment by trv6** [comment]
Baraera caused a crash as well. This report no longer contains any useful information~

**Comment by z16** [comment]
I'm sorry to say I forgot about this. Does this still occur after the latest Timers, which was pushed a few days ago? If so, can you provide a crash dump?

**Comment by trv6** [comment]
I closed this after I noticed timers had been updated. I don't think I've seen the bug occur in the last few months, though I can't remember how much I've actually played in that time. I'll reopen it if it happens again.
Crash probably wasn't the correct word to use. Is it possible to create a crash dump for an instance of a plugin encountering an error and unloading?

**Comment by z16** [comment]
Oh, no, that's not possible. Odd... let me know if it happens again, I'll think of ways to debug the issue in that case.

**Comment by trv6** [comment]
Will do.
