### ISSUE TITLE
expose if skill is capped or players base skill

### ISSUE THREAD

**Issue by sebyg666** [Windower/Issues#850]
ok i need to try explain myself as fully as possible so bare with me.
currently in windower.ffxi.get_player() the skill your character has for the particular weapon wielded is returned as  a combination of your base skill + merits skill + skill in gear.
Now, i can track merits separately and skill in gear separately but not the base skill as this changes in the struct based on what gear i have equipped but isn't reliable as its updated with incoming packets like opening equipment screen, so my skill calculation is always going to be off by what i have equipped.

Now when you have capped skill (as in fully skilled up that weapon) the number in question in game goes blue. if the api had a bool for "skill_is_capped" for example, i could very easily track my base skill.
unless off course there's a way to add a character's base skill before gear and merits, that would be even better.

would it be possible to add this or can anyone think of another method of tracking a characters base skill.

thanks in advance.

**Comment by alphaONE2** [comment]
I'm actually surprised we don't expose this already; we have it in our plugin API. This is trivial to add.

**Comment by sebyg666** [comment]
Exellent. That gives me hope that this will get added.

**Comment by z16** [comment]
It can be added easily, yes. However, I don't really see how it would help you. You're interested in base skill from what I can tell. You're tracking gear and merit bonuses separately. Now if it's capped, you want to subtract the two to get the base? Why does it matter that it's capped for that? Maybe my 5AM brain can't follow the reasoning, but I don't see what you'll gain from this.

**Comment by sebyg666** [comment]
Right now the value of skill is not static. It changes if you equip gear. But for this value to change in the struct you have to receive the packet continuessly to keep it updated right. Now if i had the baseskill value then this doesnt matter because it would be static (if you are capped) which is directly proportional to your lvl and i can code for that. So...... i have everything to gain from it.

**Comment by alphaONE2** [comment]
We can't add a way to track base skill independently, because it's simply not available client-side. All we can do is expose whether the value is capped or not.

**Comment by sebyg666** [comment]
thats fine by me, i can deal with that

**Comment by sebyg666** [comment]
ok nevermind, i got the skill capped bool from the last packet 0x062 its in there ^^.
