### ISSUE TITLE
Wardrobe 3/4 enabled flags don't work

### ISSUE THREAD

**Issue by Byrth** [Windower/Issues#851]
For whatever reason, SE did not indicate whether Wardrobe 3/4 are enabled in the same way as Satchel, Locker, Temp items, etc. Instead of being in packet 0x01C incoming, the information is actually spammed as two flags in 0x037 incoming. It's the two least significant bits of byte 0x5C in packet 0x037, with Wardrobe 3's flag being the lsb and Wardrobe 4's flag being the second lsb.

I am unaware of any errors being caused by this, but it would be nice if it could be fixed in the next hook update.

**Comment by alphaONE2** [comment]
This should be fixed in 4.3.
