### ISSUE TITLE
Timers not properly calculating song duration when using Marsyas/Inyanga Shalwar +1

### ISSUE THREAD

**Issue by ragingchaos** [Windower/Issues#853]
When using Honor March, Timers is showing duration to be 3:45 while in game Icon Timers shows over 5m on duration. I don't believe timers has been updated to include Marsyas +50% Duration Bonus. It's also not calculating Inyanga Shalwar +1 Duration Bonus of +15%.

**Comment by funkworkz** [comment]
I came here to post this about the legs. Timers also does not count Carnwenhan 119 III towards the duration either.

**Comment by z16** [comment]
To add this I will need some more info. I need to know how it works, if it multiplies duration or adds seconds and if it happens before or after other multipliers.

**Comment by funkworkz** [comment]
All song duration items in game are additive percentages, so it should have the same values as Carnwenhan's maximum form of Song Duration V.

**Comment by funkworkz** [comment]
Also worth noting the NQ Inyanga Shalwar should be added as well.

Inyanga Shalwar (ID: 25865): 12%
Inyanga Shalwar +1 (ID: 25866): 15%
Marsyas (ID: 21398): 50%
Carwenhan 119 III (ID: 20586): 50%

**Comment by ragingchaos** [comment]
Just incase these have been over looked:

Legato Dagger 5% (Additive %)
Kali 5% (Additive %)

There is also the 5% Duration bonus from BRD's 2100 JP Gift. (Additive %)

The Job Ability "Clarion Call" adds a flat +20s after all multipliers, which is cancelled if Soul Voice is active.

**Comment by funkworkz** [comment]
Timers is functioning correctly with all four of those, I just tested all of them. There might be a new augment that isn't included in the plugin such as Dark Matter augments though (Chironic gear?). 

That reminds me, Honor March should have an extra 10% duration with March+ gear due to it affecting the quality of the song by +1.

All of the below items are "March +1":
Fili manchettes +1 - ID: 27071
Fili manchettes - ID: 27070
Aoidos' manchettes +2 - ID: 11113

There are also instruments that affect march, but they obviously cannot be equipped because Marsyas needs to be in order to use the song.

**Comment by funkworkz** [comment]
Anything further you need for a fix to be released?

**Comment by z16** [comment]
I'll see about implementing them today, if I need anything else I'll let you know. Thanks for providing that info!

**Comment by z16** [comment]
Is the Honor March effect also additive in the same way as the other equipment? So every March+ piece is the same as adding onto the bonus percentage of, say, Carnwenhan?

Also, @ragingchaos you mentioned 2100 JP for the BRD bonus, but Timers currently checks for 1200. Which value is correct?

**Comment by funkworkz** [comment]
Yes Honor March is affected by March+. Because Marsyas does not have any song+ on it, the instrument itself only grants the base duration (2 minutes?) plus 50% so 3 minutes. Every March+1 adds 10%.

The duration bonus he is talking about is only at 1200 JP for 5%.

**Comment by funkworkz** [comment]
That is also all additive percentages.

**Comment by z16** [comment]
Looking at our code, the way it's set up Honor March should not have been handled at all. Did you mean to say that Honor March was simply ignored by Timers's March calculations so far (which would make sense, given the code), or that Honor March differs from other March songs in terms of buff duration calculation?

**Comment by funkworkz** [comment]
It sounds like he is saying Honor March was being treated exactly like Victory March and Advancing March.

3:45 is what I am getting for **_all_** other songs I cast right now given these items that are not functioning with timers.

**Comment by ragingchaos** [comment]
Sorry, I did mean the 1200 JP bonus.

Also yes Honor March displayed at 3:45 using Carn 119, Marsyas and Inyanga Shalwar +1.

**Comment by z16** [comment]
I'm still thoroughly confused, can you just try [this](https://drive.google.com/file/d/0B1-GYvFFRpK6c2hOZDNBU25fb00/view?usp=sharing) and tell me what's wrong with it?

**Comment by funkworkz** [comment]
I cannot test Honor March, but I can test the other gear.

My actual song length is 5 minutes 16 seconds. Timers said I only had 5 minutes 3 seconds, so there are 13 seconds unaccounted for somewhere. I will strip some gear to see what the culprit is.

I am thinking there is some rounding that isnt adding up.

**Comment by funkworkz** [comment]
Song used to test: Army's Paeon VI. Only "+" gear I had was Ghorn with +4.

Naked with only JP +5% bonus, I am getting 2:05 on timers, actual duration is 2:07. 
(Does this take the "blinking" warning into effect? Once the blinking is done it disappears at exactly the right time. Working as intended perhaps?)

JP+5% and Ghorn bonus of "+4", i am getting 2:53 on timers, actual duration is 2:55

JP+5%, Ghorn+4, Carnwenhan timers says 3:53, actual duration is 3:55

JP+5%, Ghorn+4, Carnwenhan, Aiodos Manitee, timers says 4:04, actual duration is 4:06

JP+5%, Ghorn+4, Carnwenhan, Aiodos Manitee, Fili Hongreline +1, timers says 4:19, actual duration is 4:21

JP+5%, Ghorn+4, Carnwenhan, Aiodos Manitee, Fili Hongreline +1, Inyanga Shalwar +1 timers says 4:37, actual duration is 4:39

JP+5%, Ghorn+4, Carnwenhan, Aiodos Manitee, Fili Hongreline +1, Inyanga Shalwar +1, Brioso Slippers +1 timers says 4:51, actual duration is 4:53

Minuet V from here below. Body is Minuet +1.
JP+5%, Ghorn+4, Carnwenhan, Aiodos Manitee, Fili Hongreline +1, Inyanga Shalwar +1, Brioso Slippers +1 timers says 5:03, actual duration is 5:05

**We forgot to tell you about the Intarabus's Cape ID:26255 Grants Madrigal +1 and Prelude +1**

Other than confirmation of Honor March, I believe we are good if you can add that item too.

**Comment by z16** [comment]
Wait, before you said your length was 5:16, but you say Timers is giving you 5:03. Then in the next post you said actual is 5:05. Or did I miss something?

**Comment by funkworkz** [comment]
That first post I used Madrigal to test. Second post I used Paeon for all but the last test. I was wearing the Intarabus's Cape and forgot about that bonus, and we forgot to tell you about it. 

Intarabus's Cape ID:26255 Grants Madrigal +1 and Prelude +1

**Comment by z16** [comment]
I see, all adjustments I made were to March, so I'll wait for @ragingchaos to confirm if Honor March works correctly before I publish it. In the meantime I'll add the cape.

**Comment by z16** [comment]
Posted the new version under the [same link](https://drive.google.com/file/d/0B1-GYvFFRpK6c2hOZDNBU25fb00/view?usp=sharing). This should now work correctly for everything discussed in here, if I understood everything right. It seems I am a bit slow today, so I hope I got it right.

**Comment by ragingchaos** [comment]
Honor March lines up correctly with the custom timers I had added to Gearswap as a temporary fix.

Working. Thanks so much for the effort!

**Comment by z16** [comment]
Alrighty, gonna push this then. Thanks for the info!
