### ISSUE TITLE
Windower load not displaying correctly/ Gamepad enable

### ISSUE THREAD

**Issue by Irrellius** [Windower/Issues#854]
Windower loads as a plain white boc, and IO have learned from previous times where to click to open POL. 

I wiped my OS, did multiple fresh installs, and all I get is a blank white box.

Normally this would be fine, but I've been trying to enable a game pad and can't because I can't see the windower settings. Whenever I change the setting in the ffxi config, windower changes it back, so that's no use.

Can someone get me pictures of all the settings screens so I know where in my blank white box to click to enable a gamepad?

**Comment by alphaONE2** [comment]
This is a known issue, you can find a work around on the [forums](http://forums.windower.net/index.php?/topic/588-white-screen-at-windower-launch/).

P.S. Windower doesn't have any settings related to gamepads; you'll need to use the FFXI Config Tool that SE provides.

**Comment by Irrellius** [comment]
As noted in the original complaint, gamepad keeps being disabled after activated in ffxiconfig tool

**Comment by z16** [comment]
As @alphaONE2 mentioned, Windower has no setting for gamepads. And there is a workaround for the white box issue. We recommend you fix that instead of learning where to click on a white box. As for the gamepad, I'm not sure what to tell you. Are you sure that Windower is changing it back, and that it isn't just saved incorrectly?

**Comment by alphaONE2** [comment]
I just checked. Windower isn't changing the setting for me. It doesn't have any code that touches that setting in the registry, so it really can't change it.
