### ISSUE TITLE
Windower Issue

### ISSUE THREAD

**Issue by Saiken007** [Windower/Issues#856]
Hello,

I am experiencing a strange issue with Windower 4. Gearswap is not loading at all and I don't know how to resolve this issue by myself. I have tried looking for the problem, but I cannot find it (though I am not particularly good with computers). when I try to manually load GearSwap I get this.

GearSwap: Lua runtime error: C:Program Files (x86)\Windower4res/items.lua:19677: unexpected symbol near <eof    

I have tried searching for the file, but no searches are found.

**Comment by z16** [comment]
It sounds like your resources are corrupted, as it seems to have trouble parsing our items resources. Go to `C:\Program Files (x86)\Windower4\res\` and delete the file `items.lua`. Then go to `C:\Program Files (x86)\Windower4\updates\` and delete the `resources.xml` file. After that run Windower again and it should re-download the items resource. Let us know if that solves the issue.

**Comment by Saiken007** [comment]
Thank you! that resolved the problem!
