### ISSUE TITLE
Timers not properly calculating Phantom Roll duration.

### ISSUE THREAD

**Issue by ragingchaos** [Windower/Issues#857]
Similar to the earlier problem with BRD's Honor March, the following appear to be missing from COR's duration calculation.

Compensator ID: 21482  +20 Seconds
Camulus's Mantle ID : 26262 + 30 Seconds

Also if its a minor fix, RUN's Job Ability "Vivacious Pulse" is mislabeled as "Odyllic Subterfuge".

**Comment by funkworkz** [comment]
To add to Timers, here are new items that enhances BRD duration.

Brioso Roundlet +3 ID: 23384  -  Paeon +2 (before it was +1), so another 10%.
Brioso Cuffs +3 ID: 23518 - Lullaby +2 (before it was +1), so another 10%.
Brioso Slippers +2 ID: 23317 - Effect Duration +13
Brioso Slippers +3 ID: 23652 - Effect Duration +15

+3 gear can be augmented, but I would be very surprised if it affects durations...

**Comment by funkworkz** [comment]
There are also MANY new "Enhancing Magic Effect Duration" pieces that were just added and that are older which probably are not in the plugin.

**Comment by kuroganashi** [comment]
This is going to be a LONG Thread XD
But if needed my help let me know :)

Also some Rolls for COR on Rolltracker are not properly input or missing data such as Scholar's Roll / Ruinist Roll / ETC........

and Azure Sets been irregular with speed of setting spells. (Revising this one at the moment)

**Comment by Byrth** [comment]
I added a bunch, including 119AF+2/3, in a push earlier today. Have you tried the plugin today?

**Comment by funkworkz** [comment]
No I did not try. We had to bring up the issue last time for it to be updated, so that's why I figured nobody updated it yet.

**Comment by Byrth** [comment]
Well, this time I just noticed it was out of date and did it. Someone already found something that I forgot to add (WHM Regen Duration JPs) and we worked out where they go in the equation.

If you find things that don't work, I can fix those too. I do notice that you reported Lullaby.

Is Timers supposed to track debuff durations? I don't see any handling for it.

**Comment by ragingchaos** [comment]
It used to track debuff durations for things like Horde but I think it was removed quite a while ago. Imo it should be re-added to timers (for Horde/Sleepga) if its an easy request, for now I have been doing it with in gearswap.

**Comment by Byrth** [comment]
It's outside the scope of the plugin currently (was previously reported as a bug and removed) and while I'm not opposed to adding it I also don't want to do it.

I fixed the Vivacious Pulse -> Odyllic Subterfuge confusion just now in Timers version 3,7,4,16.

**Comment by Byrth** [comment]
It looks like Doubling Up might add a small amount of duration to rolls (~=1s per double up), which we would be unable to emulate in the plugin.

Other than that, COR roll durations seem to be accurate as of v3,7,4,17, which I just pushed live. Going to close this report now. Feel free to open a new one if you find some other way Timers is inaccurate.
