### ISSUE TITLE
[Timers] Ninjutsu buffs using incorrect base times

### ISSUE THREAD

**Issue by Solo177** [Windower/Issues#859]
Ninjutsu buffs seem to be properly taking into account Job Point Gift extended duration, but most are now using incorrect base times.

Yain: Ichi, Kakka: Ichi, and Myoshu: Ichi 3 minutes base -> 5 minutes base

Monomi: Ichi and Tonko: Ichi 3 minutes base -> 7 minutes base.

Tonko: Ni 5 minutes base -> 10 minutes base

Gakka: Ichi and Migawari: Ichi are correct as is.

**Comment by Byrth** [comment]
Okay, I made these adjustments to ResourceExtractor (we have to hardcode base durations) and they will be fixed the next time we have to push resources (next version update.) Here is a version for you now if you want it:
https://www.dropbox.com/s/5tehsddg8itplk4/spells.lua?dl=0

Thanks for the notification!
