### ISSUE TITLE
Windower4

### ISSUE THREAD

**Issue by edlo3108** [Windower/Issues#861]
it only Launder Downloading component sceern when I open windower4, and then windower4 quit and open , Launder Downloading component again again. how can I fix it? I already uninstall many time ; ; 
plz help , many thanks

**Comment by alphaONE2** [comment]
There was a version mismatch on the server. I've fixed it, but I'm not quite sure how you got stuck in the loop. The updater should only make one attempt to update...

In any case, I'm going to close this. If you're still experiencing the problem, please leave a comment and w'll reopen the issue.
