### ISSUE TITLE
Windower4 #861: Windower Update Loop

### ISSUE THREAD

**Issue by FFMotte** [Windower/Issues#868]
Since end of December my Windower tries to install an update and after that windower restart and update the same thing it never stops. Have to use the taskmanager to stop it.

I reinstalled the Windower three times now, but still have the same problem. In the update->temp folder i have lots of 929kbs files with the date 29.03.15. For every update try i get a new file.

Greetings 
Motte

**Comment by Byrth** [comment]
Are you on windows XP?

**Comment by alphaONE2** [comment]
I'm not sure how you got stuck in the loop, but you could try downloading the latest version manually from http://update.windower.net/live/Windower.exe

**Comment by FFMotte** [comment]
using windows 7.

cant reach the site http://update.windower.net/live/Windower.exe (network timeout)

**Comment by Byrth** [comment]
Yes, we opened a help ticket with our host and they have not replied.

**Comment by Byrth** [comment]
I assume this is fixed now that our host is back up.

**Comment by FFMotte** [comment]
yes thank you.
