### ISSUE TITLE
Windower addons tab and plugin tab blank

### ISSUE THREAD

**Issue by Okibi1** [Windower/Issues#869]
I had to unintall and reinstall Windower, and now when I open it, the addons do not load nor do the plugins. when clicking either, the page is blank. I use Win 10, and turned off Win Defender as well as Win firewalls. Can anyone help?

**Comment by joshk6656** [comment]
It looks like there is an issue with our servers. It is probably due to
that.

**Comment by z16** [comment]
It is. We opened a ticket with our host and are awaiting a reply.

**Comment by Okibi1** [comment]
Thank you very much, guys!

**Comment by Byrth** [comment]
Sure!

**Comment by Okibi1** [comment]
Thank you so much!

**Comment by Byrth** [comment]
We're back!

**Comment by Okibi1** [comment]
Yay, thank you!

Rebecca
