### ISSUE TITLE
Timers: Brioso, Moonbow, Moonbow +1 Whistles

### ISSUE THREAD

**Issue by funkworkz** [Windower/Issues#870]
These values need to be added to Timers. All Songs +1, +2 and +3. All are Additive and times for each +1 have not changed since before this months update.

10%/12 Seconds - Brioso Whistle - ID 26031
20%/24 Seconds - Moonbow Whistle - ID  26032
30%/36 Seconds - Moonbow +1 - ID 26033

**Comment by Byrth** [comment]
Done and pushed.
