### ISSUE TITLE
Battlemod not blocking some messages.

### ISSUE THREAD

**Issue by Selindrile** [Windower/Issues#873]
I think as of the last update, battemod isn't blocking a few of the messages even though it puts it's own version of the message in chat, making a duplicate, example:

![screenshot_1](https://cloud.githubusercontent.com/assets/8662562/24327432/efe40af4-1196-11e7-8dba-3a82458cbefb.png)

**Comment by Byrth** [comment]
I have been using Selh'teus in my party for the last 800 BCNMs and have never seen this.

I suspect you are using another addon that does action packet manipulation and it is returning the original packet instead of the modified one.

**Comment by Selindrile** [comment]
Thanks, I'll see if I can figure what might be causing it.

**Comment by Byrth** [comment]
Any luck with this?

**Comment by Selindrile** [comment]
I believe I know which addon it is, and it's an unofficial one.

**Comment by Byrth** [comment]
Okay, going to close this, then. For the record, you can fix this by having it modify and return the "modified" action packet (third argument to the incoming chunk function) instead of the "original" one (first argument).
