### ISSUE TITLE
Windower 4 will not launch Play Online Viewer after Windows 1010.0.15063.138 update

### ISSUE THREAD

**Issue by jonchan229** [Windower/Issues#876]

**Comment by jonchan229** [comment]
Windower 4 will not launch Play Online Viewer after Windows 10 10.0.15063.138 update

**Comment by z16** [comment]
Duplicate of #867, which has been fixed, but due to some issues we did not push the update yet. We're trying to work them out and will then push the new Windower version.

**Comment by Alandia87** [comment]
Ashita2 will good to  launch Play Online -v -

**Comment by shivaeyes** [comment]
News from #753 : no more crash during the transition between pol and ff. Seems to work well ^^ thx :)
