### ISSUE TITLE
textures not loading possibly config issue

### ISSUE THREAD

**Issue by Freakshow17303** [Windower/Issues#878]
just installed windower4 and FFXI again on new PC before I loaded addons the game loaded and w/ config loaded this happens
[config File here](https://pastebin.com/H4ZvnBTa)

[FFXI](http://imgur.com/a/MqCFV)
*Just double checked disabled Config and textures load in just fine* Edit

**Comment by alphaONE2** [comment]
You have `<ClippingPlane>` set to `0`; you should really never set it below `0.5`. Most computers these days, even very low-end ones, can handle settings of around `4` or `5` without any issues.
