### ISSUE TITLE
Windower 4 launch issue

### ISSUE THREAD

**Issue by Penfoldius** [Windower/Issues#880]
I reecently updated Windows 10 to Version 1703 and OS build 15063.138. whenever I go to launch  FFXI through Windower, Windower 4 window just disappears and nothing happens. I have tried to disable Game Mode as well and the prolem still persists. Are there any known issues in regard to this new update for Windows?

**Comment by alphaONE2** [comment]
Most likely a duplicate of #867. Try the [4.3 development build](http://update.windower.net/dev/Windower.exe).
