### ISSUE TITLE
Close Button Greyed out.

### ISSUE THREAD

**Issue by Yoshin79** [Windower/Issues#886]
Yesterday for some reason this started happening. After Playonline launches into Windower once signed in the Minimize and Maximize are Fine but the Close X button is Greyed out only way to close is to go to toolbar and right click.  Any Fix's for this?

**Comment by joshk6656** [comment]
This is working as intended, Windower now relies on SE's official windowed mode and that is what they do.

**Comment by z16** [comment]
For the record, `/shutdown` should be fixed now, so you can use that to exit the game, or `//terminate` if you're as impatient as me.
