### ISSUE TITLE
Hook 4.3.0.6 Windows 7 64 bit Dump report

### ISSUE THREAD

**Issue by Trizzoro** [Windower/Issues#892]
I am on Windows 7 - 64 bit. Everything worked perfectly until I downloaded the update this morning for Windower4.

Now when I log into POL through Windower4, I can open a character on FFXI, but after a random short period of time, POL will crash. After researching the issues on this forum and on FFXIAH.com, I downloaded the dumpsetup.exe, placed it into my Windower4 folder, ran it, and created a dump file. Beow is the DropBox link to that file.

Thank you.

https://www.dropbox.com/s/7rt7id4qm1em0aj/pol.exe.6920.dmp?dl=0

**Comment by z16** [comment]
The crash happens in the *ConsoleBG* plugin. This plugin has been discontinued and should no longer be used. The Windower launcher can't even load it anymore, so you must be loading it indirectly, for example through your `init.txt` file. Go to `Windower/scripts/init.txt` and see if you load any plugins in there. If you have, remove all of them and instead load them through the Windower launcher (run Windower and then select the *Plugins* tab, select which plugins you want to use there).

As for ConsoleBG, it has been replaced by an addon, same as [many other plugins](https://gist.github.com/z16/f73d0912e5c5ed02c58b).

**Comment by Trizzoro** [comment]
Wow ok, I'll try to find that. I don't even know what init.txt is, so I can assure yo I'm not smart enough to run plugins through anything other than hitting some button on Windower.
