### ISSUE TITLE
Unable to start Dumpsetup.exe program

### ISSUE THREAD

**Issue by Stratusx** [Windower/Issues#894]
I'v downloaded the Dumpsetup.exe program from https://github.com/Windower/Issues/wiki/Enabling-automatic-crash-dumps

Everytime i try to load it, it says: "Dumpsetup.exe is not a valid win32 application"

Not exactly a crash but more something thats not working at all to have a crash

OS Name	Microsoft Windows XP Professional
Version	5.1.2600 Service Pack 3 Build 2600
OS Manufacturer	Microsoft Corporation
System Name	OPTIPLEX-F6A882
System Manufacturer	Dell Inc.
System Model	OptiPlex 755
System Type	X86-based PC
Processor	x86 Family 6 Model 15 Stepping 13 GenuineIntel ~2394 Mhz
BIOS Version/Date	Dell Inc. A04, 5/11/2007
SMBIOS Version	2.5
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	Australia
Hardware Abstraction Layer	Version = "5.1.2600.5512 (xpsp.080413-2111)"
User Name	OPTIPLEX-F6A882\Admin
Time Zone	W. Australia Standard Time
Total Physical Memory	3,072.00 MB
Available Physical Memory	1.85 GB
Total Virtual Memory	2.00 GB
Available Virtual Memory	1.96 GB
Page File Space	4.82 GB
Page File	C:\pagefile.sys

**Comment by Nifim** [comment]
XP is not supported anymore
