### ISSUE TITLE
Crash on early AoE buffs with 4.3

### ISSUE THREAD

**Issue by zetaepyon** [Windower/Issues#895]
Doing party-wide buffs before everyone has fully loaded seems to occasionally cause a crash. I never saw this on 4.2, but it would occasionally crash the Timers plugin.

Reported by a Twitch user, replicated myself with a dualbox using Chaos Roll on corsair.

[pol.exe.13828.dmp.zip](https://github.com/Windower/Issues/files/967299/pol.exe.13828.dmp.zip)

**Comment by alkai** [comment]
Having the same issue, doesn't seem to happen if I fully load all inv before buffing, in this dump I was on cor doing phantom rolls.
4.3 dev build

http://s000.tinyupload.com/index.php?file_id=03824302909054716813

**Comment by Byrth** [comment]
Thanks for the reports.

**Comment by cairface** [comment]
I pushed an update to timers that should address this issue. I can no longer replicate it, at any rate. I'll wait for some feedback before closing this, though.

**Comment by cairface** [comment]
Closing this. Feel free to post here if it still happens.
