### ISSUE TITLE
Maximized Windower not filling entire screen

### ISSUE THREAD

**Issue by Fwelin** [Windower/Issues#897]
As of the update on 4/28/17, using the Window Mode "Window", when the screen is maximized (using the square maximize button on the upper right part of the window), it no longer completely fills the screen, leaving a distracting gap on each of the four sides where the desktop or program loaded behind is visible.  The OS being used is Windows 10.

**Comment by cairface** [comment]
Can you provide a picture? Not sure exactly what you mean. This isn't exactly a bug, but I may be able to address it.

**Comment by Nifim** [comment]
Not enough information, if the issue persists please come to our discord for support.
