### ISSUE TITLE
Random POL crash

### ISSUE THREAD

**Issue by Cloudstrafie** [Windower/Issues#902]
https://www.dropbox.com/s/slsor2uxgxsnrer/pol.exe.17104.dmp?dl=0

https://www.dropbox.com/s/zumghc68yu1f7zw/pol.exe.13932.dmp?dl=0

https://www.dropbox.com/s/sakk0q5uvlu9ywx/pol.exe.10900.dmp?dl=0

I believe one is where i logged in the wrong charater the other 2 are when POl randomly crashes

**Comment by cairface** [comment]
I should have fixed an issue in LuaCore that caused the first crash and will push it out today.

**Comment by cairface** [comment]
I pushed a fix for the only crash here I could actually address to the dev branch, and the others seem similar to hook crashes that have been addressed. 

Since there isn't really information to try to replicate the others, and they're non-specific, I'm going to close this.
