### ISSUE TITLE
Keybinds suddenly dissapearing.

### ISSUE THREAD

**Issue by Selindrile** [Windower/Issues#903]
I'm on the newest, dev version of windower.

After 30-45 seconds or so, all my keybinds are dissapearing.

I can reapply them and they work fine for 30-45 seconds, and then dissapear again.

Aliases still working, but keybinds just poof.

**Comment by Selindrile** [comment]
Byrth mentioned on FFXIAH that it was due to alt-tabbing and I can confirm that's my issue.

**Comment by cairface** [comment]
Thanks for the report, we will be looking into this today.

**Comment by cairface** [comment]
This should be fixed on the dev branch with hook version 4.3.0.8. Let us know!

**Comment by Selindrile** [comment]
Well, it's no longer happening every time I tab, but it has happened once so far today, unsure the trigger again.

**Comment by Selindrile** [comment]
Hasn't happened in quite a while, willing to call this closed.
