### ISSUE TITLE
Gamepad  simultaneously controls multiple instances after most recent update

### ISSUE THREAD

**Issue by PabstBlueRibbon** [Windower/Issues#904]
Keyboard controls work independently for multiple instances of FF; game pad inputs replicated on multiple instances making multiboxing impossible.

**Comment by Byrth** [comment]
Cair changed the default controller behavior to "all instances" in the launcher. Just flip it back to fix it (but then setkey won't work).

**Comment by PabstBlueRibbon** [comment]
Thank you very much!  I don't use setkey so I'll be fine, just glad I can play again.
