### ISSUE TITLE
Controller issue

### ISSUE THREAD

**Issue by Tarusparu** [Windower/Issues#905]
When playing with a controller and multi-boxing, any movements with the thumb sticks are sent to every character. Same with d-pad and the start/back buttons (Xbox 360 controller). I'm aware enable gamepad is on, but I need it for setkeys to work. Any ideas on how to handle it? :(

**Comment by cairface** [comment]
This is currently fixed on the -dev hook, but it is not pushed to live yet as it creates a slightly different issue.

Additionally, I discovered I was probably incorrect about setkey and the odd behavior with setkey happens regardless of that setting.

**Comment by SplintersLakshmi** [comment]
Having the same issue as Tarusparu.

**Comment by cairface** [comment]
This has been addressed, I am going to close this.

**Comment by SplintersLakshmi** [comment]
Problem still persists, even with dev hook.

**Comment by cairface** [comment]
What's your hook version? This has been explicitly addressed.

**Comment by SplintersLakshmi** [comment]
Hook 4.3.0.9, running as admin, all characters logged out and logged back in. Whatever left thumbstick and d-pad actions I take on 1st character is mirrored on second character. Tried on both regular and dev launchers.

**Comment by Byrth** [comment]
@SplintersLakshmi You need to change your setting in the launcher. The default to through.

**Comment by SplintersLakshmi** [comment]
Of course it was something that simple... Thanks, you guys rock!
