### ISSUE TITLE
PS2 Controller

### ISSUE THREAD

**Issue by Sarahangel74** [Windower/Issues#907]
Hi,
I have Problem with my PS2 Controller and multiboxing Screens.
When I switching Screens the char does a couple klicks, like changing my armor set by klick on macro bar, or klicks on targets in the range and does tell or an examining.
In fights its changing target and/or does any moves like Provoke out my macro bar. or curing waltz from bar.

PS: I downloadet the new windowr exe datei and reinstalling the windower4 but its no working

**Comment by cairface** [comment]
This has been addressed on the current dev build, and we are currently awaiting feedback before moving it to live.

**Comment by cairface** [comment]
Closing this, it's fixed on both dev and live.
