### ISSUE TITLE
PrtScn key not taking screenshots

### ISSUE THREAD

**Issue by 6969696969696969** [Windower/Issues#909]
windower.exe 4.3.6332.35270   hook.dll  4.3.0.11  win 10 x64 Creator's Update

EDIT
I had shut the game down for  while.  When I started it again it downloaded (DEV) hook 4.3.0.13.  This seems to have fixed this issue.

another edit
this new hook (4.3.0.13)...I have noticed something that I have never seen before...If I have Notepad open and I "ctrl s" to save the document I am working on, Windower/ffxi will show "/say" in the chat window (it also does the same thing with Internet Explorer...and I am sure any other program).

edit
I guess the "another edit" I mentioned here could be moved to "**Keyboard controls characters when all instances are out of focus**". - #911

one last edit (I hope)
I fired up Windower and got the 4.3.0.14 hook.  This seems to correct all of the issues I have mentioned here.  I would say you can close this issue.

**Comment by cairface** [comment]
Closed per request
