### ISSUE TITLE
New crash and windows hanging when alt tab or switchmon

### ISSUE THREAD

**Issue by Cloudstrafie** [Windower/Issues#910]
Starting to get new random crashes.when alt tab or switchmon,Even clicking on another window then going back to the game is causing issues with commands goign to any of my characters,It takes 5-10 seconds before they will accept any commands from my controller,Issue is with 4.3 and dev build, Also to note im on windows 10 with and without windows 10 creator update

https://www.dropbox.com/sh/xl7mklhm01biwnh/AAA_4rR3XH8nEflsGngXHIPVa?dl=0

**Comment by oleboy17** [comment]
Yep i am getting the exact same thing. Takes like 5 seconds after tabbing over before my character will take any commands from my controller. Also i have my PS4 controller setup to where it is running xpadder AND DS4 so that i can use the left AND right side of the touchpad as two seperate buttons. One is Alt+tab the other is alt+shift+tab. i play 3 characters. Except when i load DS4 now it goes haywire. Didnt do this before. Omg can we please just go back to the version before all this different stuff started happening. There was nothing wrong with it. Now i cannot play. I am paying $15 a month x3 and i can't even play.

**Comment by Cloudstrafie** [comment]
I can deal with the delay till they get it fixed just makes it much harder,Im in no rush im sure theyre under the gun trying to fix everything.Give them time im sure they will fix it.Just posting stuff here lets them know whats wrong

**Comment by oleboy17** [comment]
After messing around with it for a while i found out that you can change "Always enable gamepad" to ON and that fixes it

**Comment by oleboy17** [comment]
That setting used to make it go haywire when you tabbed over but its the right setting now apparently. And no more Alt macro palette. Sweeeet!

**Comment by Cloudstrafie** [comment]
i tried that and it makes all ym characters move at the same time :/

**Comment by Cloudstrafie** [comment]
Does that move all your characters?

**Comment by oleboy17** [comment]
No sure doesnt everything is working perfectly now. Are you running borderless window?

**Comment by Cloudstrafie** [comment]
nah running window 1200x1000

**Comment by oleboy17** [comment]
Thats probably why. Run it in borderless window. You can set alt tab to a controller button with xpadder

**Comment by Cloudstrafie** [comment]
just tried it again and it seems to be working thank you very much

**Comment by oleboy17** [comment]
But maybe its cuz in your ffxi settings you have activate controller in background on

**Comment by Cloudstrafie** [comment]
yea but im running it in windowed mode cuz im running at min 6 charaters so i have one for each screen

**Comment by Cloudstrafie** [comment]
My understanding that if its set in windower its set in FFXIconfig as well

**Comment by cairface** [comment]
Thanks for your reports. I believe I have fixed the input delay as of hook 4.3.0.15. Please give it a try.

**Comment by Cloudstrafie** [comment]
Did you just push this update?  I haven't tried to load windower to see if it's updated or not. Thanks k you very much for your help and all your hard work

**Comment by cairface** [comment]
Yes, it's on the dev branch as of about 10 minutes ago.

**Comment by Cloudstrafie** [comment]
Thank you very much, I'll try it out in the morning before I go to work.
