### ISSUE TITLE
Gamepad issue. 

### ISSUE THREAD

**Issue by oleboy17** [Windower/Issues#913]
Will one of the developers please get into contact with me asap. I will make a donation towards the fixing of windower4 and these gamepad issues tonight. I would love it if we could get the gamepad functionality back to exactly the way it was before. Idk if its been changed to where plugging a new gamepad in while the game is running will make it recognize it or what but it doesnt work. Please help me out I am right in the middle of some very important events and the game is essentially unplayable to me.

**Comment by oleboy17** [comment]
After messing around with it for a while i found out that you can change "Always enable gamepad" to ON and that fixes it  Everythings back to normal. Cool i'm happy

**Comment by Byrth** [comment]
Okay!
