### ISSUE TITLE
Unable to bind to windows key on second instance

### ISSUE THREAD

**Issue by radectheblm** [Windower/Issues#918]
First instance (Fullscreen) works correctly
Second instance (Windowed) any binds using the windows key are not working, result in only the other key being pressed, ie:
@1 > "1" in the input bar
@p > Odd behaviour. First instance will execute normally. Second will open windows "project" menu

Logging/reopening 2nd instance as fullscreen did not change - only first instance remains working

Hook 4.3.0.17
Windows 10, no creator update (yet)

**Comment by radectheblm** [comment]
For addition "What", as soon as I closed the 2nd instance, binds stopped working in the first. Reopening just pol and they started working.

**Comment by cairface** [comment]
This should be fixed as of hook 4.3.1.0, currently on the dev branch. Let me know if there are any issues. Thanks!
