### ISSUE TITLE
Keyboard input delay into FFXI chat/text input box

### ISSUE THREAD

**Issue by TRBrennan** [Windower/Issues#919]
Hi

Since Windower 4.3 after maybe 5~10minutes of running the game I get a keyboard typing delay which feels a lot like the old Microsoft word buffer when typing.

It took about a minute for a sentence like "Just did Ambu V1 WAR BLU GEO WHM SMN" to appear i nthe text box but I had already pressed enter to send it and got "Jus dd Ambu V" as all that was sent.

Running: Windows 10 Home 64 Bit,
i7 Processor
16 GB
NVIDIA GeForce GT 940M 2GB Graphics Card

I don't have creators update installed yet. it is only in FFXI and Windower 4.3 that I am having this issue.

I did not have this issue with any 4.2 Hook.

**Comment by cairface** [comment]
Sounds like you ended up with an old (or debug build) hook. Sorry about that, this should be fixed as Hook 4.3.1.0.
