### ISSUE TITLE
windowed mode window on v4.3 - Outline

### ISSUE THREAD

**Issue by Byrth** [Windower/Issues#920]
Someone sent me this: http://tinypic.com/view.php?pic=rvv80w&s=9

He says there's a bar on the left side of his borderless window in 4.3 that doesn't exist in 4.2 (and verified the settings). I suspect that Borderless Window just isn't working in v4.3 and he'd probably see a border on the other sides of the window if he moved it.

**Comment by alphaONE2** [comment]
Neither of those are borderless windowed mode, there's a title bar visible in both pictures. It should be pretty easy to fix regardless.

**Comment by Mercurian** [comment]
Yup my mistake it is "window" not border less, but that line only appeared after 4.3 nothing else changed

**Comment by Nifim** [comment]
The image is no longer available, and i do not believe this is still a problem.
