### ISSUE TITLE
2 accounts 

### ISSUE THREAD

**Issue by zadelia** [Windower/Issues#922]
how i can use 2 accounts to play with windower ? 
whenever i try to open a new window the older one forced to closed 
do i need to do something before using 2nd window ? 
thanks

**Comment by z16** [comment]
How is the old one forced to be closed? You don't need anything special, but you do need two different POL accounts, not just two different characters on the same account.

**Comment by zadelia** [comment]
yea i have another POL account not 2 characters 
what i do is , i open windower to play with my account 
so i need to open windower again to use the other account , when i do this the 1st one forced to close by windows it self

**Comment by alphaONE2** [comment]
This sounds like it might be a UAC problem?

**Comment by zadelia** [comment]
whats a UAC ? and how to fix it ?

**Comment by cairface** [comment]
https://www.google.com/search?q=UAC

**Comment by zadelia** [comment]
@cairface thank you very much it really helped me <3

**Comment by joshk6656** [comment]
Assuming if it helped, it fixed? Closing.
