### ISSUE TITLE
windower console "setkey" dose not work properly on an inactive form

### ISSUE THREAD

**Issue by fenrirtarutaru** [Windower/Issues#923]
OS: Windows10 Pro
OS version: 1607 (OS build 14393.1198)
Launcher: 4.3.6338.32792
Hook: 4.3.0.17

For example..
//setkey enter up
//setkey enter down
It is displayed on the console, but it does not work.
It is work property when form is active.

**Comment by fenrirtarutaru** [comment]
I think the cause is this

+2017-05-07
+----------
+Hook 4.3.0.14 - Cair
+* Disable keyboard input while window is in background

**Comment by cairface** [comment]
This should be fixed as of hook 4.3.1.0, currently on the dev branch. Let me know if there are any issues. Thanks!

**Comment by fenrirtarutaru** [comment]
thanks so much (・◇・)

**Comment by fenrirtarutaru** [comment]
I confirmed that it was properly corrected.
thanks so much (・◇・)
(a little freezes when switching forms.)
