### ISSUE TITLE
Installer Missing Windower.exe

### ISSUE THREAD

**Issue by DuckMan435** [Windower/Issues#925]
Went to launch today and the Windower.exe file went missing. Uninstalled, downloaded and attempted to re-install and the Windower.exe seems to not be part of the install.

**Comment by joshk6656** [comment]
Can you confirm your AV did not remove it?

**Comment by DuckMan435** [comment]
I disabled AV and its back after reinstall. I kneel to your debugging skills and I'm ashamed of mine.  Thank you @joshk6656!
