### ISSUE TITLE
I can't subscribe to windower forum.

### ISSUE THREAD

**Issue by VayuMiyoku** [Windower/Issues#926]
I need help in creating a new addon but registration fails everytime up to where it is supposed to send a verification code to email and that never happens. I tried several times with multiple mail addresses.

**Comment by Byrth** [comment]
This is difficult to understand.

Are you asking about making a forum account, or using the windower.register_event() function?

**Comment by VayuMiyoku** [comment]
I'm asking about making a forum account... it's somewhat broken... I don't get any verification code...

**Comment by CrimsonShadow2017** [comment]
I wanted to make a forum account as well. No luck.

**Comment by VayuMiyoku** [comment]
Still no clues. I need to ask information on making a plugin... and I cannot become a user...

**Comment by alphaONE2** [comment]
Ask on [Discord](https://discord.gg/v6pk6uy). And I wouldn't worry too much about signing up for our forums; they're probably not going to exist for much longer.
