### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by Selindrile** [Windower/Issues#928]
With newest Windower Dev version update, crashes every time when loading addons,
Crashdump: https://www.dropbox.com/s/v1dp60zsj90iwdd/crashdump.zip?dl=0

I tried to diagnose by turning all addons/plugins off, loads into game fine, but can also load every single addon/plugin and seems to use them all without issues, so can't figure out what one is causing it to crash when it's loaded while loading into FFXI.

More info, I tried writing them all as a script to load them ingame quickly, also crashed this way,
Crashdump: https://www.dropbox.com/s/jyl48i3j0necyw8/ingamecrash.zip?dl=0

This wasn't happening until the latest patch.

However splitting it into multiple scripts that loaded: 8 addons, 7 addons, 8 addons, allowed it to load.
Sometimes, sometimes not... it seems pauses are the key here, loading too much at once causes a crash, with some amount of wait time between the addons they all load fine.

**Comment by Selindrile** [comment]
More info, I tried writing them all as a script to load them ingame quickly, also crashed this way,
Crashdump: https://www.dropbox.com/s/jyl48i3j0necyw8/ingamecrash.zip?dl=0

This wasn't happening until the latest patch.

**Comment by Selindrile** [comment]
However splitting it into multiple scripts that loaded: 8 addons, 7 addons, 8 addons, allowed it to load.

**Comment by Selindrile** [comment]
New update, no change, script I have with waits between each addon loads fine, trying to load everything at once crashes.

**Comment by z16** [comment]
Can you try this LuaCore, and if it crashes give me the crash dump?

https://drive.google.com/file/d/0B1-GYvFFRpK6R1EwNFlwY3M2ODg/view?usp=sharing

It's a debug version which means it will be pretty slow, but I only need you to get me a dump with this, it should be more accurate than the others.

**Comment by Selindrile** [comment]
Didn't load the luacore at all with that debug version, when attempting, I get the message:

Error: luacore - Failed to load plugin - (126) Module not found.

**Comment by z16** [comment]
@Selindrile Issue #930 explains that it happens on a character that does not have all jobs unlocked. Is that the case for you?

**Comment by Selindrile** [comment]
Only one character, and it has all jobs unlocked.

**Comment by alkai** [comment]
Same issue, can get around it just like OP describe.
No db, everything unlocked. Tried both normal and dev ver.
http://s000.tinyupload.com/?file_id=04358744886296883837

**Comment by Selindrile** [comment]
When I try to load addons very quickly it always crashes, loading them singly is usually fine, but occasionally I crash when loading a single addon even, I can't really find a rhyme or reason, it's not a specific addon, and it's not all the time, when loading singly, but trying to load a lot of addons at once crashes every time.

**Comment by novio** [comment]
Encountering the same issue. It will load two of my characters fine, the other two however will always crash regardless of what I do. I've disabled all addons, plugins etc. 

The two characters in question have multiple mules so it may be related to the unlocked ordeal. I've tried both the latest version of windower and a rolled back version but to no avail. 

I don't want to have to use ashita or vanilla, I love windower :(

Dump file (472mb): 
https://ufile.io/doy5q

**Comment by z16** [comment]
For the record, you can (and probably should) use the live version if you're experiencing this issue. I tried looking into it with the help of someone else who experienced the same issue, but I couldn't get to the bottom of it. I'll go look into it some more when I get back, but I'm on vacation and don't have access to my code at the moment. I'll be back about a week from now.

**Comment by Selindrile** [comment]
Thanks, I was staying on it to see if I could learn anything else/waiting for more information to be requested, but I'll switch to live then for now.

**Comment by Selindrile** [comment]
I took my sweet time transferring over to live, but this is an issue on live as well.
I still very frequently crash when loading addons.
Loading them one at a time with delay between each, especially before actually logging into the game increases my chance of not-crashing, but it still happens sometimes.

**Comment by Selindrile** [comment]
Is there any more data I can provide to assist anything here? Loading any addon is still a crap shoot and even with my script that loads one addon at a time with space in between them, I still have about a good chance on loading up those addons to crash, and every time I load an addon in game I take a chance on crashing, it's really really frustrating.

**Comment by z16** [comment]
I looked into it quite a bit since then but still couldn't figure out what's going on. I fear I'll have to rewrite addon initialization in the hopes of fixing it. But are you absolutely sure it happens on live as well? What version does your LuaCore on the live branch have?

**Comment by Selindrile** [comment]
I did, however, I had copied a lot of the files from my dev branch into live to avoid having to reset all my settings, I'll do a cleaner test and get back to you.

**Comment by Selindrile** [comment]
Yeah I'm not crashing on live now, I'm assuming when I copied over files from my dev\addons\libs folder to my live\addons\live folder, I copied whatever file had the issue when doing that, I honestly thought I had only copied over the libs files that I had added to that folder, (lorand's and I think another coder's, that I use to make their addons work) but I guess I got more than just that.

My apologies.

**Comment by z16** [comment]
No worries, at least that helps narrow it down, as I can focus on what changed between live and dev.

**Comment by z16** [comment]
We pushed a new version to the dev build. Can you see if it works now?
