### ISSUE TITLE
BUG: luacore not found

### ISSUE THREAD

**Issue by deadman80** [Windower/Issues#929]
Since yesterday, I've been getting the following error:
Error: luacore- Failed to load plugin - (126) Module not found

Deleted/redownloaded the dll and it's visible in the folder.

Same error has been happening with Sandbox for me for a while, but no luacore = no addons, which is very annoying.

**Comment by Byrth** [comment]
Are you on -dev or -live?

What is your OS?

**Comment by deadman80** [comment]
Win10, normally use -dev, but the issue is occurring in -live as well for me.

**Comment by cairface** [comment]
Just to leave some information here: I've had sporadic reports of this still happening with plugins we're compiling with VS2017.
