### ISSUE TITLE
Crash on load, dualbox

### ISSUE THREAD

**Issue by aja311** [Windower/Issues#930]
My issue is similar to Selindrile's issue here: https://github.com/Windower/Issues/issues/928

Except, I can log in one character just fine. When I try to log in my second account it crashes every time.
Here are some crash dumps.
https://www.dropbox.com/sh/vb2j9cd6h88bxy4/AAA297dR4uZ7mjEL4cpZJoVPa?dl=0

I am on Windower Dev version and Windows 7- 64 bit.

**Comment by joshk6656** [comment]
Does the character that works by chance have all jobs unlocked, and the
others do not!

**Comment by aja311** [comment]
Yes.

**Comment by aja311** [comment]
Well... unlocked the one job missing on second account. Working fine now. Thanks.

**Comment by joshk6656** [comment]
Thanks for helping us pinpoint the issue, will close this when it is
resolved.

**Comment by z16** [comment]
Unfortunately I'm having trouble reproducing it, even with characters that don't have all jobs unlocked. Do you still have an account/character you can reproduce the crash on?

**Comment by aja311** [comment]
I have a friend's account I can log into, I don't think he has all jobs unlocked. I will test now and see.

**Comment by aja311** [comment]
https://www.dropbox.com/s/pn6sfdp258537nh/pol.exe.5584.dmp?dl=0

Ok, crashed trying to log that account in. Above is link to the dump file created.

**Comment by aja311** [comment]
Now tried logging in my second account that I unlocked the missing job on and crashed as well.
Here is the link to that.
https://www.dropbox.com/s/pll43o5sdjfbme5/pol.exe.4532.dmp?dl=0

**Comment by aja311** [comment]
Also, when I log my alt account in first and then my main account, it seems to be working. At least this one time I have tried so far.

**Comment by aja311** [comment]
And, by the way, switching back to non-dev Windower, still crashes sometimes when trying to log in a second account. Usually, second or third try it will work though.

**Comment by z16** [comment]
That should be a different issue then. The next time that happens, could you provide another crash dump for it please?

**Comment by aja311** [comment]
https://www.dropbox.com/sh/6jv77zycu9na3ra/AADh6tb8LovnSq4c7ic9kToLa?dl=0

Here are 3 dumps from the crashes tonight.

**Comment by aja311** [comment]
https://www.dropbox.com/sh/648c9c3x8p8gfpl/AAANSCR6ffA584XIyfLW_RMka?dl=0

More. Also crashing while trying to load a plugin while already in game, that one is dump #4124 included in that folder.

**Comment by aja311** [comment]
Can close this, I have resolved the issue.
