### ISSUE TITLE
POL crashing on Wasp Sting

### ISSUE THREAD

**Issue by Hokuten85** [Windower/Issues#932]
POL crashing when someone uses Wasp Sting.  It doesn't seem to affect anyone else, but I cannot determine what is different about my system.  It also doesn't seem to effect any other WS.  I've done a POL file check/repair.

I have all plugins and addons turned off.

Win10 Pro
Version 1703
OS Build 15063.296

[pol.exe.9124.dmp.zip](https://github.com/Windower/Issues/files/1049360/pol.exe.9124.dmp.zip)

**Comment by Byrth** [comment]
This is very strange and you likely have a corrupted .dat or something.

**Comment by z16** [comment]
He did report file check not helping his issue, which decreases the likelihood of it being DAT related :/ A bit at a loss here, but as Byrth said, try it without Windower to be sure.

**Comment by Hokuten85** [comment]
It ended up being something with Level sync.  Whenever someone had gear that was being scaled down, and then they did a Wasp Sting or Gust Slash it crashed me.  I used POLUtils to find the gear and ws dats and deleted them, and then did a file check again, which replaced them.  Seems to be working now, though I'm still not certain what was causing the issue.
