### ISSUE TITLE
player.inventory["Item Name"].count returning unexpected value on Chrono Bullet.

### ISSUE THREAD

**Issue by Selindrile** [Windower/Issues#934]
player.inventory["Item Name"].count seems to be working fine for most things, however, when
trying to use it on the item "Chrono Bullet" instead of returning the number currently in my inventory, it returns a much larger number that constantly increases over time, despite my inventory not changing.

I'm not sure if it's broken for any other items.

**Comment by z16** [comment]
I assume this is a GearSwap thing, as regular Windower functions have no notion of that kind of inventory (or player, for that matter). Assigning this to you @Byrth.

**Comment by Selindrile** [comment]
Yes, it's within Gearswap, sorry I didn't think to specify.

**Comment by z16** [comment]
Just for the record for the future, Byrth has his [own issue tracker](https://github.com/Byrth/Lua-Byrth/issues) where he handles most of GS-related bugs, as this tracker is meant for issues with hook/plugins or the Lua API provided by *LuaCore*.

**Comment by Selindrile** [comment]
Ah, noted and thank you.

**Comment by Byrth** [comment]
Okay, I fixed it on -dev. Going to see if there's anything else I can fix today before pushing it live.
