### ISSUE TITLE
Windower "Closing" without Launching PoL

### ISSUE THREAD

**Issue by ctownwoody** [Windower/Issues#935]
Windower 4 and the dev version are starting to launch, connecting with the private server, pausing at Sending Account ID, and then "Closing", and then the program closes.  No crash log.  I've messed with about every setting I know how to, double-checked and reloaded.
It worked for a while and now does not.  
What should I do or document?

**Comment by z16** [comment]
Did you figure it out?

**Comment by ctownwoody** [comment]
Yeah, the issue was that I deleted 0.Dat too soon, so it didn't patch/repair right.

________________________________
