### ISSUE TITLE
Gearswap not working.

### ISSUE THREAD

**Issue by Diosax** [Windower/Issues#936]
Marcros doesn't changing gear, I need to do it manually to let gs change all my gear. If I click a macro it doesn't work. For example on WHM if I cast  cure touching any macro gs not change my gear, but If I cast cure by the spell list manually it does.

**Comment by cairface** [comment]
You need to use /console exec "command" in macros instead of // syntax. SquareEnix specifically disabled the use of // in macros. Also, in the future, addon issues belong on the addon author's issue tracker as linked in the launcher.
