### ISSUE TITLE
scoreboard not work

### ISSUE THREAD

**Issue by dynette** [Windower/Issues#937]
nothing cons when I typ //sb rs acc p  
![j1a2znozaehzw 55fgs6cr5](https://user-images.githubusercontent.com/29626837/27430352-d7a18a0a-577a-11e7-9b35-96d4aa59efcd.png)

**Comment by cairface** [comment]
This belongs on the addon's issue tracker: https://github.com/jerryhebert/Lua/issues

Also, some more information would be great when you repost it. You appear to be in town, where you are obviously not in battle.
