### ISSUE TITLE
Sandbox - Chatlog Issues

### ISSUE THREAD

**Issue by terravcota** [Windower/Issues#940]
Ever since the last update I've been having issues with chat logs - losing chat logs, chat logs getting mixed together and crashing while looking at chatlogs. Prior to the last update, I'd very rarely have any chat log issues since Sandbox was introduced.

When I asked on AH I was asked to unload/load to check version but //unload sandbox says Plugin not loaded and //load sandbox says Module not found. It's on in my Windower profile and I have a Sandbox.dll in my plugins folder - modified 7/3/2017 4:56 PM, 125KB. I have tried deleting the plugin from the folder and redownloading with no success.

Looking in the TEMP folder, it looks like all new files are being put in the base TEMP directory, whereas previous files were being put into TEMP\character-specific folders.

**Comment by joshk6656** [comment]
Try manually downloading this. Something may be happening with your AV or the download isn't fully downloading for some reason.

https://drive.google.com/open?id=0B-pYR7Oh0iozTElBeGZiS3NvLU0

**Comment by terravcota** [comment]
Any special instructions for loading? Copied the file into plugins and still getting the same Module not found error. I didn't log out, though.

FYI - The size on disk from both what you linked and what is automatically being downloaded are the same.

**Comment by joshk6656** [comment]
No, that's loading just fine for me. I wonder if your AV or something is preventing it from working? It does hook some functions that windows and or your AV could possibly block.

What OS are you on?

**Comment by terravcota** [comment]
Windows 7. I turned off my AV (crashed myself in the process) and still failing to load. Any ideas?

**Comment by joshk6656** [comment]
Are there any error codes along with the module not found error or does it
just say module not found?

**Comment by terravcota** [comment]
Error: sandbox - Failed to load plugin - (126) Module not found

My ls mate is having a similar issue with Sandbox not working, but he's had the issue longer than I've had it. I asked him to load it manually and he says it's not loading. Windows 8.1. I asked him to check w/ his antivirus off after we finish events.

**Comment by joshk6656** [comment]
I am thinking some kind of dependency is missing, but I'm not sure why it would suddenly stop working.

I do have a feeling @cairface may have rebuilt this with VS2017 when he pushed the last update...

One last idea, could you download this:

http://www.dependencywalker.com/depends22_x86.zip

When you run it, hit open and point it to sandbox.dll.

Click around in there and look for anything that looks like an error

**Comment by terravcota** [comment]
Error: At least one required implicit or forwarded dependency was not found.
MSVCP140.DLL
VCRUNTIME140.DLL

**Comment by joshk6656** [comment]
Go to....

Start > Programs and Features, can you list which c++ redists you have installed?

![image](https://user-images.githubusercontent.com/489101/28244402-0d94e6b0-69b0-11e7-8a7f-8c6073e1df22.png)

**Comment by joshk6656** [comment]
Also, @cairface  just recompiled. Could you try this?

https://www.dropbox.com/s/blnkzy5cvxoqm7s/Sandbox.dll?dl=0

**Comment by terravcota** [comment]
That loads!

You're right - I don't have the 2015 redistributable. Thanks for all the help!

**Comment by joshk6656** [comment]
Did you install the 2015 stuff, or just use that dll?

**Comment by terravcota** [comment]
I just downloaded the dll for now but plan to download 2015 later.

**Comment by joshk6656** [comment]
Glad to help! Closing this, you can send that to your friend, but it will get pushed to live eventually.
