### ISSUE TITLE
IPC Causes Random Crashes

### ISSUE THREAD

**Issue by Reataru** [Windower/Issues#941]
Been havin' some seemingly random crashes as of late while playin' the game with windowerer.

**Issue:** 

Durin' battle, game will start movin' at a stand-still while I get an error message that pops up. (I have not been able to see the message I'm afraid as I'm usually clickin' enter for game and it hits okay.  After this it gives the "FFXI is unresponded" and what not message, click okay/yes to close program.  At that point, the game is frozen.   When this happens the mouse is not showin' unless I get it to be on top of the error message (if I move it off the box, mouse icon vanishes).

I imagine this is related, though may be a seperate issue also.  I currently use two monitors and occasionally when I ALT+TAB from non-game monitor to FFXI (full-screen), the game acts like I'm holdin' down the the right mouse button.  If I move the mouse, player moves (has the icon for it as well).  I can fix that by hittin' the right mouse button though it does keep happenin'.  

While tryin' to figure out the problem myself, I have had this happen durin' intense fights (spammin' macros and button pushes) and durin' auto-attack and watch periods. 

Have tried unloadin' all plugin/luas (with the three exceptions below) and still had the crash:

-Gearswap
-Config
-Scoreboard

I have not tried playin' vanilla FFXI (Not sure I know how heh... >>;), though if the information I've provided doesn't help, I can attempt to and see if that solves it.

**Operating System:**

Windows 10 Home 64 Bit

**Windower Version;**

4.3.6394.32679

**Windower Settings:**

<?xml version="1.0" encoding="utf-8"?>
<settings>
  <autoload>
    <addon>battlemod</addon>
    <addon>findAll</addon>
    <addon>linker</addon>
    <addon>rolltracker</addon>
    <addon>azureSets</addon>
    <addon>shortcuts</addon>
    <addon>DressUp</addon>
    <addon>distance</addon>
    <addon>Silence</addon>
    <addon>pointwatch</addon>
    <addon>GearSwap</addon>
    <addon>zonetimer</addon>
    <addon>scoreboard</addon>
    <addon>PetTP</addon>
    <addon>SpeedChecker</addon>
    <addon>TParty</addon>
    <addon>translate</addon>
    <addon>update</addon>
    <addon>organizer</addon>
    <addon>ConsoleBG</addon>
    <addon>instaLS</addon>
    <addon>autocontrol</addon>
    <addon>timestamp</addon>
    <addon>setbgm</addon>
    <plugin>Cancel</plugin>
    <plugin>ChatLink</plugin>
    <plugin>ChatMon</plugin>
    <plugin>DrawDistance</plugin>
    <plugin>Find</plugin>
    <plugin>FFXIDB</plugin>
    <plugin>TParty</plugin>
    <plugin>ConsoleBG</plugin>
    <plugin>Timers</plugin>
    <plugin>JaZero</plugin>
    <plugin>Config</plugin>
    <plugin>Guildwork</plugin>
    <plugin>Sandbox</plugin>
  </autoload>
  <profile name="">
    <consolekey>Insert</consolekey>
    <mipmaplevel>1</mipmaplevel>
    <uiscale>1</uiscale>
    <supersampling>2</supersampling>
  </profile>
  <profile name="Reazher">
    <consolekey>Insert</consolekey>
    <uiscale>1</uiscale>
  </profile>
</settings>

**Crash Dumps**

Presumin' I haven't messed up on how to get this to work (Moved DumpSetup.exe into windower folder, ran it and took the files from windower/dumps/), here are three I have managed to acquire for this.

[Crash Dump.zip](https://github.com/Windower/Issues/files/1167849/Crash.Dump.zip)

**Note for the Crash dump file, I wasn't able to put them no seperately or in as a .rar file.  Had a roommate say if I just changed the extension to .zip it would still work.  Not sure on that myself, so if no luck, I imagine I can find winzip again and install for it. lol**

**Comment by cairface** [comment]
Your zip file won't open. :disappointed:

**Comment by Reataru** [comment]
Yeah, my fault.  Was wantin' to avoid downloadin' another program since I use .rar for stuff.  Fixin' this now.

[Crash Dump.zip](https://github.com/Windower/Issues/files/1171916/Crash.Dump.zip)
[Crash Dump2.zip](https://github.com/Windower/Issues/files/1171919/Crash.Dump2.zip)

Uploaded the same files twice.  Quite possible I goofed and kept the files I made with changin' file extentions... >.<  Since I don't know, both are in here just in case.  Sorry for the goof up. ; ;

**Comment by Reataru** [comment]
Alrighty, had another crash where I could actually read the error message.

Microsoft visual c++ runtime library

program: C:\Program....

This application has requested the runtime to terminate it in an unusual way.  Please contact support team for assistance.

Here is the crash dump.

[Dump File.zip](https://github.com/Windower/Issues/files/1185424/Dump.File.zip)

**Comment by cairthenn** [comment]
Closing and leaving #978 open until it's fixed (soon)
