### ISSUE TITLE
Fresh install on SSD and now a second windower instance start kills both instances.

### ISSUE THREAD

**Issue by Iwaio** [Windower/Issues#943]
I don't  remember having to set any preference to allow two instances on my last install before disk crash and burn.  But if there is a field and value could you please help.  I have some vision problems since my vitreous detachment and my eyes tire easily.

**Comment by z16** [comment]
There is no such thing, it should work without configuration. How exactly does it kill it? Does the other instance just disappear? Crash with an error?

**Comment by Iwaio** [comment]
The POL dies here is the data:
  Problem Event Name: APPCRASH
  Application Name: pol.exe
  Application Version: 1.18.13.0
  Application Timestamp: 4e3bcddc
  Fault Module Name: d3d8.dll
  Fault Module Version: 6.1.7600.16385
  Fault Module Timestamp: 4a5bd9a7
  Exception Code: c0000005
  Exception Offset: 0004bf62
  OS Version: 6.1.7601.2.1.0.768.3
  Locale ID: 1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

**Comment by Iwaio** [comment]
Wait on this just notices Windows update had failed on all of its NET
Framework 4 update attempts so attempting to install them again.

**Comment by cairface** [comment]
DirectX crashes are usually indicative of something going wrong with your display drivers or UAC settings.

**Comment by Schliematt** [comment]
I used to be able to use the default profile for both me and my mule, but occasionally It will crash both when id start up the second instance kinda like how you described. Try making a second profile in launcher and use that for 2nd instance and see if it works. I never could figure out why it would do that, but it would sometimes fix itself and go back to normal. just an idea.
