### ISSUE TITLE
Stops responding when switching from pol for xi

### ISSUE THREAD

**Issue by Dominionofgod** [Windower/Issues#944]
im working on switching over from a hdd to a samsung ssd that i got. I did a fresh install of OS and programs. Took a while, and a few unexpected issues, but i finally got everything working except windower.

https://www.youtube.com/watch?v=M_DAwCp7l0U

Thats what happens every time i try to use windower. It does not occur loading up with just ffxi. Running windows 7 pro.

Any ideas how to get this working right? - I seem to recall reading issues like this before, but i dont remember when or where. And to much RL stuff going on atm; my memory is stretched even thinner then usual. Havnt even logged into game for anything other then log in points in a couple weeks. Non the less, id like to get it working for when i can.

**Comment by Dominionofgod** [comment]
crash dump file
https://www.dropbox.com/s/dmc7crqx31c1x3o/pol.exe.2328.dmp?dl=0

**Comment by Dominionofgod** [comment]
well this is a bit bazaar..

Iv had no luck getting this to work. I havnt even bothered the last couple days because i had no new ideas. Well i loaded up the ssd today. I went to ffxi (desktop icon) and clicked on Troubleshoot compatibility and saved the recommended chances (which iv done before). Then i did the same thing to the windower icon (which iv done before). Then clicked on ffxi icon Run as administrator then exited out (which iv done before). Then the same thing on windower (which iv done before.

All of which iv done before (if u havnt guessed yet.) But it loaded up all the way into the game. I was shocked. So i loged out of the game and tried it again by just clicking on the windower icon (not going through all that). Wasnt sure if all that settings would save each time, or if starting up was some anomaly or.. what ever. But it loaded up again. So i restart computer entirely and tried it again. And it loaded up.

So it seems to suddenly be working.. I dont know why. But it is. And ill gladly accept that.

The only other thing i can think of is my virus software. It was on trial version on my ssd since i hadnt switched the license over from my hhd yet. Wanted to get everything working first. Now the trial is expired. But i had previously tried shutting down all virus software to start windower up and it made no difference; still had error. So i still have no idea.

**Comment by z16** [comment]
Wouldn't surprise me at all if the anti virus software was the cause, it's been known to interfere with Windower occasionally. Although usually it would say it had done something to Windower... but glad to hear it's working for you.

And by the way, none of the steps you mentioned should be required for Windower. If you do happen to figure out that any one of them was responsible for it working again for you, please let us know.
