### ISSUE TITLE
Windower 4.3 wont run in windowed mode

### ISSUE THREAD

**Issue by ghost** [Windower/Issues#945]
I cant get windower to start in windowed mode or borderless window, for some reason only works in windowed mode on windows 10. All i get is a black screen with music playing, if i press alt + tab i can see the game running in the preview window, and i cant select any other tabs the black screen stays there till i ctrl + alt + del to make it crash. I tried to sign up for there forum but its not sending me the verification email.

**Comment by Nekseus** [comment]
Are you using DgVoodoo?

**Comment by Nifim** [comment]
not enough information, and user now a ghost.
