### ISSUE TITLE
Windower 4 Win 10 Will close without opening POL

### ISSUE THREAD

**Issue by LefeinNoel** [Windower/Issues#946]
I have failed repeatedly to get Windower 4 to open PoL.

I will launch Windower, which will just close no errors or anything. No idea how to fix it. 

I can't give any information because there is nothing to give. No errors and PoL works fine when I just launch it.

I also need to add, PoL never attempts to launch. I am assuming it's looking for my PoL in the wrong place. I just don't know how to change where it looks for it.

**Comment by ancientmithra** [comment]
same prob here someone help

**Comment by z16** [comment]
Duplicate of #942.
