### ISSUE TITLE
windower not starting POL, tried reinstalling all :( wat do?

### ISSUE THREAD

**Issue by ancientmithra** [Windower/Issues#948]
![wont start](https://user-images.githubusercontent.com/32412349/31044925-f85334cc-a5a6-11e7-874c-bc1f7b805767.jpeg)

**Comment by alphaONE2** [comment]
This doesn't look like Windows. Are you trying to run Windower on a Mac?

**Comment by ancientmithra** [comment]
oh yes, I am using crossover on mac.

**Comment by alphaONE2** [comment]
Sorry to say, but this lands very much in the unsupported category.

I don't have any experience with Crossover. All I really know about it is it's a fork of Wine. Windower 4 is unlikely to *ever* work on Wine for a number of reasons, and for those same reasons, it probably isn't ever going to work on Crossover or Cedega, either.

**Comment by ancientmithra** [comment]
;_; im able to work POL and FFXI, i was wondering if there was somethign I could try to make it work (windower) after all, ithe entire game works:D

Best wishes, mes meilleurs voeux, mis mas estimados pensamientos,
Dr Carlos Faviel Font MD
