### ISSUE TITLE
Findall doesn't find Ambuscade Rings in storage slips.

### ISSUE THREAD

**Issue by Selindrile** [Windower/Issues#951]
Resources are updated, findall doesn't seem to find the old or new ambuscade rings in storage slips.

**Comment by zetaepyon** [comment]
Looks like Slip 23 in the slips library hasn't been updated for any of the Ambuscade +2 gear or rings. I've submitted a pull request that should fix this.

**Comment by zetaepyon** [comment]
Merged to live with [Lua PR #1580](https://github.com/Windower/Lua/pull/1580)
