### ISSUE TITLE
Odd Crash on New Windows Update

### ISSUE THREAD

**Issue by DracoRyx** [Windower/Issues#952]
I'm using Windows 10, the new Fall Creators Update build 1709. Now, anytime I try to run Windower, the program runs fine but crashes on the transition to PlayOnline. POL itself runs perfectly fine. Attached is Windows Event Viewer stuff I could find on the program. I've tried various compatibility modes and running the program as admin.

https://pastebin.com/Q1VBKxC6

https://pastebin.com/twgTsmZk

[crash.log](https://github.com/Windower/Issues/files/1403955/crash.log)

**Comment by z16** [comment]
Duplicate of #942.
