### ISSUE TITLE
Keyboard Wrapper causes lags spikes on window change

### ISSUE THREAD

**Issue by cairface** [Windower/Issues#955]

**Comment by cairface** [comment]
Hook 4.3.3.0+ addresses this

**Comment by MartelRagnarok** [comment]
The lag is gone! Thank you. However... I'm experiencing some keyboard oddities.

Some keys seem to be triggering both their original functions, and what ever I bind them to. So far F7~F10 do this. Also had a couple hiccups binding over previous binds had to unbind then rebind to get some to stick

Other weirdness.
Ctrl+V is toggling me between first/3rd person camera.
Ctrl+Y seems to be effectively pressing enter

It sorta seems like it's trying to use the compact keyboard, but my menu settings clearly show I'm using full keyboard...
