### ISSUE TITLE
POL crash when game is alt-tabbed.

### ISSUE THREAD

**Issue by etcetcetcplusplus** [Windower/Issues#958]
This happens at random times but only when the game is alt-tabbed.

Here's a dump:
https://mega.nz/#!rRUCDBiZ!RJoMJbOb6tFquy9RNODyLUcG95xtE4Kg270mEVgLoL0

**Comment by z16** [comment]
Is this a recent issue?

**Comment by etcetcetcplusplus** [comment]
Yes, this never occurred for months. I alt-tabbed for an hour but didn't crash despite crashing twice within 15mins this morning when alt-tabbed.

**Comment by z16** [comment]
Are you playing on the dev version of Windower, or the live version? You can check by right-clicking your `Windower.exe` file and checking the version.

**Comment by z16** [comment]
Looks like you're on the live version, so it should not be due to our recent changes. The crash dump is not very helpful unfortunately, but we'll see what we can figure out. In the meantime, let us know if it keeps happening for you.

**Comment by cairface** [comment]
Could you give the -dev version of windower a try? I'm not certain it's related, but I recently changed some thing the windower would do if it was a background process to prevent input from reaching it, so it could help.

http://update.windower.net/dev/Windower.exe
