### ISSUE TITLE
Distanceplus error line 337

### ISSUE THREAD

**Issue by amadeus1171** [Windower/Issues#959]
DistancePlus: Lua runtime error: DistancePlus/DistancePlus.lua:337 atempt to index local 'command' (a nil value)

When I hit my FFXI macro /pet fight <t> with the HQ rabbit, PonderingPeter, I get this error.  I'm in BR salvage.

**Comment by z16** [comment]
The `DistancePlus` addon reacts to the `//dp` command. Are you using that for your macro? The error message seems to indicate that you're using the `//dp` command without any arguments, which would result in your given error.

**Comment by amadeus1171** [comment]
Nope.  Just /pet fight <t>

**Comment by amadeus1171** [comment]
Oh FFS!!!!!!  I have /console dp in there for some reason. x.x

**Comment by z16** [comment]
That would do it :) Gonna close this, *DistancePlus* could probably handle that error more gracefully, but it's a user error either way.
