### ISSUE TITLE
IPC Communication Issues

### ISSUE THREAD

**Issue by Schliematt** [Windower/Issues#962]
Its been a couple months since i played FFXI. all my gearswap stuff was working last i played. But coming back this week i have found that a couple things arent working perfectly with my dual boxing... I keybind to control F2 a command to make the other character follow me. Its the same command for both characters because it is in an included file. I put an addtochat in the command to make sure it is actually being called and it is. But it isnt sending the follow command through send. The character i logged on first doesnt seem to be able to tell the other to follow, but the second character is able to. I havent checked if i log in in reverse order if it works the same yet. So id guess it was an issue with send or keybinds, not sure?

**Comment by cairface** [comment]
For self reference, the problem is easily recreated:

- Open two characters
- Crash one
- Any logged in characters at this point cannot communicate with new logins

**Comment by cairthenn** [comment]
Closing this and leaving #978 open, but this should be resolved soon
