### ISSUE TITLE
Crash on ffxi title screen unless I use no addons

### ISSUE THREAD

**Issue by alkai** [Windower/Issues#963]
Windower4, live version, Win7 64bit.

Works fine if I load addons one by one manually once in game.

http://s000.tinyupload.com/?file_id=98954506486625460623

**Comment by alkai** [comment]
Update- Manually loading addons in-game also seem to crash game occasionally.
Can provide more crash reports if requested.

**Comment by Nifim** [comment]
If issue still exist please come to our discord for support.
