### ISSUE TITLE
Changing automatically the appropriate ClippingPlane for each zone

### ISSUE THREAD

**Issue by VayuMiyoku** [Windower/Issues#967]
I can't register nor write to the forum, so I write it here. 

I need help with AutoExec, I want Clipping Plane to set automatically at a pre-determined value each time I change a zone.

I tried to make it this way but it doesn't work:

```
<?xml version="1.0" ?>
<autoexec>
<!-- This is an autocreated AutoExec file. the next line is commented out and not going to be ran, its to show an example on how to add commands to this file. -->
<!--register event="login" silent="true" runonce="true">load expwatch</register-->
<register event="zone_La_Theine_Plateau" silent="false" runonce="false">config ClippingPlane 9</register>
<register event="zone_Beaucedine_Glacier" silent="false" runonce="false">config ClippingPlane 9</register>
<register event="zone_Meriphataud_Mountains" silent="false" runonce="false">config ClippingPlane 6</register>
<register event="zone_Sauromugue_Champaign" silent="false" runonce="false">config ClippingPlane 4</register>
<register event="zone_Konschtat_Highlands" silent="false" runonce="false">config ClippingPlane 3</register>
<register event="zone_West_Ronfaure" silent="false" runonce="false">config ClippingPlane 2</register>
<register event="zone_Mog_Garden" silent="false" runonce="false">config ClippingPlane 1</register>
<register event="zone_The_Sanctuary_of_Zi'Tah" silent="false" runonce="false">config ClippingPlane 1</register>
</autoexec>

```
Please lend me an hand, i'm crap at programming.

**Comment by cairface** [comment]
You could make a simple addon in your `windower/addons/` directory :

```lua
res = require('resources')
windower.register_event('zone', function(id)

    if res.zones[id].name == 'La Theine Plateau' then
        windower.send_command('config ClippingPlane 9')
    elseif res.zones[id].name == 'West Ronfaure' then
        windower.send_command('config ClippingPlane 2')
--[[
    elseif... etc...
]]
    end
    

end)
```

**Comment by z16** [comment]
I don't see anything immediately wrong with it, but you can more easily replace this in Lua. Go to `Windower/addons/` and create a new folder, may as well call it `autoexec`. Place an `autoexec.lua` file inside it, and edit it to contain this:
```lua
res = require('resources')

zones =
{
    ['La Theine Plateau'] = 9,
    ['Beaucedine Glacier'] = 9,
    --[[ others ]]
}

windower.register_event('zone', function(id)
    local zone = res.zones[id]
    if zones[zone.english] then
        windower.send_command('config ClippingPlane ' .. tostring(zones[zone]))
    end
end)
```

**Comment by VayuMiyoku** [comment]
Thank you for your help, I'll try both codes tomorrow. The second one seems more functional to be edited further (I'm not gonna set all the values in a row). Hope to do not miss anything.

**Comment by VayuMiyoku** [comment]
Wow the second one worked great! Thank you so much!

Now I got another question, just to simplify things and speed up everything, but i don't know if it would be possible: 
could i program that everytime i enter a zone without a pre-determined set (basically, a zone that's not in the list) windower send command "config ClippingPlane 1" ???

**Comment by joshk6656** [comment]
[code]
windower.register_event('zone', function(id)
    local zone = res.zones[id]
    if zones[zone.english] then
        windower.send_command('config ClippingPlane ' .. tostring(zones[zone.english]))
    else
        windower.send_command('config ClippingPlane 1')  
    end
end)

**Comment by VayuMiyoku** [comment]
"else" command, ofc... you made it look so obvious and made me feel so dumb lol ... that's gonna work thanks !!!

**Comment by joshk6656** [comment]
If you want to learn some about if statements, check this.

http://www.lua.org/pil/4.3.1.html

**Comment by z16** [comment]
If you want to default to one, you could even make it a one-liner:
```lua
windower.register_event('zone', function(id)
    windower.send_command('config ClippingPlane ' .. tostring(zones[res.zones[id].english] or 1))
end)
```

**Comment by VayuMiyoku** [comment]
It doesn't work anymore... can't understand why...

```
res = require('resources')

zones =
{
    ['Morimar Basalt Fields'] = 15,
    ['La Theine Plateau'] = 9,
    ['Beaucedine Glacier'] = 9,
    ['Meriphataud Mountains'] = 6,
    ['Sauromugue Champaign'] = 4,
    ['Reisenjima'] = 4,
    ['Konschtat Highlands'] = 3,
    ['Xarcabard'] = 2,
    ['Marjami Ravine'] = 2,
    ['South Gustaberg'] = 2,
    ['North Gustaberg'] = 2,
    ['Wajaom Woodlands'] = 2,
    ['Western Adoulin'] = 3,
    ['West Ronfaure'] = 2,
}

windower.register_event('zone', function(id)
    local zone = res.zones[id]
    if zones[zone.english] then
        windower.send_command('config ClippingPlane ' .. tostring(zones[zone.english]))
    else
        windower.send_command('config ClippingPlane 1')  
    end
end)
```

**Comment by z16** [comment]
Fixed this on Discord, for posterity: the event is `zone change`, not `zone`.
