### ISSUE TITLE
Magic fruit element in spells.lua

### ISSUE THREAD

**Issue by MartelRagnarok** [Windower/Issues#969]
The element value for Magic Fruit in res/spell.lua is currently 15. According to elements.lua 15 = none. Magic fruit is light so it should be 6. This is the case both on normal and dev versions of windower.

Somehow it being 15 is making my obi rules always true, even though the day element should never be 'none'. Weird.

**Comment by z16** [comment]
The value is generated from the DAT files, so it means SE has it listed as 15 there. We'll need to think about how to handle that... are you certain it's light elemental?

**Comment by MartelRagnarok** [comment]
The in game spell icon is white. Consistent with light elemental blue magic.

However, I went and actually tested magic fruit with no weather then light+obi and didn't get any bonus. I feel like it's supposed to be light, but isn't anymore. In any case, I guess that means this ticket is pointless. nothing ya'll can do about that.

**Comment by cairface** [comment]
Well, if you post on official forums saying that obi + weather doesn't affect it, that's probably the best chance :( Gonna close this
