### ISSUE TITLE
2018-01-01 Resources Update

### ISSUE THREAD

**Issue by radectheblm** [Windower/Issues#970]
On first login this morning, res/ updated to use a number of files from July - anything with a timestamp of 07/09/2017 appears to be affected, as well as the entire ~\plugins\resources\ folder.

res/
12/10/2017  10:33 PM            18,306 ability_recasts.lua
12/10/2017  10:33 PM            76,186 action_messages.lua
12/10/2017  10:33 PM           114,409 augments.lua
12/10/2017  10:33 PM           159,245 auto_translates.lua
12/10/2017  10:33 PM             2,732 bags.lua
07/09/2017  12:06 AM            64,318 buffs.lua
12/10/2017  10:33 PM             2,057 chat.lua
12/10/2017  10:33 PM             1,842 check_ratings.lua
12/10/2017  10:33 PM             1,979 days.lua
12/10/2017  10:33 PM             1,951 elements.lua
12/10/2017  10:33 PM             4,186 emotes.lua
12/10/2017  10:33 PM             1,872 encumbrance.lua
07/09/2017  12:03 AM         4,396,049 items.lua
07/09/2017  12:03 AM         4,007,382 item_descriptions.lua
12/10/2017  10:33 PM             3,229 jobs.lua
12/10/2017  10:33 PM           108,762 job_abilities.lua
12/10/2017  10:33 PM            73,978 job_points.lua
12/10/2017  10:33 PM            13,505 job_traits.lua
07/09/2017  12:03 AM           325,483 key_items.lua
06/14/2017  07:40 AM            73,934 merit_points.lua
07/09/2017  12:03 AM           330,517 monster_abilities.lua
12/10/2017  10:33 PM            25,335 monstrosity.lua
12/10/2017  10:33 PM             2,214 moon_phases.lua
07/09/2017  12:07 AM             3,985 mounts.lua
12/10/2017  10:33 PM             2,818 races.lua
12/10/2017  10:33 PM             5,106 regions.lua
12/10/2017  10:33 PM             2,110 servers.lua
12/10/2017  10:33 PM             4,801 skills.lua
12/10/2017  10:33 PM             2,039 slots.lua
07/09/2017  12:03 AM           249,878 spells.lua
12/10/2017  10:33 PM             3,198 statuses.lua
12/10/2017  10:33 PM             1,906 synth_ranks.lua
07/09/2017  12:07 AM            82,864 titles.lua
12/10/2017  10:33 PM            46,078 weapon_skills.lua
12/10/2017  10:33 PM             2,935 weather.lua
06/14/2017  07:40 AM            26,848 zones.lua

**Comment by radectheblm** [comment]
The files on https://github.com/Windower/Resources/ are still up to date, if those can be used instead - manually updating from there has restored new gear in gearswap for me.

**Comment by z16** [comment]
Yeah and those will work fine for Lua resources, but plugins still use our original style of XML resources, which we don't have backed up anywhere, so I need to regenerate them.

**Comment by z16** [comment]
Should be all fixed now, let me know if something is still not right.
