### ISSUE TITLE
Windower forums

### ISSUE THREAD

**Issue by Peligroso81** [Windower/Issues#971]
This isn't in direct relation to the program but about the windower.net website. Is anyone currently maintaining it? I went to go to the forums to download the vision map pack that is on their since I recently reinstalled from years ago but when loading the forms the page just loads to a blank white page in multiple browsers.

**Comment by z16** [comment]
The forums are currently down, and we do not plan to reopen them for discussion, but we will set up an archived copy of it which people can browse. Unfortunately I can't promise that it will happen during this week, maybe the next weekend.

**Comment by Peligroso81** [comment]
That works, just needed some stuff of of there like the map lua files.
