### ISSUE TITLE
Windower4 not loading PoL after Jan1 update.

### ISSUE THREAD

**Issue by Tiernan30** [Windower/Issues#972]
I know this issue has cropped up in the past.  After the Jan 1 update, gearswap stopped working.  Today  everything was running fine.  I reinstalled since even after this morning's update gearswap still did not work.  Since I've reinstalled windower4 will crash as it tries to launch PoL.  I get the "Launching PlayOnline" message, but the windower window disappears, PoL does not appear (nor is it in my task view), and windower is no longer in my tasks as well.  PoL launches fine without windower as well.

Windows 10 64 bit, Latest version of non-dev windower.  Going to try launching with less/no addons/plugins (not that I run a lot to begin with). 

I tried looking through older threads, but could not find a fix, so if I missed something I apologize.

Thanks in advance for any help.

**Comment by Maxxsen** [comment]
I have exactly the same Problem. Reinstalled FF11 aswell Windower 4.

**Comment by Tiernan30** [comment]
I tried no addons/plugins, to no avail.  I'm guessing it's an issue with the hook, but I have no idea why it suddenly stopped when it was working just fine.

**Comment by Tiernan30** [comment]
that is correct.

**Comment by Maxxsen** [comment]
yes correct

**Comment by thaeld43** [comment]
Same for me.  Friday (12/29) when I last logged in to the game Windower worked fine.  Tuesday (01/02) when I tried to login I experienced the same issue (Windower starts, goes to bring up POL and just vanishes).

**Comment by NeonSuspenders** [comment]
I too am having this issue. It never makes it to the PlayOnline splash image.. Here is the error report from windows.
![error](https://user-images.githubusercontent.com/35077610/34536183-0361fb5e-f08a-11e7-816d-ac008351f0dd.PNG)

**Comment by z16** [comment]
Can you guys right-click on `Windower.exe` and select `Properties`, then go to the `Details` tab and tell me what version you're using?

**Comment by thaeld43** [comment]
Sure thing...  image attached.
![windower](https://user-images.githubusercontent.com/35075221/34538890-eab60596-f093-11e7-8d41-9209a1c14cf2.png)

**Comment by z16** [comment]
The version is outdated, which explains the error, because we it's an older error we fixed a few months ago. Apparently there's an issue with updates, I'll look into it now and let you know when it's resolved.

**Comment by thaeld43** [comment]
Great, thank you!

**Comment by z16** [comment]
Can you try now?

**Comment by thaeld43** [comment]
That did it.  When I ran it some updated files came down and PO launched like normal.  Thanks so much, I can't play FFXI anymore without your wonderful software!

**Comment by z16** [comment]
Glad we could help!

**Comment by NeonSuspenders** [comment]
That's the version I have too... where can I get the new version?

**Comment by z16** [comment]
It should auto-update now. Can you try?

**Comment by NeonSuspenders** [comment]
Ah! There was the auto update. Disregard thank you very much for the help z!

**Comment by Tiernan30** [comment]
Seems to be fixed for me as well, thank you for all your hard work!
