### ISSUE TITLE
could not execute1 autoloadautoload.txt

### ISSUE THREAD

**Issue by Wakiza1982** [Windower/Issues#973]
Last night FFXI crashed on me after reopening Notepad++ in admin mode.  I didn't think much of it.  Restarted windower and I got "could not execute1 autoloadautoload.txt - File does not exist" in the Console.  No addons or plugins loaded.  I restarted again and Playonline - Member is now in Japanese.  I uninstalled Playonline and Windower 4.  Everything worked fine in vanilla, but when launching windower again, same thing happened.  I have tried this a few times now, got it to actually work once, but forgot to adjust the default logout timer, and came back from afk and had disconnected.  I did not reinstall FFXI itself.  Please help.

**Comment by Nifim** [comment]
If issue still exists please come to our discord for assistance.
