### ISSUE TITLE
Windower crash on startup. Error: "The directory name is invalid"

### ISSUE THREAD

**Issue by aregowe** [Windower/Issues#977]
Received this error upon starting Windower. Error just simply says "The directory name is invalid" and windower crashes.

This is what I've done:

* Uninstalled FFXI
* Ran Ccleaner, cleaned registry
* Reinstalled FFXI to a new SSD
* Uninstalled Windower
* Ran Ccleaner, cleaned registry
* Reinstalled Windower

Now, Windower is giving this error. I assume it's because FFXI is located in a completely different drive. Is it possible to point Windower to the new drive somehow?

Recommendation: Have a setting that lets the user select where their POL / FFXI directory is.

Thank you.

**Comment by nuhir** [comment]
I'm having the same issue as well.  I've done the same, short of uninstalling FFXI.  Here is a copy of my crash.log.  This happens every time the Fall Creator's update installs, and the only fix that has worked was to roll back the install.

[crash.log](https://github.com/Windower/Issues/files/1680922/crash.log)

**Comment by alphaONE2** [comment]
Windower picks up the install directory from the exact same registry keys that PlayOnline does. Check the registry and see if the paths there are correct.

#### 32-bit Windows
|   |   |
|:---:|---|
| JP | HKEY_LOCAL_MACHINE\SOFTWARE\PlayOnline\InstallFolder |
| NA | HKEY_LOCAL_MACHINE\SOFTWARE\PlayOnlineUS\InstallFolder |
| EU | HKEY_LOCAL_MACHINE\SOFTWARE\PlayOnlineEU\InstallFolder |

#### 64-bit Windows
|   |   |
|:---:|---|
| JP | HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\PlayOnline\InstallFolder |
| NA | HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\PlayOnlineUS\InstallFolder |
| EU | HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\PlayOnlineEU\InstallFolder |

The values in those keys are as follows

|   |   |
|---:|---|
| 0001 | Final Fantasy XI |
| 0002 | Tetra Master |
| 1000 | PlayOnline Viewer |

**Comment by joshk6656** [comment]
Is creators update preventing us from reading the registry?

**Comment by Nifim** [comment]
This seems to be a registry issue
