### ISSUE TITLE
BLUguide mouseover problem

### ISSUE THREAD

**Issue by Arliman** [Windower/Issues#982]
Wanting to utilize this addon however when the interface menu comes up, the mouse does not correlate with the selection highlight. I'm running the game in 3440x1440 with Windower automatically adjusting the aspect ratio. Im not sure if this has anything to do with it, the mouse works fine for ingame actions. 

With the add-on menu open:
The mouse has to be NW and about two inches away from the buttons for the highlight to appear, 
and as the mouse is moved, so does the highlight accordingly. Unfortunately, this makes it impossible to target anything in the left table or the menu selections. Hopefully this can be addressed.

Thanks!

**Comment by cairthenn** [comment]
Sounds like a DPI awareness issues. You can change the DPI scaling of POL on its compatibility tab (Click the box and choose "Application").

If it's an issue with just this addon, submit it to the addon author.
