### ISSUE TITLE
Boxdestroyer not offering hints when clicking on brown chests

### ISSUE THREAD

**Issue by GenTeal** [Windower/Issues#983]
I have just returned to FFXI.  I have noticed that when I click on a brown chest there are no hints being shown.

**Comment by zetaepyon** [comment]
Strings probably need to be updated after the recent update. I can fix it tonight if it hasn't already been addressed.

**Comment by zetaepyon** [comment]
Actually it appears to be working - the messages have not changed. Can you try reloading BoxDestroyer when in the zone where you want to use it?

**Comment by zetaepyon** [comment]
Upon further investigation it looks like this was already fixed in the dev branch of the addon repository. I'll see about getting the changes merged to live.

**Comment by zetaepyon** [comment]
Closing as the fix has been pushed to live.
