### ISSUE TITLE
Resources Item_discription

### ISSUE THREAD

**Issue by sebyg666** [Windower/Issues#987]
is there a way i could get a copy of the resources file for item discriptions without the english chopped off on the end. I'm trying to use the file to pull all the set bonuses from every item, but many are completely chopped off. 
for example "Hachiya Chain. +3" literally has "Set:" and the rest of the text is chopped off.
i have 930+ items and about 30% of them are chopped off, and id preferable rather not have to go through each individual item and correct it manually.

Any help would be highly appreciated thanks.

**Comment by z16** [comment]
Should be fixed, let us know if the issue persists for you.
