### ISSUE TITLE
POL Crashes on boot; changes FFXI config to "Borderless Window" instead of "Fullscreen"

### ISSUE THREAD

**Issue by ghost** [Windower/Issues#992]
So my apologies if this has been reported before; I didn't see anything that sounded like the issue that I'm having. Basically when I press the button to choose my profile, the PlayOnline splash screen shows up. However, before it loads, it errors out saying 'PlayOnline Viewer has stopped working' and then closes without giving me more information. 

I believe I've figured out why though. When I enter the FFXI configuration application, I have it set to "Fullscreen mode"; however, when I attempt to perform the actions above, after the crash, I check the configuration applcation and it has switched to "Borderless window mode".  My guess is that the hook is unintentionally flipping that switch somehow.

I'm on Windows 10 Pro. The dmp is attached

[pol.exe.7900.zip](https://github.com/Windower/Issues/files/1953769/pol.exe.7900.zip)

**Comment by z16** [comment]
It's not unintentional, hook changes quite a few registry entries depending on your settings in the Launcher. Those are then displayed that way in the FFXI config tool. I assume borderless window is selected in the launcher as well? Does it work if you set it to full screen?

**Comment by cornyhorse** [comment]
Unfortunately, no. I tried all of the options. The reason I had mentioned the FFXI configuration mode is that I recall when the official windowed mode was introduced that you had to have it set to 'full screen' for windower to work, so I thought maybe it was incorrectly configuring it.  Oh well, back to the drawing board!

**Comment by cairthenn** [comment]
What sort of mouse are you using?

**Comment by cornyhorse** [comment]
Well, I use a Logitec G600 on my primary machine. I'm using that to Chrome Remote Desktop into this second machine. It worked until a few weeks ago and I can still use FFXI without Windower no problem too.  Occurs to me I probably should have mentioned that sooner, I'm sure I'm an edge case.

**Comment by cairthenn** [comment]
Could you let me know what happens with this:

https://www.dropbox.com/s/ddbhqr2n8ww98t7/Hook.dll?dl=0

**Comment by cornyhorse** [comment]
Oops, just realized I logged in from the wrong GitHub account. Hope that didn't confuse anyone. That Hook did work swimmingly. Fixes all the issues, thanks!

**Comment by notnate75** [comment]
I'm having the same issue, tried all suggestions above including the new hook.dll and it still hangs on pol splash screen
