### ISSUE TITLE
extdata May be wrong on Dim. Ring (Holla)

### ISSUE THREAD

**Issue by Selindrile** [Windower/Issues#996]
Honestly can't remember where I got this function but it seems to work fine on most items, though I admittedly don't really understand it, get_item_next_use('Dim. Ring (Holla)').usable returns true when it's not on cooldown whether it's equipped or not, unlike other items that only return true when they're equipped/ready to use, (have turned blue in your inventory), I'm unsure if this extends to the other dimensional rings, I'm assuming this is a resources issue and not an issue with this code, but sorry if I'm wrong!

```
function get_item_next_use(name)--returns time that you can use the item again
    for _,n in pairs({"inventory","wardrobe","wardrobe2","wardrobe3","wardrobe4"}) do
        for _,v in pairs(gearswap.items[n]) do
            if type(v) == "table" and v.id ~= 0 and res.items[v.id].english == name then
                return extdata.decode(v)
            end
        end
    end
end

**Comment by cairthenn** [comment]
It's reading the ExtData of the item to check the timer data on the object. The ExtData has no knowledge of whether the item is equipped already or not. That data is provided in gearswap separately.

**Comment by Selindrile** [comment]
Ah well get_item_next_use('Warp Ring').usable or get_item_next_use('Capacity Ring').usable etc, all only return true if the item is equipped and usable, get_item_next_use(Dim. Ring (Holla)').usable returns true if it's off cooldown, regardless of whether it's equipped/usable or not.

Was using a return of true to use the item, otherwise send the command to equip it, works on what I've tried up until Dim. Ring (Holla).

**Comment by cairthenn** [comment]
I'll look at it a bit more.. but it seems the game itself is setting the bit that ExtData reads for 'usable' differently on Dimensional Rings. I'm pretty sure it's reading the appropriate bit though.

**Comment by cairthenn** [comment]
Okay, nevermind. Here's how it works:

There's a flag on the item that we use to determine if an item is usable. If it's equipped, this flag is flipped off until the timer counts down, and then the flag is turned on. Unequipped, this flag depends on the items cooldown.

SE does this, so we don't have control over the specifics.

**Comment by Selindrile** [comment]
Thank you for taking a look, but yeah it's just odd that the extdata is different for that item than others like it, in similar situations, my problem was trying to figure out if a piece of gear was equipped without knowing the slot beforehand, but I fixed it with a for loop to check for the item in each slot and am using that.

**Comment by cairthenn** [comment]
It's not different after all, I was mistaken originally. I went through each item and looked at the raw extdata. It functions exactly as I described it.

Edit: FWIW, un-equipping the item after it has gained its 'usable' flag doesn't reset this flag, reequipping it resets it.

**Comment by Selindrile** [comment]
Ah, I'm just struggling because the function doesn't seem to return things as expected on all items, .usable definitely seems to work differently on Dim. Ring (Holla), and

get_item_next_use('Behemoth Suit +1').next_use_time seems to always return a nil value for me, as well, seems to work on some items just fine, but others not at all.

**Comment by Selindrile** [comment]
I apologize then for my ignorance, and thank you for the information, the way it was described to me was that .usable would only be true in the case it was both equipped and ready for use, in my other cases I was checking if it was equipped anyway, so it didn't matter, found a way do that without needing to know the slot beforehand as I said, but the following issue, hopefully... is a real one.

get_item_next_use('Behemoth Suit +1').next_use_time    seems to always be returning nil regardless of time remaining.
