### ISSUE TITLE
POL Crashing when moving from Windower

### ISSUE THREAD

**Issue by njewell** [Windower/Issues#998]
POL is crashing when moving from windower. Running windows 10. NVIDIA GeForce GTX 970. Works fine running FFXI without windower.  All plugins and addons are turned off. Uninstalled/reinstalled both windower and FFXI. Tried easing the dim settings and didn't help. 

Here is the link to the crash dump. 

https://drive.google.com/file/d/1_bUA6YyHHJOQNeGwTBEPw6ONGLlEMpF3/view?usp=sharing

**Comment by cairthenn** [comment]
You can host a crash dump somewhere like google drive or dropbox.

**Comment by cairthenn** [comment]
Are you on a private server? Looks like we're failing to locate FFXI's command handler function.

**Comment by njewell** [comment]
I am not. Just using normal ffxi.

**Comment by cairthenn** [comment]
Really not sure. There are a few modules loaded I don't normally see that may be interfering with our hooking. "RivaTuner" specifically may be worth looking in to.

**Comment by njewell** [comment]
Uninstalled RivaTuner and playonline loaded. Problem resolved. Thank you!

**Comment by Nifim** [comment]
RivaTuner was cause.
