### ISSUE TITLE
Trying to search for player Status crashes game

### ISSUE THREAD

**Issue by Iminiillusions** [Windower/Issues#999]
So I'm trying to find a character called Status and upon pressing enter when I type "/sea all status" my game crashes. has happened multiple times, and not just to me, Crash Dump attached.

[pol.exe.11428.zip](https://github.com/Windower/Issues/files/2029467/pol.exe.11428.zip)

**Comment by cairthenn** [comment]
This happens in vanilla XI, file a report with SE.
